### ISSUE TITLE
Bug? when adding data view for person

### ISSUE THREAD

**Issue by demersus** [SparkDevNetwork/Rock#1206]
I am not sure if this is isolated to our environment, or if it is a bug in rock.

I get this Exception Message:
````
Error
Object reference not set to an instance of an object.
   at Rock.Field.FieldType.FilterValueControl(Dictionary`2 configurationValues, String id, Boolean required)
   at Rock.Field.Types.DefinedValueFieldType.FilterValueControl(Dictionary`2 configurationValues, String id, Boolean required)
   at Rock.Field.FieldType.FilterControl(Dictionary`2 configurationValues, String id, Boolean required)
   at Rock.Reporting.EntityHelper.AddEntityFieldForAttribute(List`1 entityFields, AttributeCache attribute)
   at Rock.Reporting.EntityHelper.GetEntityFields(Type entityType, Boolean includeOnlyReportingFields)
   at Rock.Reporting.DataFilter.PropertyFilter.CreateChildControls(Type entityType, FilterField filterControl)
   at Rock.Web.UI.Controls.FilterField.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at Rock.Web.UI.Controls.FilterField.set_FilteredEntityTypeName(String value)
   at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Control parentControl, DataViewFilter filter, String filteredEntityTypeName, Boolean setSelection, RockContext rockContext) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 796
   at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Control parentControl, DataViewFilter filter, String filteredEntityTypeName, Boolean setSelection, RockContext rockContext) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 832
   at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Nullable`1 filteredEntityTypeId, DataViewFilter filter, Boolean setSelection, RockContext rockContext) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 776
   at RockWeb.Blocks.Reporting.DataViewDetail.etpEntityType_SelectedIndexChanged(Object sender, EventArgs e) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 934
   at System.Web.UI.WebControls.ListControl.OnSelectedIndexChanged(EventArgs e)
   at System.Web.UI.Page.RaiseChangedEvents()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
````
When trying to add a data view, and selecting "Person" from the "Applies To" field.

Steps to produce:  
1. Menu -> Tools -> (Reporting) Data Views
2. Click on category in tree menu
3. Click + Dataview button
4 Select "Person" from "Applies To" field

Rock McKinley 3.4

Thank you.

**Comment by arranf** [comment]
Hey Nik,

This is definitely just specific to your environment!


On 21 August 2015 at 00:44, Nik Petersen <notifications@github.com> wrote:

> I am not sure if this is isolated to our environment, or if it is a bug in
> rock.
>
> I get this Exception Message:
>
> Error
> Object reference not set to an instance of an object.
>    at Rock.Field.FieldType.FilterValueControl(Dictionary`2 configurationValues, String id, Boolean required)
>    at Rock.Field.Types.DefinedValueFieldType.FilterValueControl(Dictionary`2 configurationValues, String id, Boolean required)
>    at Rock.Field.FieldType.FilterControl(Dictionary`2 configurationValues, String id, Boolean required)
>    at Rock.Reporting.EntityHelper.AddEntityFieldForAttribute(List`1 entityFields, AttributeCache attribute)
>    at Rock.Reporting.EntityHelper.GetEntityFields(Type entityType, Boolean includeOnlyReportingFields)
>    at Rock.Reporting.DataFilter.PropertyFilter.CreateChildControls(Type entityType, FilterField filterControl)
>    at Rock.Web.UI.Controls.FilterField.CreateChildControls()
>    at System.Web.UI.Control.EnsureChildControls()
>    at Rock.Web.UI.Controls.FilterField.set_FilteredEntityTypeName(String value)
>    at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Control parentControl, DataViewFilter filter, String filteredEntityTypeName, Boolean setSelection, RockContext rockContext) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 796
>    at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Control parentControl, DataViewFilter filter, String filteredEntityTypeName, Boolean setSelection, RockContext rockContext) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 832
>    at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Nullable`1 filteredEntityTypeId, DataViewFilter filter, Boolean setSelection, RockContext rockContext) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 776
>    at RockWeb.Blocks.Reporting.DataViewDetail.etpEntityType_SelectedIndexChanged(Object sender, EventArgs e) in c:\inetpub\rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 934
>    at System.Web.UI.WebControls.ListControl.OnSelectedIndexChanged(EventArgs e)
>    at System.Web.UI.Page.RaiseChangedEvents()
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>
> When trying to add a data view, and selecting "Person" from the "Applies
> To" field.
>
> Steps to produce:
>
> 1. Menu -> Tools -> (Reporting) Data Views
> 2. Click on category in tree menu
> 3. Click + Dataview button
> 4 Select "Person" from "Applies To" field
>
> Rock McKinley 3.4
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/1206>.
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by MrUpsideDown** [comment]
From the error message, it seems there is a problem with one of the Defined Values used by a Person Attribute you have added. To troubleshoot this issue, I suggest you begin by looking at any recent changes to your Person Attributes.

**Comment by demersus** [comment]
Thank you.  I will investigate the defined values to further debug our environment.  I wasn't familiar enough to know where to look.  You're the best!

(Closing issue now)

**Comment by azturner** [comment]
@demersus , We're going to keep this open. Even if there's an invalid defined value, we shouldn't be throwing an unhandled exception like that. If you find any more details feel free to add them here.

**Comment by demersus** [comment]
Sounds good.  I will let you know what I find, when I solve it.  Its most likely an issue caused by the data migration we are using.   We built a custom migration tool to move data from our old version of Arena.

**Comment by MrUpsideDown** [comment]
@azturner Good call - it's always encouraging to see that kind of commitment to "getting it right" rather than just "getting it done"! +1

**Comment by demersus** [comment]
Okay, I changed my development environment to include the full source of Rock linked to the RockWeb project.  I can see where the error is originating, but am having trouble understanding what is going on.  I think it's my unfamiliarity with C# that is making it difficult for me to debug.

Here is the current backtrace:
````
Error
Object reference not set to an instance of an object.
   at Rock.Field.FieldType.FilterValueControl(Dictionary`2 configurationValues, String id, Boolean required) in m:\Projects\Rock\Rock\Field\FieldType.cs:line 278
   at Rock.Field.Types.DefinedValueFieldType.FilterValueControl(Dictionary`2 configurationValues, String id, Boolean required) in m:\Projects\Rock\Rock\Field\Types\DefinedValueFieldType.cs:line 400
   at Rock.Field.FieldType.FilterControl(Dictionary`2 configurationValues, String id, Boolean required) in m:\Projects\Rock\Rock\Field\FieldType.cs:line 219
   at Rock.Reporting.EntityHelper.AddEntityFieldForAttribute(List`1 entityFields, AttributeCache attribute) in m:\Projects\Rock\Rock\Reporting\EntityHelper.cs:line 221
   at Rock.Reporting.EntityHelper.GetEntityFields(Type entityType, Boolean includeOnlyReportingFields) in m:\Projects\Rock\Rock\Reporting\EntityHelper.cs:line 181
   at Rock.Reporting.DataFilter.PropertyFilter.CreateChildControls(Type entityType, FilterField filterControl) in m:\Projects\Rock\Rock\Reporting\DataFilter\PropertyFilter.cs:line 153
   at Rock.Web.UI.Controls.FilterField.CreateChildControls() in m:\Projects\Rock\Rock\Web\UI\Controls\Data View Filters\FilterField.cs:line 317
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.WebControls.CompositeControl.RecreateChildControls()
   at Rock.Web.UI.Controls.FilterField.set_FilteredEntityTypeName(String value) in m:\Projects\Rock\Rock\Web\UI\Controls\Data View Filters\FilterField.cs:line 144
   at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Control parentControl, DataViewFilter filter, String filteredEntityTypeName, Boolean setSelection, RockContext rockContext) in m:\Projects\Rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 796
   at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Control parentControl, DataViewFilter filter, String filteredEntityTypeName, Boolean setSelection, RockContext rockContext) in m:\Projects\Rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 832
   at RockWeb.Blocks.Reporting.DataViewDetail.CreateFilterControl(Nullable`1 filteredEntityTypeId, DataViewFilter filter, Boolean setSelection, RockContext rockContext) in m:\Projects\Rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 776
   at RockWeb.Blocks.Reporting.DataViewDetail.etpEntityType_SelectedIndexChanged(Object sender, EventArgs e) in m:\Projects\Rock\RockWeb\Blocks\Reporting\DataViewDetail.ascx.cs:line 934
   at System.Web.UI.WebControls.ListControl.OnSelectedIndexChanged(EventArgs e)
   at System.Web.UI.WebControls.DropDownList.RaisePostDataChangedEvent()
   at System.Web.UI.WebControls.DropDownList.System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent()
   at System.Web.UI.Page.RaiseChangedEvents()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
````

````c#
 public virtual Control FilterValueControl( Dictionary<string, ConfigurationValue> configurationValues, string id, bool required )
        {
            var control = EditControl( configurationValues, id );
            control.ID = string.Format( "{0}_ctlCompareValue", id ); // <-- ERROR HAPPENS HERE
            if ( control is WebControl )
            {
                ( (WebControl)control ).AddCssClass( "js-filter-control" );
            }
            return control;
        }
````
When inspecting the control variable, while debugging, it appears to be null on one of our current attributres.  The result from the previous call: `EditControl( configurationValues, id );` is null.  Here `id = "BaptismsFirstContactResponse"`.

I am not sure how or why `EditControl` would be returning null.  It appears to be simply initializing and returning a `Rock.Web.UI.Controls.RockTextBox`.  If I rewrite like so:
````c#
 public virtual Control FilterValueControl( Dictionary<string, ConfigurationValue> configurationValues, string id, bool required )
        {
            var control = EditControl( configurationValues, id );
//<Code Added>
            if (control == null)
            {
                control = new Rock.Web.UI.Controls.RockTextBox();
            }
//</Code Added>
            control.ID = string.Format( "{0}_ctlCompareValue", id );
            if ( control is WebControl )
            {
                ( (WebControl)control ).AddCssClass( "js-filter-control" );
            }
            return control;
        }
````
It seems to work....

Anyone have an idea what could be going wrong?
Thank you in advance!
