### ISSUE TITLE
Online Giving - FinancialPersonSavedAccount with NULL CreditCardTypeValueId causes NullReferenceException

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1231]
On McKinley 3.5 - I've been seeing some NullReferenceExceptions few and far between with online giving. It seems like sometimes, a when card number is saved the CreditCardTypeValueId ends up NULL:

![2015-09-03 14_03_50-sqlquery6 sql - rock newpointe org master sa 69 _ - microsoft sql server mana](https://cloud.githubusercontent.com/assets/1859094/9666674/72020c24-5245-11e5-90f4-dd9500c42274.png)

When someone tries to give with this saved card again for a one-time gift, they get a NullReferenceException (or the next button goes to inactive state and they get no error - Chrome only)

I went through the database and set a value for those (but I don't know the card type because I can't see the first digit on the card - does that matter?) and that fixes the problem.  But I can't reproduce how they are getting saved with NULL values in the first place.

**Comment by bwitting** [comment]
If it helps, here's the stack trace from the exception log:

```   
System.NullReferenceException: Object reference not set to an instance of an object
   at Rock.Model.FinancialPersonSavedAccount.GetReferencePayment()
   at RockWeb.Blocks.Finance.TransactionEntry.GetPaymentInfo()
   at RockWeb.Blocks.Finance.TransactionEntry.ProcessPaymentInfo(String& errorMessage)
   at RockWeb.Blocks.Finance.TransactionEntry.btnNext_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```
