### ISSUE TITLE
Recurring Exception: A potentially dangerous Request.QueryString value was detected

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1233]
How can I stop this continually recurring Exception error? 
We have other exception errors like it.
We don't have a give page, and we don't have a loreen mcneil.  It looks like this is someone attempting to plant some html or something into our site?  I don't know how to stop the error, and does this need to be prevented in some way?  Thanks.

An exception has occurred. Details of this error can be found below: 
An error occurred on the Rock site on page: 
http://porirua.elim.org.nz:80/Http404Error.aspx?404;http://porirua.elim.org.nz:80/index.php/donate?name=Loreen&email=loreen.mcneill%3Cspan%20class='spancrypt'%3E %3C/span%3Egmail.com&website=http://sandwichesspot.blog.com/&address=KQ&latitude=&longitude=&tnc-checkbox=y&parent=0&task=commentSave&pageItemId=492
HttpRequestValidationException in System.Web
Message
A potentially dangerous Request.QueryString value was detected from the client (="nbsp;gmail.com").
Stack Trace
at System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection)
at System.Web.HttpRequest.<>c__DisplayClass5.b__3(String key, String value)
at System.Web.HttpValueCollection.EnsureKeyValidated(String key)
at System.Web.HttpValueCollection.GetValues(String name)
at System.Web.UI.Page.DeterminePostBackMode()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.http404error_aspx.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-

**Comment by arranf** [comment]
I'm seeing a similar exception for password resets.
