### ISSUE TITLE
Event Registration "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by nateh777** [SparkDevNetwork/Rock#1256]
I'm sure it is still a work in progress, but I wanted to let you know of an exception while I was trying out the new Event Registration in the develop branch. When I attempt to register without being logged in I receive this error: 
```
An Error Occurred Processing Your Registration
Object reference not set to an instance of an object.
```

Looking at the exception list in Rock Admin this is the error:
```
System.NullReferenceException Rock Object reference not set to an instance of an object. 
   at Rock.Data.DbContext.WrapTransaction(Action action) in C:\Users\Nate\Documents\Visual Studio 2015\Projects\Rock\Rock\Data\DbContext.cs:line 75
   at RockWeb.Blocks.Event.RegistrationEntry.SaveChanges() in c:\Users\Nate\Documents\Visual Studio 2015\Projects\Rock\RockWeb\Blocks\Event\RegistrationEntry.ascx.cs:line 1138
```

I'm looking forward to this new feature in 4.0, can't wait to get it.

-Nate

**Comment by nateh777** [comment]
I also should have stated it was an event with no cost and it was when I hit next on the last step ("Review Registration") when I received this error.
