### ISSUE TITLE
Rockit SDK is broken

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1308]
Attempting to run http://www.rockrms.com/Rock/Developer/Rockit with a given domain of  "rocksolidchurch.org" produces:
```
Unable to build custom Rockit.
at RockWeb.Plugins.org_sparkdevnetwork.SDK.Rockit.BuildRockit(String cachedRockitZip, String domainName, String version)
at RockWeb.Plugins.org_sparkdevnetwork.SDK.Rockit.bbtnCreateRockit_Click(Object sender, EventArgs e)
```

**Comment by nairdo** [comment]
Fixed by preventing someone from using the special domain "rocksolidchurch.org".
