### ISSUE TITLE
[v4 Update] System.Text.EncoderFallbackException in Statement Generator

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1332]
When testing the statement generator on V4, I get the following exception:

`System.Text.EncoderFallbackException: Unable to translate Unicode character \uDCC5 at index 971 to specified code page.`

Stack Trace:
```
at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type)
   at Newtonsoft.Json.JsonTextWriter.Close()
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at Rock.Utility.RockJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.d__1b.MoveNext()
```

I'm assuming that this character is in a filed like name or address that is getting merged on the dynamic pdf - When I run it with just me it works fine. When I run it with a individuals with contributions or a big data view, I get the error.  I'll see if I can figure out how to search the database for that unicode character.

**Comment by bwitting** [comment]
I did a full text database search for `\uDCC5`, `U+DCC5` `&#xDCC5;`, `&#56517;`, and `edb385` (see http://www.scarfboy.com/coding/unicode-tool?s=U%2BDCC5) - no dice. (Well, except for `\uDCC5`, but only because it's in the exception log.)  I'm not sure what else to try.  @mikepetersonccv, what do you think I should do to debug this?  Thanks!

**Comment by mikepetersonccv** [comment]
@bwitting  as far as searching for Unicode, you could do something like this 
```sql
select * from Person where cast(LastName as varchar(max)) != LastName
```

**Comment by bwitting** [comment]
Thanks @mikepetersonccv.  I tried that with a bunch of the person fields and didn't get any results.  The weird thing is that the 1.3 statement generator works fine with v3.5 and I don't get that error.  But using a fresh copy of the exact same database updated to 4.0, the 1.4 statement generator gets that issue.

**Comment by bwitting** [comment]
Found it! There were some weird unicode characters in the Summary column of the FinancialTransaction table (that got imported from Fellowship One).  Removing those fixed the problem.  Thanks for the tip @mikepetersonccv!

**Comment by mikepetersonccv** [comment]
@bwitting Cool! I was having trouble reproducing it so I'm glad you figured it out!
