### ISSUE TITLE
Metric detail block stopped working after 4.0 update. 

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#1340]
The detail error is below. 

c:\inetpub\vhosts\mcchurch.me\httpdocs\Blocks\Reporting\MetricDetail.ascx.cs(704): error CS0103: The name 'hlScheduleFriendlyText' does not exist in the current context

   at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at System.Web.UI.TemplateControl.LoadControl(String virtualPath)
   at Rock.Web.UI.RockPage.OnInit(EventArgs e)

**Comment by azturner** [comment]
@kcirgjd , v4.0 updated the MetricDetail.ascx.cs (code behind) file, but not the markup file. However, the markup (MetricDetail.ascx) has had the hlScheduleFriendlyText control since 1.3.2. Is there any chance you might have modified these blocks?  If you can send your two \blocks\reporting\MetricDetail.* files, I'll take a look a what might be causing the error.

**Comment by kcirgjd** [comment]
Weird. Thanks!

[MetricDetail.ascx.zip](https://github.com/SparkDevNetwork/Rock/files/72475/MetricDetail.ascx.zip)

**Comment by kcirgjd** [comment]
I just came across another blocks that are not working. I figured I would add it here first in case it's all the same issue. 
##the knows relationships block on on a profile page. 
c:\inetpub\vhosts\mcchurch.me\httpdocs\Blocks\Crm\PersonDetail\Relationships.ascx.cs(352): error CS0103: The name 'lAccessWarning' does not exist in the current context

   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at System.Web.UI.TemplateControl.LoadControl(String virtualPath)
   at Rock.Web.UI.RockPage.OnInit(EventArgs e)
[Relationships.zip](https://github.com/SparkDevNetwork/Rock/files/72486/Relationships.zip)

**Comment by kcirgjd** [comment]
And now when i go into edit a profile: 

Message
c:\inetpub\vhosts\mcchurch.me\httpdocs\Blocks\Crm\PersonDetail\Relationships.ascx.cs(352): error CS0103: The name 'lAccessWarning' does not exist in the current context

Stack Trace
at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)
at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
at System.Web.UI.TemplateControl.LoadControl(String virtualPath)
at Rock.Web.UI.RockPage.OnInit(EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.themes_rock_layouts_persondetail_aspx.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by kcirgjd** [comment]
It's really odd i just got the same message referecing the relationship block when i clicked to edit someone's profile.

**Comment by kcirgjd** [comment]
@azturner I missed up earlier and send old file.
[MetricDetail.zip](https://github.com/SparkDevNetwork/Rock/files/72504/MetricDetail.zip)

**Comment by azturner** [comment]
@kcirgjd , You are missing updates that should have been installed with the 3.1 and 3.2 updates. I'm not sure how your environment could be in that state since 3.2 is required before you can install 3.3. And 3.3 is required for 3.4... etc. Can you share a screenshot of your Rock\App_Data\Packages folder. Should look something like this...

![image](https://cloud.githubusercontent.com/assets/548180/12010443/ac535b8e-ac64-11e5-86b3-4e91247fa83b.png)

Also any insight on how you update/deploy your environment might be helpful to understand how that might have happened.

**Comment by kcirgjd** [comment]
That's super strange. 
![update packages](https://cloud.githubusercontent.com/assets/7595345/12010484/098bebb0-ac77-11e5-9618-e5a99d60fd45.png)

We are running on 3Essentials. I don't know if we would do anything that would goof this up. I don't know what other details you would be looking for on deployment.

**Comment by azturner** [comment]
Do you recall if you previously deleted any files from this folder (maybe to save space)? What's concerning is that the 1.0 - 3.0 update packages are all dated 12/25/15 so they were missing, and downloaded (as prerequisites) at the same time you updated to v4.0.  I suspect, the files from those earlier packages were then added to your environment but since you already had 3.1 - 3.4, those updated files were not reapplied. @nairdo thoughts?

In the mean time, I'll add all the files that were updated in versions 3.1 - 3.4 to a zip file that you can then use to get your files current.

deleting files from that folder. What's

**Comment by kcirgjd** [comment]
I remember considering it a while ago when we ran out of space. But I remember being hesitant worried about how it would effect future updates. I am pretty sure I decided against it (and it turned out Plesk wasn't automatically deleting temp files it created and had sucked up >15gb). 

Thanks so much!

**Comment by azturner** [comment]
@kcirgjd Here are the files that were updated in versions 3.1 through 3.4 that were not updated by v4.0. 

[Rock.zip](https://github.com/SparkDevNetwork/Rock/files/72715/Rock.zip)

**Comment by kcirgjd** [comment]
Thank you so much!

**Comment by kcirgjd** [comment]
I was able to get them all updated and tested the issues I was having. They are all resolved. 

THANK YOU SOOO MUCH!!!!
