### ISSUE TITLE
NullReferenceException when trying to Copy a Registration Template

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1356]
In v1.4.1

When going to a Registration Template and clicking Copy, a NullReferenceException occurs. 

```
Message
Object reference not set to an instance of an object.

Stack Trace
at Rock.Web.UI.Controls.RegistrationTemplateFormEditor.<BindFieldsGrid>b__1(RegistrationTemplateFormField a)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Rock.Web.UI.Controls.RegistrationTemplateFormEditor.BindFieldsGrid(List`1 formFields)
at RockWeb.Blocks.Event.RegistrationTemplateDetail.BuildFormControl(Control parentControl, Boolean setValues, RegistrationTemplateForm form, Nullable`1 activeFormGuid, Boolean showInvalid)
at RockWeb.Blocks.Event.RegistrationTemplateDetail.BuildControls(Boolean setValues, Nullable`1 activeFormGuid)
at RockWeb.Blocks.Event.RegistrationTemplateDetail.ShowEditDetails(RegistrationTemplate RegistrationTemplate, RockContext rockContext)
at RockWeb.Blocks.Event.RegistrationTemplateDetail.btnCopy_Click(Object sender, EventArgs e)
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)```

**Comment by azturner** [comment]
@bwitting I'm having trouble reproducing this. It looks like its an issue with one of the form fields. Is it only happening on a specific template? Is so, can you share a screenshot of the fields on that template.

**Comment by bwitting** [comment]
@azturner Yup, it was only happening on a specific template (the only one we had).  I created another one with only a single text field and it copied just fine.
Here's a screenshot of the fields:
![2016-01-20 16_44_22-event registration _ rock rms](https://cloud.githubusercontent.com/assets/1859094/12464052/23c00602-bf95-11e5-94d0-019e77843db7.png)

I'm having my admin who made the form delete 1 field at a time and try to copy to see if we can find the culprit. (this is just a test so no big deal)

**Comment by bwitting** [comment]
@azturner - when we removed the Allergy / Person Attribute field, that fixed the issue.
