### ISSUE TITLE
V1.4.3 Content Approval Error

### ISSUE THREAD

**Issue by JayGreentree** [SparkDevNetwork/Rock#1406]
I am getting this warning in the Content Approval page and I believe I have all security roles enabled for myself.

Error
Object reference not set to an instance of an object.

   at RockWeb.Blocks.Cms.ContentChannelItemView.BindAttributes(ContentChannel channel) in c:\inetpub\vhosts\thursdaychurch.co\httpdocs\Blocks\Cms\ContentChannelItemView.ascx.cs:line 526
   at RockWeb.Blocks.Cms.ContentChannelItemView.LoadViewState(Object savedState) in c:\inetpub\vhosts\thursdaychurch.co\httpdocs\Blocks\Cms\ContentChannelItemView.ascx.cs:line 76
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by nairdo** [comment]
Steps to repo the issue. Create a channel, view the channel in Tools > Website > Content page, then delete the channel, then return to the Tools > Website > Content page.  I have the fix -- check the channel is not null before attempting to Bind, etc after line 75:
```
    var channel = new ContentChannelService( new RockContext() ).Get( SelectedChannelId.Value );
    if ( channel != null )
    {
        BindAttributes( channel );
        AddDynamicControls( channel );
    }
``` 

This will probably go into a 1.4.4 hotfix.
