### ISSUE TITLE
Giving Error - "A history point can only be created during an asynchronous postback."

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1438]
On 4.3 and 4.4 - 
I can't reproduce this, but in some situations when pressing Next button on the Give Now block, a `System.InvalidOperationException` occurs - `A history point can only be created during an asynchronous postback`.

Stack trace:

```
at System.Web.UI.ScriptManager.PrepareNewHistoryPoint()
   at System.Web.UI.ScriptManager.AddHistoryPoint(String key, String value, String title)
   at RockWeb.Plugins.org_newpointe.BlockMods.Finance.TransactionEntry.btnNext_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

This has happened 15 times now in the past 3 weeks, some with logged in users and some when a user wasn't logged in.  When it happens, the user is directed to the 404 page.

(@azturner, here's the exception: https://rock.newpointe.org/page/173#&&dww2KiUvtLJvib8KR4qzFcacVW2Phu7MjY0N//kfVdmpSB+rwq9pwuAUYQ6wX5HzYsKpIS4Yyz/Fcf4shriGsrcwc+6b6MB0rntJDYi5OGk=)

**Comment by mikejed** [comment]
Closing this issue because it has reportedly not been observed since this time (checked with @Tschrock )
