### ISSUE TITLE
Error importing Sample Data

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1536]
@nairdo 
I tried to import some sample data today using the latest develop branch and I got an error.

```
Oops! That wasn't supposed to happen. The error was:
String was not recognized as a valid DateTime.

at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
at System.DateTime.Parse(String s)
at RockWeb.Blocks.Examples.SampleData.AddRegistrationInstances(XElement elemRegistrationInstances, RockContext rockContext) in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 998
at RockWeb.Blocks.Examples.SampleData.<>c__DisplayClass5.<ProcessXml>b__4() in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 549
at Rock.Data.DbContext.WrapTransaction(Action action) in C:\Users\Arran\Documents\GitHub\Spark\Rock\Rock\Data\DbContext.cs:line 75
at RockWeb.Blocks.Examples.SampleData.ProcessXml(String sampleXmlFile) in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 516
at RockWeb.Blocks.Examples.SampleData.bbtnLoadData_Click(Object sender, EventArgs e) in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 303
```

Then I tried with a fresh DB and I got a different error.
```
Oops! That wasn't supposed to happen. The error was:
An error occurred while updating the entries. See the inner exception for details.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Attribute_dbo.EntityType_EntityTypeId". The conflict occurred in database "rock-develop", table "dbo.EntityType", column 'Id'.
The statement has been terminated. 
at System.Data.Entity.Internal.InternalContext.SaveChanges()
at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
at System.Data.Entity.DbContext.SaveChanges()
at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Users\Arran\Documents\GitHub\Spark\Rock\Rock\Data\DbContext.cs:line 145
at Rock.Data.DbContext.SaveChanges() in C:\Users\Arran\Documents\GitHub\Spark\Rock\Rock\Data\DbContext.cs:line 97
at Rock.Attribute.Helper.SaveAttributeEdits(Attribute newAttribute, Nullable`1 entityTypeId, String entityTypeQualifierColumn, String entityTypeQualifierValue, RockContext rockContext) in C:\Users\Arran\Documents\GitHub\Spark\Rock\Rock\Attribute\Helper.cs:line 732
at RockWeb.Blocks.Examples.SampleData.AddRegistrationTemplates(XElement elemRegistrationTemplates, RockContext rockContext) in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 827
at RockWeb.Blocks.Examples.SampleData.<>c__DisplayClass5.<ProcessXml>b__4() in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 544
at Rock.Data.DbContext.WrapTransaction(Action action) in C:\Users\Arran\Documents\GitHub\Spark\Rock\Rock\Data\DbContext.cs:line 75
at RockWeb.Blocks.Examples.SampleData.ProcessXml(String sampleXmlFile) in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 516
at RockWeb.Blocks.Examples.SampleData.bbtnLoadData_Click(Object sender, EventArgs e) in c:\Users\Arran\Documents\GitHub\Spark\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 303
```

**Comment by nairdo** [comment]
I just tried again to replicate this issue but I'm not able to.  The first one looks like it was complaining about the "registrationStarts" in the registrationInstance section of the http://storage.rockrms.com/sampledata/sampledata_1_5_0.xml -- which uses Lava to produce the date.  So this may be related to a lava issue.

**Comment by arranf** [comment]
I'll attempt to replicate it again. I could do consistently earlier but
I'll give it another shot .

**Comment by arranf** [comment]
@nairdo I can reproduce the second exception on my machine. VS2015, SSM14. Develop branch c837d6fbbc1e81a898878b9475f0f645b5fc4f5b with a fresh DB.

**Comment by nairdo** [comment]
Very odd, I checked out that branch and with a fresh DB cannot repro.  Can you track it down to see what the bug is?

**Comment by arranf** [comment]
@nairdo 

I _could_ reproduce the second exception but now I can't. It was to do with the fact Rock.Model.RegistrationRegistrant wasn't in the EntityType Table, hence the error about constraints. Line 780 
`  int? registrationRegistrantEntityTypeId = EntityTypeCache.Read( typeof( Rock.Model.RegistrationRegistrant ) ).Id;` produces a value of 293 wasn't matching any ID the table. I'm fairly certain this is something to do with my instance of SQL Server so we'll ignore that.

The DateTime exception I can't really pin down either. The String that's returned from the Lava to be parsed is 5/30/2016 12:00AM, and to me that looks valid!

**Comment by arranf** [comment]
Created a little test program

```
using System;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            string time = "5/30/2016";
            var newTime = DateTime.Parse(time);
            Console.WriteLine(newTime.ToString());
        }
    }
}
```
Parsing that string _does_ produce an exception reliably. Switch it over to 30/5/2016 and it works fine for me. Is this an localisation issue? Maybe it makes sense to switch the format to YYYY-MM-DD?

**Comment by nairdo** [comment]
@arranf thanks for catching that!  I just updated the .xml in the storage container to use the yyyy-M-dd format if you'd like to try it again now.

**Comment by azturner** [comment]
@nairdo , @arranf is this resolved?

**Comment by MinaMaher2** [comment]
Hi, Everyone

I came across the same issue now with Rock McKinley 8.4. I use d/M/yyyy date format, and I reproduced the error on the live demo as well. How can I get past that

**Comment by MinaMaher2** [comment]
@nairdo OK but, that's not the main problem the problem is when i try to download sample data into my web application running at my server it doesn't and give me the "String was not recognized as a valid DateTime." Exception so how to fix that?
Thank you.
