### ISSUE TITLE
Group Finder Filter for DateRange Error

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1561]
Hi

I added a DateRange attribute to the group type and on the Group Finder when i select to filter by this it throws the following error

NullReferenceException in App_Web_izalie4n

Message
Object reference not set to an instance of an object.
Stack Trace
   at RockWeb.Blocks.Groups.GroupFinder.AddFilterControl(Control control, String name, String description) in f:\My Documents\My Development\Bitbucket\Rock4.6\RockWeb\Blocks\Groups\GroupFinder.ascx.cs:line 744
   at RockWeb.Blocks.Groups.GroupFinder.BuildDynamicControls() in f:\My Documents\My Development\Bitbucket\Rock4.6\RockWeb\Blocks\Groups\GroupFinder.ascx.cs:line 650
   at RockWeb.Blocks.Groups.GroupFinder.OnLoad(EventArgs e) in f:\My Documents\My Development\Bitbucket\Rock4.6\RockWeb\Blocks\Groups\GroupFinder.ascx.cs:line 212
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by azturner** [comment]
@dcagnetta, Some field types do not have the capability to render the controls needed to be used for filtering. The DataRange field type is one of these. We've updated this block so that it no longer gives the option of being able to select any of these types of attributes and added error-handling if one already had been selected previously.
