### ISSUE TITLE
Sample Data Exception

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1698]
# Context

On a fresh DB on 1.6 develop, importing sample data.
# Expected Behaviour

Sample data would be imported.
# Actual Behaviour

An exception was thrown.

```
The wait operation timed out 
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
at Rock.Attribute.Helper.LoadAttributes(IHasAttributes entity, RockContext rockContext) in C:\Users\arran\Documents\Projects\Rock\Rock\Attribute\Helper.cs:line 490
at Rock.Attribute.Helper.LoadAttributes(IHasAttributes entity) in C:\Users\arran\Documents\Projects\Rock\Rock\Attribute\Helper.cs:line 310
at Rock.ExtensionMethods.LoadAttributes(IHasAttributes entity) in C:\Users\arran\Documents\Projects\Rock\Rock\Utility\ExtensionMethods\AttributesExtensions.cs:line 35
at Rock.Model.GroupMemberService.GetInverseRelationship(GroupMember groupMember, Boolean createGroup) in C:\Users\arran\Documents\Projects\Rock\Rock\Model\GroupMemberService.Partial.cs:line 279
at RockWeb.Blocks.Examples.SampleData.AddRelationships(XElement elemRelationships, RockContext rockContext) in c:\Users\arran\Documents\Projects\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 1321
at RockWeb.Blocks.Examples.SampleData.<>c__DisplayClass5.<ProcessXml>b__4() in c:\Users\arran\Documents\Projects\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 523
at Rock.Data.DbContext.WrapTransaction(Action action) in C:\Users\arran\Documents\Projects\Rock\Rock\Data\DbContext.cs:line 75
at RockWeb.Blocks.Examples.SampleData.ProcessXml(String sampleXmlFile) in c:\Users\arran\Documents\Projects\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 516
at RockWeb.Blocks.Examples.SampleData.bbtnLoadData_Click(Object sender, EventArgs e) in c:\Users\arran\Documents\Projects\Rock\RockWeb\Blocks\Examples\SampleData.ascx.cs:line 303
```
# Steps to Reproduce
1. Fresh Database on 1.6.0 develop
2. Import Sample Data
3. Wait for the exception
# Environment and Diagnostics Information

[RockDiagnostics-DESKTOP-KQ6T3BL.txt](https://github.com/SparkDevNetwork/Rock/files/414396/RockDiagnostics-DESKTOP-KQ6T3BL.txt)
- **Rock Version**:Rock McKinley 5.2
- **Client Culture Settinng**: en-gb

**Comment by edmistj** [comment]
I'm not seeing this anymore. Closing it. Please re-open if it comes back.
