### ISSUE TITLE
Document Signature: Null reference during registration.

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#1722]
### Prerequisites
This is an issue in the develop branch. 

### Description

System.NullReferenceException	App_Web_0vqwxgbn	Object reference not set to an instance of an object.	
   at RockWeb.Blocks.Event.RegistrationEntry.LoadViewState(Object savedState) in c:\RockStaging\Blocks\Event\RegistrationEntry.ascx.cs:line 338
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Steps to Reproduce

1. Setup a registration without a Document Signature requirement
2. Try to register for the event.
3. Null Reference is thrown

**Expected behavior:** Registration should work.

**Actual behavior:** Null Reference is thrown

### Versions

* Latest develop branch.

**Comment by cbump** [comment]
This is fixed in the latest version of the block.  My environment was out of date. Closing the issue.
