### ISSUE TITLE
Plugin upgrade fails silently in v6

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1873]
### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When upgrading the Amazon S3 Storage Provider to 1.1 in the beta of Rock v6, the upgrade fails silently.

### Steps to Reproduce

1. Click update button on plugin in Rock Shop
2. Login with credentials, click update
3. Rock generates success confirmation message
<img width="833" alt="screen shot 2016-11-17 at 11 19 31 am" src="https://cloud.githubusercontent.com/assets/374209/20403976/cd42f594-acb7-11e6-86a4-4fa85d23c939.png">
4. Restart Rock (and IIS), plugin remains at prior version

**Expected behavior:** Plugin upgrades to 1.1

**Actual behavior:** Stays at 1.0 after restart.

### Versions

* **Rock Version:** Rock McKinley 6.0 (Beta from Update Server)
* **Client Culture Setting** en-US 
[RockDiagnostics.txt](https://github.com/SparkDevNetwork/Rock/files/598233/RockDiagnostics-GRANITE.1.txt)

**Comment by azturner** [comment]
@garrettjohnson Were there any exceptions in your exception log reported at the time you did the restart?

**Comment by garrettjohnson** [comment]
I missed it the first time, but it fires a System.Exception, Exception occurred when adding Plugin Entities to RockContext
```
   at Rock.Data.RockContext.OnModelCreating(DbModelBuilder modelBuilder)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModelBuilder()
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
   at System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
   at InteractivePreGeneratedViews.InteractiveViews.SetViewCacheFactory(DbContext context, DbMappingViewCacheFactory viewCacheFactory)
   at Rock.Data.RockInteractiveViews.SetViewFactory(String path)
   at RockWeb.Global.Application_Start(Object sender, EventArgs e)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.Web.HttpApplication.InvokeMethodWithAssert(MethodInfo method, Int32 paramCount, Object eventSource, EventArgs eventArgs)
   at System.Web.HttpApplication.ProcessSpecialRequest(HttpContext context, MethodInfo method, Int32 paramCount, Object eventSource, EventArgs eventArgs, HttpSessionState session)
   at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)

**Comment by garrettjohnson** [comment]
Had a phantom plugin version being reported from the Rock Shop. Fixed with an update to the shop by @azturner
