### ISSUE TITLE
Giving Page UI Confusion

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#3014]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
If the giving page has a long footer (and some sites do because of social media feeds, etc), and the user inputs their card info and clicks next, the page scrolls down and it's not clear what happened. 

The donor needs to scroll up to complete the transaction.

### Steps to Reproduce
![long-footer](https://user-images.githubusercontent.com/117657/40378671-dfd0931a-5db9-11e8-8652-176b051c535d.gif)

### Versions
* **Rock Version:** [1.7.3]

**Comment by tommyprater** [comment]
We face this issue as well. We have had a few people call in about not knowing they had to scroll up to finish their gift.

**Comment by JimMichael** [comment]
Add me to the list as well... at least a couple times a month someone claims they gave but it "never came out of my account" and when we research, we find there is no transaction and after the first few times it happened realized the person never clicked "Finish" because they didn't know they needed to scroll back up. Would be nice if there were some anchors on the form that it would return to as people move through the forms.

**Comment by ethan-sparkdevnetwork** [comment]
The issue was the page has logic to scroll to the bottom after clicking next. This is actually good behavior for the page unless here is content in the footer, then the page jumps down and the user doesn't see the form anymore. Changed the default behavior of the page to retain window position after a postback.

**Comment by ethan-sparkdevnetwork** [comment]
If the size difference between the entry form and the confirmation form is large enough due to styling and/or number of accounts then the scroll position is going to be the bottom of the page when it gets to the confirmation.
Changed the logic to set focus to the asp:panel that is being made visible after the button clicks.
Removed logic to set scroll position on the client.

Tested in Chrome and Edge and will be in 8.5.

For a quick fix on 8.0 - 8.4 we can force the page to scroll to the top. To do this edit the TransactionEntry.ascx.cs file (notepad is fine) to remove the "//" in front of "//setTimeout('window.scrollTo(0,0)',0);". Then in the TransactionEntry.ascx file delete the script block at the bottom "<script type="text/javascript">
            Sys.Application.add_load(function () {
                window.scrollTo = function (x, y) { return true; }
            });
        </script>"

**Comment by timlem** [comment]
@ethan-sparkdevnetwork I tried doing the temporary fix but I broke something. Can you help me trace what this error means: Error

c:\inetpub\wwwroot\Blocks\Finance\TransactionEntry.ascx.cs(1): error CS0116: A namespace cannot directly contain members such as fields or methods
   at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at Rock.Web.UI.RockPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.themes_landingpage_layouts_fullclassic_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\e22c2559\92c7e946\App_Web_wkugg2x0.6.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by ethan-sparkdevnetwork** [comment]
Hello,

That error means there is code inside of the namespace but outside of the class. See below:

namespace RockWeb.Blocks.Finance
{
// Here we have the block attributes for the class. There are a lot for the TransactionEntry block and each are contained in square brackets
// e.g. [DisplayName( "Transaction Entry" )]
// However there should be no methods or properties. Look for anything that is not in square brackets.
    public partial class TransactionEntry : Rock.Web.UI.RockBlock
    {
                …
    }
}

I made the changes in the attached files and ran a few tests. The block will go to the top after clicking the next/previous/finish buttons.

God Bless,

Ethan

**Comment by timlem** [comment]
This is still happening on our site and we are on v8.5
