### ISSUE TITLE
Deleting an Attribute from a Workflow causes Workflow to be inaccessible

### ISSUE THREAD

**Issue by nathanp** [SparkDevNetwork/Rock#3141]
### Description

- I had an existing workflow that had been functioning for months (Communications media request form).
- I added 2 new attributes and removed 1 existing workflow attribute.
- Now the workflow is inaccessible, cannot be edited, and cannot be duplicated.

### Steps to Reproduce

1. On the Workflow configuration screen, when I click "Edit", I get the following error:
```
Error
Object reference not set to an instance of an object.

   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.BuildActionControl(Control parentControl, Boolean setValues, WorkflowActionType actionType, Dictionary`2 attributes, Dictionary`2 activities, Nullable`1 activeWorkflowActionTypeGuid, Boolean showInvalid) in c:\inetpub\Rock\Blocks\WorkFlow\WorkflowTypeDetail.ascx.cs:line 1670
   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.BuildActivityControl(Control parentControl, Boolean setValues, WorkflowActivityType activityType, Dictionary`2 workflowAttributes, Nullable`1 activeActivityTypeGuid, Nullable`1 activeWorkflowActionTypeGuid, Boolean showInvalid) in c:\inetpub\Rock\Blocks\WorkFlow\WorkflowTypeDetail.ascx.cs:line 1618
   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.BuildControls(Boolean setValues, Nullable`1 activeActivityTypeGuid, Nullable`1 activeActionTypeGuid) in c:\inetpub\Rock\Blocks\WorkFlow\WorkflowTypeDetail.ascx.cs:line 1573
   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.ShowEditDetails(WorkflowType workflowType, RockContext rockContext) in c:\inetpub\Rock\Blocks\WorkFlow\WorkflowTypeDetail.ascx.cs:line 1429
   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.btnEdit_Click(Object sender, EventArgs e) in c:\inetpub\Rock\Blocks\WorkFlow\WorkflowTypeDetail.ascx.cs:line 270
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

2. And when a user tries to submit the form, the following error is returned:
```
 NullReferenceException in App_Web_ntmepl2u

Message
Object reference not set to an instance of an object.

Stack Trace

   at RockWeb.Blocks.WorkFlow.WorkflowEntry.BuildForm(Boolean setValues) in c:\inetpub\Rock\Blocks\WorkFlow\WorkflowEntry.ascx.cs:line 554
   at RockWeb.Blocks.WorkFlow.WorkflowEntry.OnLoad(EventArgs e) in c:\inetpub\Rock\Blocks\WorkFlow\WorkflowEntry.ascx.cs:line 179
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

I assume this means it's still trying to access that attribute, but I have not figured out how to fix this.

**Expected behavior:**

I can delete an attribute from a Workflow without it throwing errors.

**Actual behavior:**

Can no longer edit or use the workflow.

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;795994085990100">image.png</a>

**Comment by mikejed** [comment]
@nathanp can you share what types of attributes you added to the workflow, and what type of attribute you removed from it?

Thanks

**Comment by nathanp** [comment]
@mikejed I deleted two attributes, both were Time (start time and end time).
I added a DateTime attribute, clicked "Save", and that's when the error started.

**Comment by cabal95** [comment]
@nathanp Did the attribute you added have the same name and/or Key as one of the attributes you deleted? Could be an important difference.

**Comment by nathanp** [comment]
@cabal95 No the keys were unique.
I have since gone in and deleted the old and new attributes via SQL, but the error persists.
