### ISSUE TITLE
Error accessing Defined Types

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#3149]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
We are having trouble accessing "Defined Types" it started a couple days ago and it happening on both our Dev Server and Production Server.

We are running: 7.4 in both environments.

I was not able to reproduce the issue on the Demo Site.

I did not find any other issues reported. 

### Steps to Reproduce
1. Go to General Admin Tools
1. Click on General Settings
1. Click on Defined Types
1. Receiving Error Message

**Expected behavior:**

By clicking on Defined Types it should take you to /page/84

**Actual behavior:**

We are receiving the following Error Message: 

Exception Log:
NullReferenceException in Rock
Message
Object reference not set to an instance of an object.

Stack Trace

at Rock.Web.UI.Controls.HtmlField.FormatDataValue(Object dataValue, Boolean encode)
 at System.Web.UI.WebControls.BoundField.OnDataBindField(Object sender, EventArgs e)
 at System.Web.UI.Control.OnDataBinding(EventArgs e)
 at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
 at System.Web.UI.Control.DataBindChildren()
 at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
 at System.Web.UI.WebControls.GridView.CreateRow(Int32 rowIndex, Int32 dataSourceIndex, DataControlRowType rowType, DataControlRowState rowState, Boolean dataBind, Object dataItem, DataControlField[] fields, TableRowCollection rows, PagedDataSource pagedDataSource)
 at System.Web.UI.WebControls.GridView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding)
 at Rock.Web.UI.Controls.Grid.CreateChildControls(IEnumerable dataSource, Boolean dataBinding)
 at System.Web.UI.WebControls.CompositeDataBoundControl.PerformDataBinding(IEnumerable data)
 at System.Web.UI.WebControls.GridView.PerformDataBinding(IEnumerable data)
 at System.Web.UI.WebControls.DataBoundControl.OnDataSourceViewSelectCallback(IEnumerable data)
 at RockWeb.Blocks.Core.DefinedTypeList.gDefinedType_Bind() in c:\inetpub\wwwroot\Blocks\Core\DefinedTypeList.ascx.cs:line 291
 at RockWeb.Blocks.Core.DefinedTypeList.OnLoad(EventArgs e) in c:\inetpub\wwwroot\Blocks\Core\DefinedTypeList.ascx.cs:line 89
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Versions
* **Rock Version:** [7.4]
* **Client Culture Setting:** [en-US]

**Comment by jcjones37** [comment]
<img width="1138" alt="screen shot 2018-08-05 at 20 57 58" src="https://user-images.githubusercontent.com/41912840/43692085-49cc6b22-98f2-11e8-9c67-1cab471d3f16.png">

**Comment by jcjones37** [comment]
This is resolved. Mike Roth was able to help!
