### ISSUE TITLE
Connections Merge Template

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#3195]
### Description
The option for "merge records into merge template" does not work on our instance of Rock.  I am not able to recreate it on the demo site. It gives us an error.

### Steps to Reproduce
1. Go to Connections
1. Click on an opportunity
1. Click on Merge Records into merge template
1. See error

**Expected behavior:**

You should be redirected to the Merge Template block/page

**Actual behavior:**

We receive the following error:

Error

The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.
 at System.Data.Entity.Core.Objects.ObjectContext.get_Connection()
 at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
 at System.Data.Entity.Core.Objects.DataClasses.EntityReference`1.Load(MergeOption mergeOption)
 at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.DeferredLoad()
 at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.LoadProperty[TItem](TItem propertyValue, String relationshipName, String targetRoleName, Boolean mustBeNull, Object wrapperObject)
 at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.<>c__DisplayClass7`2.<GetInterceptorDelegate>b__2(TProxy proxy, TItem item)
 at System.Data.Entity.DynamicProxies.Campus_6999FA348B8E25A78360308A7D6FDB5B937F8E7CA64CB4C21B4FD8C98359610B.get_LeaderPersonAlias()
 at GetLeaderPersonAlias(Object )
 at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
 at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
 at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
 at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
 at Rock.ExtensionMethods.ToJson(Object obj)
 at EntityFramework.Utilities.EFDataReader`1.<>c__DisplayClass21_0`1.<MakeDelegate>b__0(T t)
 at EntityFramework.Utilities.EFDataReader`1.GetValue(Int32 ordinal)
 at System.Data.SqlClient.SqlBulkCopy.GetValueFromSourceRow(Int32 destRowIndex, Boolean& isSqlType, Boolean& isDataFeed, Boolean& isNull)
 at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
 at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
 at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
 at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
 at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
 at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
 at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
 at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
 at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
 at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
 at EntityFramework.Utilities.SqlQueryProvider.InsertItems[T](IEnumerable`1 items, String schema, String tableName, IList`1 properties, DbConnection storeConnection, Nullable`1 batchSize)
 at EntityFramework.Utilities.EFBatchOperation`2.InsertAll[TEntity](IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)
 at Rock.Data.RockContext.BulkInsert[T](IEnumerable`1 records, Boolean useSqlBulkCopy)
 at Rock.Web.UI.Controls.Grid.GetEntitySetFromGridSourceList()
 at Rock.Web.UI.Controls.Grid.GetEntitySetFromGrid(EventArgs e)
 at Rock.Web.UI.Controls.Grid.Actions_MergeTemplateClick(Object sender, EventArgs e)
 at Rock.Web.UI.Controls.GridActions._lbMergeTemplate_Click(Object sender, EventArgs e)
 at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
 at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Versions
* **Rock Version:** [Rock McKinley 7.4 (1.7.4.58)]
* **Client Culture Setting:** [en-US]

**Comment by mikejed** [comment]
Slightly different presentation, but same error is confirmed on Prealpha
