### ISSUE TITLE
FontAwesome No Worky

### ISSUE THREAD

**Issue by TylerTheHanson** [SparkDevNetwork/Rock#3202]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? Yep!
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting? Rock McKinley 7.4 (1.7.4.58)
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported? Yep!

### Description

Just trying to upgrade FontAwesome packages from FontAwesome 

### Steps to Reproduce

1. Go to Admin Tools -> CMS Configuration -> FontAwesome Settings
2. Upload the Zip of FontAwesome Version 5.1+
3. Click Update
4. See error:
"Error
Value cannot be null. Parameter name: value
   at System.String.StartsWith(String value)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.Utility.FontAwesomeHelper.ExtractFontAwesomePackage(Int32 binaryFileId)
   at RockWeb.Blocks.Cms.FontAwesomeSettings.btnInstallUpdate_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\Cms\FontAwesomeSettings.ascx.cs:line 101
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)"

**Expected behavior:**

A Success Message: "Font Awesome Pro Package updated."

**Actual behavior:**

"Error
Value cannot be null. Parameter name: value
   at System.String.StartsWith(String value)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.Utility.FontAwesomeHelper.ExtractFontAwesomePackage(Int32 binaryFileId)
   at RockWeb.Blocks.Cms.FontAwesomeSettings.btnInstallUpdate_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\Cms\FontAwesomeSettings.ascx.cs:line 101
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)"

### Versions

* **Rock Version:** Rock McKinley 7.4 (1.7.4.58)
* **Client Culture Setting:** [en-US]

<img width="1475" alt="faerror" src="https://user-images.githubusercontent.com/42622675/44489557-c98b0000-a629-11e8-85dd-d9419a843e4e.png">

**Comment by TylerTheHanson** [comment]
I'm quite certain it's the build layout of director files that FontAwesome has changed up in the last several versions.

**Comment by Tschrock** [comment]
You are correct, FontAwesome uses a different file format since v5.1. The helper class for this will need to be updated.

**Comment by JimMichael** [comment]
Can we get clarification on how this is _supposed_ to work? I was under the impression that you could never upgrade to a pro version > than the "base" version in core, which (understandably) doesn't get updated near as often as FA updates their stuff. Is that accurate, or _should_ we (ignoring the install bug for a moment) be able to upgrade to any pro version regardless of what base package is in core?

**Comment by edmistj** [comment]
You should be fine upgrading to a newer FA than what is in core (assuming in a future release FA doesn't break anything). 

I reached out to the FA guys and they said that the new zip format will be consistent going forward. We'll fix this to allow either zip file format.
