### ISSUE TITLE
MergeTemplate Exception when Group contains same Person more than once

### ISSUE THREAD

**Issue by stevelipinski** [SparkDevNetwork/Rock#3210]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Attempting to apply a Merge template to a Group that has a Person contained multiple times fires an Exception.  The following Exception captured from demo site:

```
InvalidOperationException in EntityFramework
Message
Attaching an entity of type 'Rock.Model.Person' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.

Stack Trace

   at System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   at System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   at System.Data.Entity.DbSet`1.Attach(TEntity entity)
   at RockWeb.Blocks.Core.MergeTemplateEntry.GetMergeObjectList(RockContext rockContext, Nullable`1 fetchCount) in c:\inetpub\wwwroot\Blocks\Core\MergeTemplateEntry.ascx.cs:line 373
   at RockWeb.Blocks.Core.MergeTemplateEntry.btnMerge_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\Core\MergeTemplateEntry.ascx.cs:line 162
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

### Steps to Reproduce

1. Go to Group Viewer, Add new Small Group
2. Add a Person as a Member.  Add same Person again as Leader
3. Attempt to apply the Samples/Group Roster Merge Template to the group.

**Expected behavior:**

Merge should succeed

**Actual behavior:**

Exception fired (see description above)

### Versions

* **Rock Version:** Rock McKinley 8.1 (1.8.1.29)
* **Client Culture Setting:** en-US

**Comment by debbiethurston** [comment]
I too have had this when I have a data view that pulls more than one group and the person is in multiple groups.  The specific problem is having a person in a serving group for week 1 and the same person serves again in week 3.  Merging the serving team for the month, the error appears.

**Comment by mikejed** [comment]
I can confirm (v9 prealpha) that using a merge template on a group where a person is added more than one time causes an IIS error as stated.

I cannot reproduce a person dataview throwing an error if it pulls in multiple groups, even when a person is a member of multiple groups. They still only show up in the data view once, and the merge succeeds. I might need some more information from @debbiethurston to reproduce that issue.

**Comment by debbiethurston** [comment]
![image](https://user-images.githubusercontent.com/31704449/44871206-27d66500-ac60-11e8-9524-b6bfd1361a7c.png)

Here is from the data grid.  There are two different groups, the person is serving in group one and group 2 and as you can see in the note, to keep from getting the error, we have noted what we have to do.  The data view is pulling by Group ID.  Cut of the headings...sorry.  The 3837 and 3839 are the group IDs and 1239 is the same person in two different groups.  We are attempting to merge the combined groups into one Word Merge document.

Here is the Exception Log:
InvalidOperationException in EntityFramework
Message
Attaching an entity of type 'Rock.Model.Person' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.

Stack Trace

   at System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   at System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   at System.Data.Entity.DbSet`1.Attach(TEntity entity)
   at RockWeb.Blocks.Core.MergeTemplateEntry.GetMergeObjectList(RockContext rockContext, Nullable`1 fetchCount)
   at RockWeb.Blocks.Core.MergeTemplateEntry.btnMerge_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by debbiethurston** [comment]
So sorry, I just reread this.  The Dataview is NOT giving the error...it is the merge using a dataview that pulls a person more than one time and the merge throws an error.

**Comment by drychlik76** [comment]
Thank you!
