### ISSUE TITLE
Exception when Adding New Family

### ISSUE THREAD

**Issue by andrewe24** [SparkDevNetwork/Rock#3240]
When I try to add a new person/family, I get the issue below.  This is a new installation of RockRMS updated to version 7.5.  I have deleted all files and reinstalled, and it is still happening.

Error

Unable to find an entry point named 'SetClrFeatureSwitchMap' in DLL 'SqlServerSpatial110.dll'.
 at Microsoft.SqlServer.Types.GLNativeMethods.SetClrFeatureSwitchMap(Int32 clrFeatureSwitchMap)
 at Microsoft.SqlServer.Types.SqlGeometry.IsValidExpensive()
 at Microsoft.SqlServer.Types.SqlGeometry.Construct(GeoData g, Int32 srid)
 at Microsoft.SqlServer.Types.SqlGeometry.GeometryFromText(OpenGisType type, SqlChars text, Int32 srid)
 at Microsoft.SqlServer.Types.SqlGeometry.Parse(SqlString s)
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[ ] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[ ] parameters, Object[ ] arguments)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[ ] parameters, CultureInfo culture)
 at System.Data.Entity.SqlServer.SqlSpatialServices.GeometryFromText(String wellKnownText)
 at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.InitializeSpatialTypeDefaultMap()
 at System.Lazy`1.CreateValue()
 at System.Lazy`1.LazyInitValue()
 at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.TryGetDefaultValue(PrimitiveType primitiveType, Object& defaultValue)
 at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.GetPropagatorResultForPrimitiveType(PrimitiveType primitiveType, PropagatorResult& result)
 at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.Visit(EdmMember node)
 at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.CreateEntitySetPlaceholder(EntitySet entitySet)
 at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.Visit(DbScanExpression node)
 at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.Visit(DbProjectExpression node)
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<ProduceDynamicCommands>d__a.MoveNext()
 at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateCommandOrderer..ctor(IEnumerable`1 commands, UpdateTranslator translator)
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ProduceCommands()
 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
 at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
 at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
 at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
 at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
 at System.Data.Entity.Internal.InternalContext.SaveChanges()
 at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)
 at Rock.Model.LocationService.Get(String street1, String street2, String city, String state, String postalCode, String country, Group group, Boolean verifyLocation)
 at RockWeb.Blocks.Crm.PersonDetail.AddGroup.btnNext_Click(Object sender, EventArgs e)
 at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
 at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by TheCoreyHall** [comment]
Im with BEMA and we have a client that has this error thrown any time an address is attempted to be saved. It just started happening last week. They are managed on Azure as well. Any news on this?

**Comment by TheCoreyHall** [comment]
Just want to leave this in case it helps. This issue started happening for a client last week after installing the software Veeam onto their server. Veeam installed Microsoft System CLR Types for SQL Server 2012 in its installation. We determined that this was causing the conflict with Rock, and uninstalling the software and its dependencies fixed this issue.

**Comment by nairdo** [comment]
Hi @andrewe24 I know this is an oldie, but we've been asking around in other circles (and behind the scenes with) to see if anyone else is still having this issue with this or the duplicate issue (https://github.com/SparkDevNetwork/Rock/issues/3713; CC: @austinspooner), but so far no one else has.  We're going to close this but if you (or anyone else) is able to reproduce it, this issue can be reopened.
