### ISSUE TITLE
Person attribute with "Enhance For Long Lists" set can't be added to a Data View

### ISSUE THREAD

**Issue by darringraham** [SparkDevNetwork/Rock#3318]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When you try to add a user-added Person Attribute based on a user-added Defined Type to a Data View, Rock throws the following error:

```
Error

Control 'ff_b9753e65243242eeace1e57550df0dbe_containerControl_Attribute_FCCLoc_62b0806019c04939be53339eee4bc789' referenced by the ControlToValidate property of 'ff_b9753e65243242eeace1e57550df0dbe_containerControl_Attribute_FCCLoc_62b0806019c04939be53339eee4bc789_rfv' cannot be validated.
   at System.Web.UI.WebControls.BaseValidator.CheckControlValidationProperty(String name, String propertyName)
   at System.Web.UI.WebControls.BaseValidator.ControlPropertiesValid()
   at System.Web.UI.WebControls.BaseValidator.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

![image](https://user-images.githubusercontent.com/38145549/46425918-3b129f80-c6fa-11e8-9d95-86f122021cc7.png)

### Steps to Reproduce
1. Go to **General Settings | Defined Types** and create a **Defined Type** like "DepartmentList" and set it's Category to **Person**, then click **Save**.
1. Add a couple of **Values** to the Defined Type, like "IT", "Worship"
1. Go to General Settings | Person Attributes and create a new Person Attribute like "Department"
1. Set its **Categories** setting to "Employment", **Field Type** to Defined Value, Defined Type to "DepartmentList", click **Allow Multiple Values** and **Enhance For Long Lists**, and click **Save**
1. Go to Data Views and create a new Data View. Give it a name and set **Applies To** to "Person", 
1. Click **Add Filter** and make sure **Filter Type** is "Person Fields"
1. From the dropdown, select the **Person Attribute** "Department"
1. Rock spins for a minute then gives the error (above)

**Expected behavior:**

You should be able to create a Data View that references a user-defined Person Attribute that is enhanced for long lists and based on a Defined Type.

**Actual behavior:**

Rock throws an error (above)

### Versions
* **Rock Version:** Rock McKinley 8.3 (1.8.3.36)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Fixed via 7a030603d28 (Fixes #3318).
