### ISSUE TITLE
"Failed to load viewstate" when examining footer in CMS

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#3354]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Error block appears when navigating to footer zone in CMS/Pages. (found on our church's Azure/RMS8.3 installation, verified on demo site)

### Steps to Reproduce
1. Go to AdminTools>CMS Configuration>Pages>Internal Homepage>Reporting>Data Views

http://rock.rocksolidchurchdemo.com/page/103?Page=145&ExpandedIds=12%2c105%2c144&Redirect=false

1. On "Main Zone" block, click on the box that says "Main (2)" on the right and change to "Footer (1)".
1. See error

**Expected behavior:**

There should be no error box.

**Actual behavior:**

Failed to load viewstate. The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request. For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.
 at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
 at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
 at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
 at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.AddedControl(Control control, Int32 index)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.AddAdminControls(BlockCache block, Panel pnlLayoutItem)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.rptBlocks_ItemDataBound(Object sender, RepeaterItemEventArgs e)
 at System.Web.UI.WebControls.Repeater.OnItemDataBound(RepeaterItemEventArgs e)
 at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
 at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
 at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
 at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.ShowDetailForZone(String zoneName)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.OnLoad(EventArgs e)
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Versions
* **Rock Version:** [Rock Version: Rock McKinley 8.3 (1.8.3.36)]
* **Client Culture Setting:** [Client Culture Setting: en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=891198972741853">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=891198972741855">image.png</a>

**Comment by nairdo** [comment]
We have not been able to reproduce this using the steps provided.  Please feel free to re-open this if you have another reliable way of re-creating this issue.

**Comment by MicahO** [comment]
Thanks for re-opening. Here's a better description of the bug, for those interested.

https://www.youtube.com/watch?v=TuwLjysNq48

**Comment by MicahO** [comment]
@nairdo @RileyGspark This bug appears to be fixed in 11.1; do you want to mark it as fixed and closed?

**Comment by nairdo** [comment]
@MicahO Sure will!  Thanks for testing and letting us know.
