### ISSUE TITLE
Archived Groups Crash Person's Group History

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#3392]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

1. Find a small group and note the name of one person in the group.
2. Archive the group.
3. Go to the person's profile and click the "Groups" tab.
4. Find the group on the timeline. Click the group.

**Expected behavior:**

I don't know the expected behavior. Maybe a note that says "This group has been archived and cannot be viewed at this time. To un-archive the group, contact your database administrator." Or maybe you actually do want the person to be able to view the group.

**Actual behavior:**

```
NullReferenceException in mscorlib
Message
Object reference not set to an instance of an object.

Stack Trace

   at System.Object.GetType()
   at Rock.Web.UI.Controls.FollowingsHelper.SetFollowing(IEntity followEntity, WebControl followControl, Person follower)
   at RockWeb.Blocks.Groups.GroupDetail.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

```

### Versions

* **Rock Version:** [v8.x (verified on Rock Demo (v8.4) and our church's site (v8.3).]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/a20bb726d3d31d227eafc3ee41c664168fd85f90#diff-4c074351206de65666821726933c7b7eR39
