### ISSUE TITLE
Error while trying to change schedule on group with group history enabled

### ISSUE THREAD

**Issue by jrockman13** [SparkDevNetwork/Rock#3450]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
Background: I'm trying to troubleshoot an issue where there seems to be a "ghost" schedule. We have a small group that uses Check-in on Sunday AM. It's set to use service schedule, but oddly, two attendance occurances are created. I fixed it on one group a while back by deleting the schedule in the group viewer and then setting it on a schedule in the Check-in Config.

I was trying to do that today with another one of the groups and get this error:

`DbUpdateException in EntityFramework
Message
An error occurred while updating the entries. See the inner exception for details.
Stack Trace
at System.Data.Entity.Internal.InternalContext.SaveChanges()
at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)
at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationTypeDetail.<>c__DisplayClass10.<btnSave_Click>b__9() in c:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationTypeDetail.ascx.cs:line 354
at Rock.Data.DbContext.WrapTransaction(Action action)
at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationTypeDetail.btnSave_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationTypeDetail.ascx.cs:line 352
at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
-UpdateException in EntityFramework
Message
An error occurred while updating the entries. See the inner exception for details.
Stack Trace
at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
at System.Data.Entity.Internal.InternalContext.SaveChanges()
--SqlException in .Net SqlClient Data Provider
Message
The DELETE statement conflicted with the REFERENCE constraint "FK__com_centralaz_RoomManagement_ReservationWorkflow_ReservationWorkflowTriggerId". The conflict occurred in database "cbc-rock-db", table "dbo._com_centralaz_RoomManagement_ReservationWorkflow", column 'ReservationWorkflowTriggerId'. The statement has been terminated.
Stack Trace
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
`

### Steps to Reproduce
1. Go into one of the adult groups
1. Click "Edit"
1. Remove the current schedule/location
1. Try to save.

**Expected behavior:**

Save works and the group would have NO schedule.

**Actual behavior:**

I get the above error message

### Versions
* **Rock Version:** 8.4
* **Client Culture Setting:** en-us

**Comment by CompassSkelly** [comment]
Testing on devbox running v8.9: I was able to reproduce this issue

Testing on the same group on demo and Prealpha: I get the expected behavior of "Save works and the group would have NO schedule."

**Comment by chead4** [comment]
@jrockman13 We are unable to recreate this issue.  Please add more screenshots so that we can understand exactly how you configured the group.
