### ISSUE TITLE
ArgumentException when query string matches route parameter

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3557]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
When the key for a query string parameter is the same as a route parameter in a url, Rock throws an ArgumentException:

     ArgumentException in mscorlib: An item with the same key has already been added.
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Rock.Web.UI.RockPage.PageParameters() in C:\Users\jay\Desktop\Rock2\Rock\Web\UI\RockPage.cs:line 2563
       at Rock.Lava.LavaHelper.GetCommonMergeFields(RockPage rockPage, Person currentPerson, CommonMergeFieldsOptions options) in C:\Users\jay\Desktop\Rock2\Rock\Lava\LavaHelper.cs:line 120
       at RockWeb.Blocks.Cms.HtmlContentDetail.ShowView() in c:\inetpub\wwwroot\Blocks\Cms\HtmlContentDetail.ascx.cs:line 682
       at RockWeb.Blocks.Cms.HtmlContentDetail.OnLoad(EventArgs e) in c:\inetpub\wwwroot\Blocks\Cms\HtmlContentDetail.ascx.cs:line 123
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)### Steps to Reproduce
1. Go to [https://www.rocksolidchurchdemo.com/Page/1?PageId=1](https://www.rocksolidchurchdemo.com/Page/1?PageId=1) or [https://www.rocksolidchurchdemo.com/WorkflowEntry/16?WorkflowTypeId=16](https://www.rocksolidchurchdemo.com/WorkflowEntry/16?WorkflowTypeId=16)

**Expected behavior:**

The page loads.

**Actual behavior:**

The page throws an error.

### Versions
* **Rock Version:** v1.8.6.2, pre-alpha (1.9.0.14)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Greetings, we did some recent work to reproduce this and discovered it was corrected in 12.1 via https://github.com/SparkDevNetwork/Rock/commit/627924a215df37e23540d8c49bd3679f9220bfc7 but we failed to connect it back to this issue during the commit.
