### ISSUE TITLE
Process BI Analytics - Job Not Running

### ISSUE THREAD

**Issue by lizrose20** [SparkDevNetwork/Rock#3748]
### Description
The Process BI Analytics job has failed since May 24th.  We were able to get all but the Process Person BI Analytics pieces of the job to run.   If we run just that the Process Person BI Analytics it also fails.

We updated to Rock 8.8 yesterday on our dev site.  I was able to duplicate the error there as well.

### Steps to Reproduce
1. Go to 'Jobs Administration'
1. Click on 'Run - Process BI Analytics'
1. Mark all processes as Yes.
1. Save
1. Run Job
1. See error

**Expected behavior:**

Job runs without failure.

Job Failed - Error Message 
The conversion of a date data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

### Versions
* **Rock Version:** [Rock McKinley 8.7 (1.8.7.6)]
* **Client Culture Setting:** [en-US]

**Comment by randyjreed** [comment]
This is happening on our system also.

**Comment by nairdo** [comment]
@randyjreed (or @lizrose20 ) ~Are you getting any other exceptions in your Exception Log?~  ~If so can you attach the details here because~ the stack trace could be really helpful for us to figure out what's going wrong ~(since we've not been abler to reproduce it)~.

I was able to find another system the same problem and am attaching the stack Exception log details for our reference:

`The conversion of a date data type to a datetime data type resulted in an out-of-range value. The statement has been terminated.[: Line 6, : Line 6]`

```
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Rock.Data.DbService.ExecuteCommand(String query, CommandType commandType, Dictionary`2 parameters, Nullable`1 commandTimeout)
   at Rock.Jobs.ProcessBIAnalytics.DoPersonMainPopulateETLs(List`1 analyticsSourcePersonHistoricalFields, List`1 personAnalyticAttributes)
   at Rock.Jobs.ProcessBIAnalytics.ProcessPersonBIAnalytics(IJobExecutionContext context, JobDataMap dataMap)
   at Rock.Jobs.ProcessBIAnalytics.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run()
```

**Comment by nairdo** [comment]
We believe we've found the cause (bad date from data in the Person's BirthDay, BirthMonth, BirthYear columns) and recent v9 fix (https://github.com/SparkDevNetwork/Rock/commit/c009bd9d5762f20776fcb3bbe91930e267be8f41) in addition to the fact that in v9 the BirthDate column is being changed to a real date column.  

Can you verify that this query is **_not_** fails when you run it?

```Sql
SELECT COUNT(1) FROM [Person] WHERE 1 IN ( SELECT dbo.ufnCrm_GetAge(p.BirthDate) [Age] FROM [Person] p )
```

If that fails, you can proceed with this next stuff...

1. If you want to try to find the bad data (so you can correct it manually), using SQL Server Management Studio, run this query and the last person it shows should be right before the problem record:

```Sql
 SELECT [Id], dbo.ufnCrm_GetAge(p.BirthDate) [Age] FROM [Person] p ORDER BY [Id]
```

2. Once you find the range, you should be able to quickly spot the bad date with something like this example from my system:

```Sql
-- In my case it failed right at the 166153 record...
 SELECT [Id], BirthYear, BirthMonth, BirthDay, BirthDate FROM [Person] p WHERE [Id] between 166153 and 166160
```

![image](https://user-images.githubusercontent.com/383807/59526545-03194a00-8e8e-11e9-854c-29c4a73e83b6.png)

3. Fix bad data.

You may need to repeat these steps if you have more than one bad record.

**Comment by randyjreed** [comment]
@nairdo That was it. The job now runs without error. I identified two bad records. One person was over 1000 years old... Thanks for your efforts.

**Comment by lizrose20** [comment]
@nairdo Sorry for the late reply, I was unexpectedly off for a few days.  Back at it this morning, and while I actually got a timeout running the above, I did run a quick report for anyone with a birth year less than 1900 and was able to find 2 bad records.  Once I cleaned those up, everything ran just fine.

Thank you so much for finding this!
