### ISSUE TITLE
Registration Template fee displaying validation error.

### ISSUE THREAD

**Issue by aaronjones8** [SparkDevNetwork/Rock#3807]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?

    [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    

    [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a registration has fee that is required with the option of multiple options with quantity, a validation error occurs when choosing a quantity in 1 of the options
### Steps to Reproduce

1. Create a registration with a template that has a required fee with multiple options and quantities
2. Go to the registration and attempt to complete the registration.
3. Place 1 in the registration quantity and press next
4. Receive error message

**Expected behavior:**

Once you have entered a positive quantity for fee, registration should proceed when next button is pressed

**Actual behavior:**

Validation error is displayed

### Versions

Rock Version: Rock McKinley 8.8 (1.8.8.3)
    Client Culture Setting: en-US
![registration](https://user-images.githubusercontent.com/13666106/61411016-6a725180-a8b3-11e9-83e2-4f8395d1db9b.png)

**Comment by Tschrock** [comment]
Confirmed on the pre-alpha server (The validation error shows up no matter how much I put for the quantity)

In addition to the validation error, trying to go to the previous page and then forward again with a 0 for all quantities results in the following exception:
```
System.ArgumentNullException    System.Core    Value cannot be null. Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rock.Model.RegistrationTemplateFee.GetFeeMultipleOptionMultipleQuantityControl(Boolean setValues, List`1 feeValues, RegistrationInstance registrationInstance, List`1 otherRegistrants) in C:\Source\Repos\Rock\Rock\Model\RegistrationTemplateFee.cs:line 348
   at Rock.Model.RegistrationTemplateFee.AddFeeControl(PlaceHolder phFees, RegistrationInstance registrationInstance, Boolean setValues, List`1 feeValues, List`1 otherRegistrants) in C:\Source\Repos\Rock\Rock\Model\RegistrationTemplateFee.cs:line 452
   at RockWeb.Blocks.Event.RegistrationEntry.CreateRegistrantControls(Boolean setValues) in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 4508
   at RockWeb.Blocks.Event.RegistrationEntry.CreateDynamicControls(Boolean setValues) in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 4363
   at RockWeb.Blocks.Event.RegistrationEntry.SetPanel(PanelIndex currentPanelIndex) in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 4052
   at RockWeb.Blocks.Event.RegistrationEntry.ShowRegistrant() in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 3871
   at RockWeb.Blocks.Event.RegistrationEntry.ShowRegistrant(Boolean forward, Boolean increment) in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 3686
   at RockWeb.Blocks.Event.RegistrationEntry.btnRegistrationAttributesStartNext_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 997
   at RockWeb.Blocks.Event.RegistrationEntry.ShowRegistrationAttributesStart(Boolean forward) in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 906
   at RockWeb.Blocks.Event.RegistrationEntry.lbHowManyNext_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 863
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```
