### ISSUE TITLE
Server Error with MigrateScheduledTransactionNotesToHistory.sql and ValueAsNumeric - Upgrade To V9 Beta

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#3812]
### Description
I got the eureka page after updating the v9 beta. I hit restart and I got the RTE page. I adjust the `web.config` to show the error and got this:

```
Line 636:
Line 637:                    // NOTE: we need to specify the last migration vs null so it won't detect/complain about pending changes
Line 638:                    migratorLoggingDecorator.Update( lastMigration );
Line 639:                    result = true;
Line 640:                }

Source File: c:\inetpub\wwwroot\App_Code\Global.asax.cs Line: 638
```

At the bottom of the `App_Data\RockExceptions.csv` log was the following:
```
7/19/2019 12:08:55 PM,System.ComponentModel.Win32Exception,"The wait operation timed out",""
7/19/2019 12:08:55 PM,System.Exception,"Error occurred during application startup","   at RockWeb.Global.Application_Start(Object sender, EventArgs e) in c:\inetpub\wwwroot\App_Code\Global.asax.cs:line 350"
7/19/2019 12:08:55 PM,System.Data.SqlClient.SqlException,"Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.","   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at RockWeb.Global.MigrateDatabase(RockContext rockContext) in c:\inetpub\wwwroot\App_Code\Global.asax.cs:line 638
   at RockWeb.Global.Application_Start(Object sender, EventArgs e) in c:\inetpub\wwwroot\App_Code\Global.asax.cs:line 179"
7/19/2019 12:08:55 PM,System.ComponentModel.Win32Exception,"The wait operation timed out",""
```

### Steps to Reproduce
I went from 8.8 to v9.

**Expected behavior:**

Rock to work

**Actual behavior:**

Rock does not work

### Versions
* **Rock Version:** [v9 beta]
* **Client Culture Setting:** [en-US]

**Comment by tstephens17** [comment]
Every time I try to go to our Rock site, the Azure SQL jumps to 70% and stays there until the wait operation times out.

**Comment by tstephens17** [comment]
@nairdo I rant he query.
201903202256547_EFMigrationCleanUp

I am now going to up the DTUs and see if I can get past it.

**Comment by nairdo** [comment]
(For others watching outside our #beta-testers channel...)

It appears the migration it's stuck on is the "ScheduledTransactionHistory" migration, and in there, it's probably/possibly timing out running this part:

```Sql

DECLARE @historyCategoryId INT = (
		SELECT TOP 1 Id
		FROM Category
		WHERE Guid = '477EE3BE-C68F-48BD-B218-FAFC99AF56B3'
		)
	,@entityTypeIdScheduledTransaction INT = (
		SELECT TOP 1 Id
		FROM EntityType
		WHERE [Guid] = '76824E8A-CCC4-4085-84D9-8AF8C0807E20'
		)
	,@noteTypeIdScheduledTransaction INT = (
		SELECT TOP 1 Id
		FROM NoteType
		WHERE [Guid] = '360CFFE2-7FE3-4B0B-85A7-BFDACC9AF588'
		)

BEGIN
	-- convert 'Created Transaction' notes into History if they aren't aleady in History
	INSERT INTO [History] (
		IsSystem
		,CategoryId
		,EntityTypeId
		,EntityId
		,[Guid]
		,CreatedDateTime
		,ModifiedDateTime
		,CreatedByPersonAliasId
		,ModifiedByPersonAliasId
		,[Verb]
		,[ChangeType]
		,[ValueName]
		)
	SELECT n.IsSystem
		,@historyCategoryId [CategoryId]
		,@entityTypeIdScheduledTransaction [EntityTypeId]
		,n.EntityId
		,newid() [Guid]
		,n.CreatedDateTime
		,n.ModifiedDateTime
		,n.CreatedByPersonAliasId
		,n.ModifiedByPersonAliasId
		,'ADD' [Verb]
		,'Record' [ChangeType]
		,'Transaction' [ValueName]
	FROM [Note] n
	WHERE NoteTypeId = @noteTypeIdScheduledTransaction
		AND [Caption] = 'Created Transaction'
		AND EntityId NOT IN (
			SELECT EntityId
			FROM [History]
			WHERE EntityTypeId = @entityTypeIdScheduledTransaction
				AND [Verb] = 'ADD'
			)

	-- convert 'Updated Transaction','Cancelled Transaction','Reactivated Transaction' notes into History if they aren't aleady in History
	INSERT INTO [History] (
		IsSystem
		,CategoryId
		,EntityTypeId
		,EntityId
		,[Summary]
		,[Guid]
		,CreatedDateTime
		,ModifiedDateTime
		,CreatedByPersonAliasId
		,ModifiedByPersonAliasId
		,[Verb]
		,[ChangeType]
		,[ValueName]
		,[NewValue]
		)
	SELECT n.IsSystem
		,@historyCategoryId [CategoryId]
		,@entityTypeIdScheduledTransaction [EntityTypeId]
		,n.EntityId
		,n.Caption [Summary]
		,newid() [Guid]
		,n.CreatedDateTime
		,n.ModifiedDateTime
		,n.CreatedByPersonAliasId
		,n.ModifiedByPersonAliasId
		,'MODIFY' [Verb]
		,'Property' [ChangeType]
		,CASE n.Caption
			WHEN 'Cancelled Transaction'
				THEN 'Is Active'
			WHEN 'Reactivated Transaction'
				THEN 'Is Active'
			ELSE 'Transaction'
			END [ValueName]
		,CASE n.Caption
			WHEN 'Cancelled Transaction'
				THEN 'False'
			WHEN 'Reactivated Transaction'
				THEN 'True'
			ELSE ''
			END [NewValue]
	FROM [Note] n
	WHERE NoteTypeId = @noteTypeIdScheduledTransaction
		AND [Caption] IN (
			'Updated Transaction'
			,'Cancelled Transaction'
			,'Reactivated Transaction'
			)
		AND EntityId NOT IN (
			SELECT EntityId
			FROM [History]
			WHERE EntityTypeId = @entityTypeIdScheduledTransaction
				AND [Verb] = 'MODIFY'
			)
	ORDER BY [Caption]

	DELETE FROM [Note] WHERE NoteTypeId = @noteTypeIdScheduledTransaction
		AND [Caption] IN (
			'Created Transaction'
			,'Updated Transaction'
			,'Cancelled Transaction'
			,'Reactivated Transaction'
			)
END
```

**Comment by tstephens17** [comment]
Bumping up to an S7 (800 DTUs) got me past this error and another came up.


Line 149:                { 
Line 150:                    // Get the values 
Line 151:                    var values = definedType.DefinedValues.OrderBy( v => v.Order ).ToList(); 
Line 152: 
Line 153:                    // Find all the unselected values
--
Source File: c:\inetpub\wwwroot\Blocks\Utility\DefinedTypeCheckList.ascx.cs    Line: 151

**Comment by nairdo** [comment]
After the completion of all the data migrations to get you to v9, there is a [currently a job called PostV90DataMigrationsValueAsNumeric](https://github.com/SparkDevNetwork/Rock/blob/release-1.9.0/Rock/Jobs/PostV90DataMigrationsValueAsNumeric.cs#L61) that Rock runs to perform some conversion of the `AttributeValue` table's `ValueAsNumeric` column.  We're investigating what might have gone wrong and will provide a fix for the remaining beta users if needed.

**Comment by tstephens17** [comment]
I am no longer seeing this error after trying to connect again.

**Comment by nairdo** [comment]
Great news.  Let's leave this issue open until our team has a chance to examine and harden some of the migration code, etc.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/sparkdevnetwork/rock/commit/3cae8cfbece1e3baa0619cc6bdefc05e23144cb7

and
https://github.com/sparkdevnetwork/rock/commit/e2e9fe5be660bff1b0b16e5511189b4fea81ffef
