### ISSUE TITLE
Process BI Analytics throws exceptions when a person's birth year is < 1753

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3899]
### Description
When a person's birth year is set to a really low value due to a data entry error, the Process Bi Analytics job throws an exception:

    System.Data.SqlClient.SqlException 	.Net SqlClient Data Provider 	The conversion of a date data type to a datetime data type resulted in an out-of-range value. The statement has been terminated.[: Line 5, : Line 5]
    
       at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
       at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
       at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
       at Rock.Data.DbService.ExecuteCommand(String query, CommandType commandType, Dictionary`2 parameters, Nullable`1 commandTimeout) in C:\Source\Repos\Rock\Rock\Data\DbService.cs:line 216
       at Rock.Jobs.ProcessBIAnalytics.DoPersonMainPopulateETLs(List`1 analyticsSourcePersonHistoricalFields, List`1 personAnalyticAttributes) in C:\Source\Repos\Rock\Rock\Jobs\ProcessBIAnalytics.cs:line 755
       at Rock.Jobs.ProcessBIAnalytics.ProcessPersonBIAnalytics(IJobExecutionContext context, JobDataMap dataMap) in C:\Source\Repos\Rock\Rock\Jobs\ProcessBIAnalytics.cs:line 523
       at Rock.Jobs.ProcessBIAnalytics.Execute(IJobExecutionContext context) in C:\Source\Repos\Rock\Rock\Jobs\ProcessBIAnalytics.cs:line 106
       at Quartz.Core.JobRunShell.Run()### Steps to Reproduce
1. Use sql or other means to change a person's birthdate to have a year before 1753
1. Run the 'Process Bi Analytics' job

**Expected behavior:**

The job runs successfully

**Actual behavior:**

The job throws an exception

### Versions
* **Rock Version:** 8.8, pre-alpha (1.10.0.6)
* **Client Culture Setting:** en-US

**Comment by afewkes** [comment]
Confirmed this is still in issue on the demo server (1.9.1.3) and the prealpha server (1.11.0.2).
You cannot enter a birth year prior to 1900 on the internal site, but you can thru family preregistration and check in registration.  
Changing the calendar dimensions did not fix the problem.

**Comment by nairdo** [comment]
As Jesse mentioned, this is actually the same underlying problem as reported via #3881 so I'm going to close this one as a duplicate. ( We'll be working on that issue.)
