### ISSUE TITLE
Error when editing registration instance without cost

### ISSUE THREAD

**Issue by craigmash** [SparkDevNetwork/Rock#3918]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When editing an existing registration instance that has no cost associated, you get the following error...
Error
The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.
   at System.Data.Entity.Core.Objects.ObjectContext.get_Connection()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.DataClasses.EntityCollection`1.Load(List`1 collection, MergeOption mergeOption)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.DeferredLoad()
   at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.LoadProperty[TItem](TItem propertyValue, String relationshipName, String targetRoleName, Boolean mustBeNull, Object wrapperObject)
   at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.<>c__DisplayClass7`2.<GetInterceptorDelegate>b__1(TProxy proxy, TItem item)
   at System.Data.Entity.DynamicProxies.RegistrationTemplate_682327402E051E03803CB5EF02C393FF54DAF03C93CE1C7286BF536CCEAB21E8.get_Fees()
   at RockWeb.Blocks.Event.RegistrationInstanceDetail.btnSave_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

If you add a cost to the template, error does not happen. Similar to https://github.com/SparkDevNetwork/Rock/issues/3888 but this seems to happen only in 9.2. Was not happening in 9.0 or 9.1.

### Steps to Reproduce

Got to existing registration instance without cost and edit it.
Click the SAVE button and error will appear.

**Expected behavior:**

Save with no error

**Actual behavior:**

The changes will save, but with the error.

### Versions

* **Rock Version:** [ Rock McKinley 9.2 (1.9.2.3)]
* **Client Culture Setting:** [ en-US]

**Comment by ethan-sparkdevnetwork** [comment]
This issue was fixed in 9.3 in commit: 3b0db8bbb4ed6ea38272b174e9a368ea8943dd06
