### ISSUE TITLE
Connection Request Transfer Exception Thrown When There are No Other Connection Opportunities of that Opportunity Type

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#4011]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:

### Description

Clicking transfer on a Connection Request when the Connection Opportunity Type has only one Connection Opportunity throws an exception

### Steps to Reproduce

1. Create a Connection Opportunity Type
2. Only Create One Connection Opportunity
3. Create a Request for that opportunity
4. Click Transfer
5. See Error

**Expected behavior:**

I would expect the Transfer button to either hide or disable when there are no other connection opportunities to transfer the request to.

**Actual behavior:**

Error is Thrown 
Object reference not set to an instance of an object.
   at RockWeb.Blocks.Connection.ConnectionRequestDetail.ddlTransferOpportunity_SelectedIndexChanged(Object sender, EventArgs e)
   at RockWeb.Blocks.Connection.ConnectionRequestDetail.lbTransfer_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Versions

Rock Version: Rock McKinley 9.4 (1.9.4.1)
Client Culture Setting: en-US

**Comment by MichaelAllen** [comment]
Looks like this has been fixed in v11: https://github.com/SparkDevNetwork/Rock/issues/3963
