### ISSUE TITLE
v10 update fails when [location] for campus [does NOT] exist

### ISSUE THREAD

**Issue by NonDeterministicStateMachine** [SparkDevNetwork/Rock#4056]
### Description

Updating to Rock v10 fails when multiple campuses are present or when the campus has a `NULL` location.

### Steps to Reproduce

1. Deploy an instance of Rock RMS to v9.4
2. Create a new location
3. Create a new campus
4. Update to v10
5. Restart Rock

**Expected behavior:** 

The update would be successful.

**Actual behavior:** 

The application fails to start up due to an application initialization error. The reported error in the logs is a `System.Data.SqlClient.SqlException`:

```c#
Cannot insert the value NULL into column 'LocationId', table 'RockChMS.dbo.GroupLocation'; column does not allow nulls. INSERT fails.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at RockWeb.Global.MigrateDatabase(RockContext rockContext)
   at RockWeb.Global.Application_Start(Object sender, EventArgs e)
```

Specifically, the error appears to originate from the [201908141043495_AddWeekendServicesCheckin](https://github.com/SparkDevNetwork/Rock/blob/1.10.0/Rock.Migrations/Migrations/Version%2010.0/Version%201.10.0/201908141043495_AddWeekendServicesCheckin.cs) migration. The following SQL is present (formatted for readability):

```sql
--Add Weekend Service Group Locations
DECLARE @GroupId INT = ( SELECT [Id] FROM [Group] WHERE [Guid] = 'E000800B-B358-416F-BCD5-90C4CAC65AA3' );
IF @GroupId IS NOT NULL
BEGIN
    INSERT INTO [GroupLocation] ( [LocationId], [GroupId], [IsMailingLocation], [IsMappedLocation], [Guid] )
        SELECT [LocationId], @GroupId, 0, 0, NEWID()
            FROM [Campus] 
            WHERE [IsActive] = 1
            GROUP BY [LocationId]
            ORDER BY MAX( [Name] )
END
```

The nested `SELECT` statement seems to be intended to only return a single campus. However, if multiple campuses are present, the `[LocationId]` will be translated to `NULL`, causing the migration to fail. Additionally if the first campus does not have a location, `[LocationId]` will also be `NULL`. To better protect against these cases, the migration SQL may need to be modified into something more like the following:

```sql
--Add Weekend Service Group Locations
DECLARE @GroupId INT = ( SELECT [Id] FROM [Group] WHERE [Guid] = 'E000800B-B358-416F-BCD5-90C4CAC65AA3' );
IF @GroupId IS NOT NULL
BEGIN
    INSERT INTO [GroupLocation] ( [LocationId], [GroupId], [IsMailingLocation], [IsMappedLocation], [Guid] )
        SELECT TOP ( 1 ) [LocationId], @GroupId, 0, 0, NEWID()
            FROM [Campus] 
            WHERE [IsActive] = 1
                AND [LocationId] IS NOT NULL
            GROUP BY [LocationId]
            ORDER BY MAX( [Name] )
END
```

However, this example still does not handle the case where there is a single campus without a location. Since this migration was introduced in 1.10.0 and migrations exist for 1.10.1, this would most likely be a breaking change.

### Versions

* **Rock Version:** Rock McKinley 9.3 (1.9.3), Rock McKinley 9.4 (1.9.4)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
We haven't done the final update on production yet, but on our dev testing of alpha and beta we didn't run into any issues and we have 5 campuses, so it might be something besides _just_ the multiple campus thing.

**Comment by JimMichael** [comment]
I concur with Daniel. I've test upgraded a copy of our production DB multiple times without issue, and we have five campuses... so perhaps the issue has something to do with a mis-configuration of campuses prior to upgrade.

**Comment by ethan-sparkdevnetwork** [comment]
This is due one or more rows campuses with a NULL LocationId. This state is not allowed by the Rock UI but it is LocationId is not a required field on the Campus table.

**Comment by ethan-sparkdevnetwork** [comment]
@NonDeterministicStateMachine You can complete the upgrade by updating the Campus table with a valid LocationId. You can run the query below and then update the campus with the correct location after the upgrade and Rock is up and running. Alternatively you can update Campus with the correct LocationId in SQL.

```
DECLARE @locationId INT = ( SELECT TOP(1) [Id] FROM [Location] WHERE [IsActive] = 1 ORDER BY [ID] )

IF(@locationId IS NOT NULL)
BEGIN UPDATE [Campus] SET [LocationId] = @locationId WHERE [LocationId] IS NULL END
```

**Comment by nairdo** [comment]
@NonDeterministicStateMachine Please let us know if you're unable to repair the campus-location data in your server.  A campus should always be connected to a location (Rock's campus detail block also requires a campus to have a location.)
