### ISSUE TITLE
Can't remove Workflow Type from Connection Type

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#4068]
### Description
Looks like Issue  #1488 might be back. Trying to remove a Workflow type from a Connection Type when a workflow has been started from a connection request results in an error:

`The DELETE statement conflicted with the REFERENCE constraint "FK_dbo.ConnectionRequestWorkflow_dbo.ConnectionWorkflow_ConnectionWorkflowId"`

### Steps to Reproduce
1. Add a Workflow Trigger to a Connection Type
1. Trigger the workflow from a Connection Request of the same type
1. Edit the Connection Type
1. Delete the Workflow Type from the list
1. Click Save
1. Notice that nothing seems to happen
1. Scroll to the top to see the error

**Expected behavior:**

The changes to the Connection Type should be saved, including the removal of the Workflow Type, and I should be redirected to the Connection Type Detail page.

**Actual behavior:**

Nothing is saved, no redirect happens and an exception is thrown.

### Versions
* **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** en-US

**Comment by JRichmond27** [comment]
Just came across the same issue with Connection Activity Types.

**Comment by JRichmond27** [comment]
Same issue happens when a workflow is triggered from a connection request, and then the workflow tries to delete itself.

**Steps to Reproduce**
1. Create a workflow with a user entry form with a cancel button that triggers a "Workflow Delete" action
2. Add a Workflow Trigger to a Connection Type
3. Trigger the workflow from a Connection Request of the same type

Here's the error:
`The DELETE statement conflicted with the REFERENCE constraint "FK_dbo.ConnectionRequestWorkflow_dbo.Workflow_WorkflowId"`

**Comment by jayoma** [comment]
> Same issue happens when a workflow is triggered from a connection request, and then the workflow tries to delete itself.

@JRichmond27 , thank you for pointing this out. We will be addressing both issues mentioned here in our fix.

**Comment by jasonhendee** [comment]
> Same issue happens when a workflow is triggered from a connection request, and then the workflow tries to delete itself.

@JRichmond27 , thank you for pointing this out. We will be addressing both issues mentioned here in our fix.

**Comment by TheArkChurch** [comment]
Just tried this on my system and I still get errors when trying to delete a workflow that was\is tied to a connection type and has had workflow run.

`   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)
   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.btnDelete_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

Thats the exception error that I'm getting

**Comment by nairdo** [comment]
@TheArkChurch We're going to review this one to see what else might be happening.  Would you be willing to use the "export" feature to export your workflow (and DM/Chat it to me) just in case there is something special in there that we didn't account for?
