### ISSUE TITLE
Exception when sending SMS from Communication Entry block if "Enable Lava" is set to No

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#4175]
### Description
When trying to send a message from the simple communication page (Communication Entry block) I am getting a `System.ArgumentNullException` if I set the "Enable Lava" option to "No". Here is the full stack trace:

```
System.ArgumentNullException | Value cannot be null. Parameter name: input
at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at Rock.ExtensionMethods.SanitizeLava(String lava)
   at RockWeb.Blocks.Communication.CommunicationEntry.UpdateCommunication(RockContext rockContext)
   at RockWeb.Blocks.Communication.CommunicationEntry.btnSubmit_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

I did not want to put my Twilio API credentials on the demo server to test, but I was able to reproduce this on a fresh install of 10.2. Also Brianne Shaw was seeing the same issue in RocketChat today (https://chat.rockrms.com/channel/communications?msg=9rHmt5P8KhXnp3SKo https://chat.rockrms.com/channel/communications?msg=hT4r3xZaiWa4GiiYY)

Changing "Enable Lave" to "Yes" fixes the issue. Also, enabling the email medium fixes the issue, even though we are only sending a SMS message.

### Steps to Reproduce
1. Edit the block settings on the Communication Entry block (Not the wizard).
  * Set "Enable Lava" to "No"
  * Only enable the SMS medium
1. Compose a message
1. Press send

**Expected behavior:**

Message is sent.

**Actual behavior:**

Message does not send, and a `System.ArgumentNullException` occurs.

### Versions
* **Rock Version:** 1.10.2.3
* **Client Culture Setting:** en-US

**Comment by MichaelAllen** [comment]
Stepping through this in VS, the exception is originating from this line: https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.3/RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs#L1499
It appears that `communication.FromEmail` and `communication.FromName` are both set to null if the Email medium isn't enabled, and the `SanatizeLava()` method does not like null values.

**Comment by MichaelAllen** [comment]
The easy fix for this block is to add a null-coalesce to these 2 lines https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.3/RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs#L1301 and https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.3/RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs#L1308

But it is worth considering if `SanatizeLava()` should be modified to return an empty string if given null, rather than throwing an exception.
