### ISSUE TITLE
Communications to large number of recipients fails with "query processor ran out of resources"

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4194]
### Description
When creating a communication to a large number of recipients, in our case 55,000, the communication fails to save due to a "Query processor ran out of internal resources" error. The exception happens on this line:

https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.2/RockWeb/Blocks/Communication/CommunicationEntryWizard.ascx.cs#L2534

And appears to be caused by a large `IN` clause. The query in question results in where clause like:

```SQL
WHERE x IN (1, 2, 3, 4, 5, ..., 54998, 54999, 55000)
```

which is doomed to fail. See screenshots and full stack trace below.

![](https://user-images.githubusercontent.com/1119863/79782066-4edd2100-82f3-11ea-91b9-532db918ffbd.png)

Full Stack Trace:

    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
       at System.Data.SqlClient.SqlDataReader.get_MetaData()
       at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
       at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
       at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
       at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
       at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
       at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
       at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
       at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
       at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
       at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
       at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
       at RockWeb.Blocks.Communication.CommunicationEntryWizard.UpdateCommunication(RockContext rockContext) in c:\inetpub\wwwroot\rock\Blocks\Communication\CommunicationEntryWizard.ascx.cs:line 2534
       at RockWeb.Blocks.Communication.CommunicationEntryWizard.SendTestCommunication(Int32 mediumEntityTypeId, NotificationBox nbResult) in c:\inetpub\wwwroot\rock\Blocks\Communication\CommunicationEntryWizard.ascx.cs:line 1502
       at RockWeb.Blocks.Communication.CommunicationEntryWizard.btnEmailSendTest_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\rock\Blocks\Communication\CommunicationEntryWizard.ascx.cs:line 1482
       at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
       at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
       at RockWeb.Global.Application_Error(Object sender, EventArgs e)### Steps to Reproduce
1. Go to a Data View with 55,000 people in it.
1. Click on the communicate button.
1. Step through various screens until you reach the main editor.
1. Click Send Test or Save
1. See error.

**Expected behavior:**

The communication should be saved.

**Actual behavior:**

It isn't and you get an error instead.

### Potential solution.
One potential solution would be to break that query into smaller chunks of 250 or maybe 1,000 recipients at a time. Something like:

```
// Add any new recipients
HashSet<int> communicationPersonIdHash = new HashSet<int>( qryRecipients.Select( a => a.PersonAlias.PersonId ) );
var tempRecipientPersonIds = recipientPersonIds.ToList();
// Cheat to create an anonymous dictionary we can add to.
var recipientPersonsLookup = Enumerable.Range( 0, 0 )
    .ToDictionary( a => a, a => new { CommunicationPreference = CommunicationType.Email, PrimaryAlias = new PersonAlias() } );
while ( tempRecipientPersonIds.Any() )
{
    var personIdsChunk = tempRecipientPersonIds.Take( 1000 ).ToList();
    tempRecipientPersonIds = tempRecipientPersonIds.Skip( 1000 ).ToList();
    new PersonService( rockContext ).Queryable()
        .Where( a => personIdsChunk.Contains( a.Id ) ).Select( a => new
        {
            PersonId = a.Id,
            a.CommunicationPreference,
            PrimaryAlias = a.Aliases.Where( x => x.AliasPersonId == x.PersonId ).Select( pa => pa ).FirstOrDefault()
        } )
        .ToList()
        .ForEach( a =>
        {
            recipientPersonsLookup.AddOrReplace( a.PersonId, new { a.CommunicationPreference, a.PrimaryAlias } );
        } );
}
```

We will be testing the above code later this afternoon and I will report back if it works correctly.

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
The above query is in place on our production server and seems to work. It's slow - though I don't think that is due to the change above directly. I think it's just slow because it's working with 55,000 recipients.

At that count, clicking "Save" took 60+ seconds before finishing. But it did at least work.

Hopefully we can find a way to speed that up, but maybe we can/should also add in some SignalR code for live progress feedback or something when dealing with communications > 1,000 recipients.

**Comment by JimMichael** [comment]
I can confirm that sending email to a very large number of recipients is broken here, as well.  I tried creating a communication from a DV of 81k people and I could not save it or send a test. I got a different error than Daniel (`the wait operation timed out`) but the result is the same... I couldn't send such a large email if I needed/wanted to.

**Comment by nairdo** [comment]
When I was at CentralAZ, we found the practical limit was somewhere around the 50-60k number.  Anything much higher and you would likely encounter problems.  For now, as a workaround, I'd suggest splitting it up into two different communications.

**Comment by cabal95** [comment]
Just saw that this was previously reported as #4041, so I'm going to close this one.

**Comment by zackdutra** [comment]
It looks like this has been partially resolved, but the issue still occurs when sending a communication from a data view. https://github.com/SparkDevNetwork/Rock/commit/d1187bf45c3e8e26ec72131d06212954e8b549be
