### ISSUE TITLE
[Alpha] NRE in CacheManager that seems to kill Rock until restarted

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4267]
### Description
I don't know if this is v11 related or not. And I don't know what I'm doing that is triggering this. But it has happened to me 3 different times on Alpha so far today. I am having unrelated performance issues on the server, so it's possible those performance issues are in turn causing this NRE. But either way, I there is apparently not a null check somewhere that there should be.

I'm assuming the reason for the null value is related to a SQL connection ussue. These traces are from the RockExceptions.csv as they are not being recorded in the ExceptionLog table.

NOTICE: I'm primarily logging this bug about the lack of a null check somewhere. I'm fairly certain I have unrelated server issues causing the core problem for why it's null to begin with.

### Stack traces
```text
6/25/2020 1:36:20 PM,System.NullReferenceException,"Object reference not set to an instance of an object.","   at CacheManager.Core.Internal.CacheStats`1.<GetWorkingCounters>d__21.MoveNext()
   at CacheManager.Core.Internal.CacheStats`1.OnGet(String region)
   at CacheManager.Core.BaseCacheManager`1.GetCacheItemInternal(String key, String region)
   at CacheManager.Core.Internal.BaseCache`1.Get(String key)
   at Rock.Web.Cache.ItemCache`1.GetOrAddExisting(String key, Func`1 itemFactory)
   at RockWeb.Global.GetKeepAliveUrl()
   at RockWeb.Global.CacheItemRemoved(String k, Object v, CacheItemRemovedReason r)"
```

```text
6/25/2020 1:34:42 PM,System.NullReferenceException,"Object reference not set to an instance of an object.","   at CacheManager.Core.Internal.CacheStats`1.<GetWorkingCounters>d__21.MoveNext()
   at CacheManager.Core.Internal.CacheStats`1.OnGet(String region)
   at CacheManager.Core.BaseCacheManager`1.GetCacheItemInternal(String key, String region)
   at CacheManager.Core.Internal.BaseCache`1.Get(String key)
   at Rock.Web.Cache.ItemCache`1.GetOrAddExisting(String key, Func`1 itemFactory)
   at Rock.Web.Cache.ItemCache`1.GetOrAddExisting(Int32 key, Func`1 itemFactory)
   at Rock.Web.Cache.EntityCache`2.Get(Int32 id, RockContext rockContext)
   at RockWeb.Blocks.Administration.ScheduledJobList.gScheduledJobs_RowDataBound(Object sender, GridViewRowEventArgs e)
   at System.Web.UI.WebControls.GridView.OnRowDataBound(GridViewRowEventArgs e)
   at Rock.Web.UI.Controls.Grid.OnRowDataBound(GridViewRowEventArgs e)
   at System.Web.UI.WebControls.GridView.CreateRow(Int32 rowIndex, Int32 dataSourceIndex, DataControlRowType rowType, DataControlRowState rowState, Boolean dataBind, Object dataItem, DataControlField[] fields, TableRowCollection rows, PagedDataSource pagedDataSource)
   at System.Web.UI.WebControls.GridView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding)
   at Rock.Web.UI.Controls.Grid.CreateChildControls(IEnumerable dataSource, Boolean dataBinding)
   at System.Web.UI.WebControls.CompositeDataBoundControl.PerformDataBinding(IEnumerable data)
   at System.Web.UI.WebControls.GridView.PerformDataBinding(IEnumerable data)
   at System.Web.UI.WebControls.DataBoundControl.OnDataSourceViewSelectCallback(IEnumerable data)
   at RockWeb.Blocks.Administration.ScheduledJobList.BindGrid()
   at RockWeb.Blocks.Administration.ScheduledJobList.gScheduledJobs_RunNow(Object sender, RowEventArgs e)
   at Rock.Web.UI.Controls.EditField.OnClick(RowEventArgs e)
   at Rock.Web.UI.Controls.EditFieldTemplate.lbEdit_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)"
```

### Steps to Reproduce
1. Unknown.

### Versions
* **Rock Version:** v11 alpha
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Okay, so the initial trigger for this seems to be the "Fix Combined Givers" (plugin) job. It's an old job that is somehow no longer compatible with v11, but seems to trigger this state where Rock becomes completely inaccessible until you restart the App Pool as accessing any page results in the previously reported exception.

**Comment by nairdo** [comment]
UPDATE: We are investigating this and believe we're close to uncovering the problem (and a probable solution).
