### ISSUE TITLE
Rock Update Exception 

### ISSUE THREAD

**Issue by eford2345** [SparkDevNetwork/Rock#4371]
### Description

We are running into a bug that does not allow us to update our Rock instance. The update block appears to be having an issue on our end. 

### Steps to Reproduce

1. Go to Admin Tools - General Settings
2. Click on Rock Update

**Expected behavior:**

Load Rock Update block. 

**Actual behavior:**

After clicking on the Rock Update button an exception appears: 

ArgumentException in App_Web_wud13jvn
Message
There is a malformed 'requires-' tag in a Rock package (1.1.0) 

### Versions

* **Rock Version:** 13.3

----------------------------------------------------------------------

Full exception:   

 at RockWeb.Blocks.Core.RockUpdate.ExtractRequiredVersionFromTags(IPackage package)
   at RockWeb.Blocks.Core.RockUpdate.rptPackageVersions_ItemDataBound(Object sender, RepeaterItemEventArgs e)
   at System.Web.UI.WebControls.Repeater.OnItemDataBound(RepeaterItemEventArgs e)
   at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
   at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
   at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
   at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
   at RockWeb.Blocks.Core.RockUpdate.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by nairdo** [comment]
@eford2345 Here are the things to double check on your system:

1. What version of Rock are you currently running? __________
2. What items are in your `RockWeb\Packages\` folder?  If you were running Rock v11, you should have `Rock.1.11.0.nupkg`, `RockUpdate-1-11-0.1.11.0.nupkg`, followed by a whole bunch of other RockUpdate-1-X-Y.1.x.y.nupkg items as shown here:
![image](https://user-images.githubusercontent.com/383807/91109244-42652e00-e62f-11ea-849f-00e20c78047b.png)
3. What URL is your `Update Server URL` global attribute configured to use?
![image](https://user-images.githubusercontent.com/383807/91109308-69bbfb00-e62f-11ea-851f-3e0e25ebfeb5.png)

If either of the #2 and #3 is incorrect, it will lead to problems similar to what you've described.

**Comment by eford2345** [comment]
Good deal. Thanks for that information, Nick!

1.) We are running Rock McKinley 10.3 (1.10.3.7) currently.
2.) Here is a look at our Packages folder:

<img width="574" alt="Screen Shot 2020-08-26 at 11 41 24 AM" src="https://user-images.githubusercontent.com/62080073/91332326-a1db4f00-e791-11ea-8196-89b220b7ac48.png">

3.) This is our update server URL: http://update.rockrms.com/F/rockbeta/api/v2/

**Comment by eford2345** [comment]
> Good deal. Thanks for that information, Nick!
> 
> 1.) We are running Rock McKinley 10.3 (1.10.3.7) currently.
> 2.) Here is a look at our Packages folder:
> 
> <img alt="Screen Shot 2020-08-26 at 11 41 24 AM" width="574" src="https://user-images.githubusercontent.com/62080073/91332326-a1db4f00-e791-11ea-8196-89b220b7ac48.png">
> 
> 3.) This is our update server URL: http://update.rockrms.com/F/rockbeta/api/v2/

**Comment by nairdo** [comment]
@eford2345 Ok -- so if that screenshot is complete, you're missing the `Rock.1.10.3.nupkg`.  That probably means the update to v10.3 failed in some fashion.

**Comment by eford2345** [comment]
Yes, it appears I am missing Rock.1.10.3.nupkg.

**Comment by eford2345** [comment]
What is the best course of action at this point?

**Comment by nairdo** [comment]
In that case, we generally recommend someone restore back to their current state and re-try the upgrade. (That can be very difficult if a significant amount of time has passed -- since your database is likely to have changes you don't want to loose. In such case, I'd recommend you reach out to a partner to get additional assistance.)

**Comment by eford2345** [comment]
Great. Thanks!
