### ISSUE TITLE
Groups not added/detached correctly with multiple Group Placement Tabs

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#4383]
On behalf of Faithbridge Church.

### Description
When using multiple group placement tabs on a registration, the Add Group options add the groups such that all tabs contain all groups.  So if you have a Bus tab and a Cabin tab, both tabs show all buses and all cabins.

In addition, if trying to detach a group added through the Add Groups button, all groups are removed and not just the one requested (I suspect this might be a result of how they are being added so it may be the same issue creating both).

### Steps to Reproduce
1. Go to rocksolidchurchdemo.com Summer Camp registration [event registration template] .
1. Under Placement Configuration, add two placement configurations - one for Buses and one for Cabins with a group type of Small Group.
1. Go to the the Summer Camp 2016 registration instance.
1. Click on the Buses tab.
1. Click on Add Groups.
1. Click on Add Multiple Groups (same issue with Add Existing Group as well).
1. Select Section A as the parent group and click Save.
1. Click on the Cabins tab.
1.  All of the groups were added to both tabs.

I believe this is incorrect!  The purpose of multiple tabs is to have separate sets of groups people are assigned to on each tab.

1. Pick the top group (Decker Group) by clicking the three dots and select Detach.
1. Refresh the screen.
1. All groups have been removed, not just the Decker Group.

I believe this should only detach one of the groups.

**Expected behavior:**

I would expect that adding groups would only add them to the currently active tab.  I would expect that detaching one group would only affect that group.

**Actual behavior:**

Adding groups through the instance adds them to all tabs.  Detaching one group detaches them all.

### Versions
* **Rock Version:** v10.3 and verified on v11 on rocksolidchurchdemo.com and on prealpha.
* **Client Culture Setting:** Azure

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199586758880741">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199586758880750">image.png</a>

**Comment by karenn-ccbc** [comment]
I am seeing this same issue with detaching a single group when multiple groups were added still not working in 11.3 and also when adding in multiple groups, it is adding inactive groups in the tree as well. I would like to see it only adding in the active groups or having an option of whether or not to add in inactive groups.

**Comment by karenn-ccbc** [comment]
we have a beta instance on 12.3 and I am still seeing this behavior. It allows you to detach a group, but then trying to add a person to a remaining group, you get an error. It also still adds inactive groups when adding multiple groups.
![image](https://user-images.githubusercontent.com/35667472/122080775-2a2fec80-cdc4-11eb-8f2b-aa3daf727169.png)

**Comment by karenn-ccbc** [comment]
Just confirmed this in Rock Demo

**Comment by ethan-sparkdevnetwork** [comment]
Fix for multiple group selection including inactive groups: https://github.com/sparkdevnetwork/rock/commit/7cd45f3d02d310d577649132d8912ce942da545e

Fix for detaching a single group also removing all instance placement groups: https://github.com/sparkdevnetwork/rock/commit/9161ce80e6925638bd5f8928bdc73545472f922d

These will be included in version 12.5.

**Comment by karenn-ccbc** [comment]
I commented on RocketChat https://chat.rockrms.com/channel/events-registrations?msg=SQePsdhoH3tRriqkE  and not sure if this is related, but we updated from 12.2 to 12.5 last evening and our groups that were on a placement tab before update have disappeared today. It appears that they are there, but hidden in that only the people not in groups are showing to be placed, and when we try to re add the groups we get an error message about "Cannot insert duplicate key row..."

**Comment by karenn-ccbc** [comment]
Error

Cannot insert duplicate key row in object 'dbo.RelatedEntity' with unique index 'IX_SourceEntityTypeId_SourceEntityId_TargetEntityTypeId_TargetEntityId_PurposeKey'. The duplicate key value is (260, 989, 16, 477962, PLACEMENT). The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Source\Repos\Rock12\Rock\Data\DbContext.cs:line 196
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Source\Repos\Rock12\Rock\Data\DbContext.cs:line 157
   at RockWeb.Blocks.Event.RegistrationInstanceGroupPlacement.mdAddPlacementGroup_SaveClick(Object sender, EventArgs e)
   at Rock.Web.UI.Controls.ModalDialog.SaveLink_ServerClick(Object sender, EventArgs e) in C:\Source\Repos\Rock12\Rock\Web\UI\Controls\ModalDialog.cs:line 575
   at System.Web.UI.HtmlControls.HtmlAnchor.OnServerClick(EventArgs e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by karenn-ccbc** [comment]
We determined that the Qualifier Value is missing and adding that back in brought the groups back.
![image](https://user-images.githubusercontent.com/35667472/133346186-fcfee03e-a621-44cf-ba3a-80c1ed1a1186.png)
I will be opening a new issue tomorrow-- in case this is not related.
