### ISSUE TITLE
Entity Property Set workflow action doesn't work with Group Member entity

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#4407]
### Description
When using the Entity Property Set workflow action to attempt to set a property on a Group Member entity it throws a `System.InvalidOperationException`.

    Member 'OriginalValues' cannot be called for the entity of type 'GroupMember' because the entity does not exist in the context. To add an entity to the context call the Add or Attach method of DbSet<GroupMember>.
    
    at System.Data.Entity.Internal.InternalEntityEntry.ValidateNotDetachedAndInitializeRelatedEnd(String method)
       at System.Data.Entity.Internal.InternalEntityEntry.ValidateStateToGetValues(String method, EntityState invalidState)
       at System.Data.Entity.Internal.InternalEntityEntry.get_OriginalValues()
       at Rock.Model.GroupMember.IsNewOrChangedGroupMember(RockContext rockContext)
       at Rock.Model.GroupMember.ValidateGroupMemberDuplicateMember(RockContext rockContext, GroupTypeCache groupType, String& errorMessage)
       at Rock.Model.GroupMember.ValidateGroupMembership(RockContext rockContext, String& errorMessage)
       at Rock.Model.GroupMember.IsValidGroupMember(RockContext rockContext)
       at Rock.Model.GroupMember.get_IsValid()
       at Rock.Workflow.Action.SetEntityProperty.Execute(RockContext rockContext, WorkflowAction action, Object entity, List`1& errorMessages)
       at Rock.Model.WorkflowAction.Process(RockContext rockContext, Object entity, List`1& errorMessages)
       at Rock.Model.WorkflowActivity.Process(RockContext rockContext, Object entity, List`1& errorMessages)
       at Rock.Model.Workflow.ProcessActivity(RockContext rockContext, DateTime processStartTime, Object entity, List`1& errorMessages)
       at Rock.Model.Workflow.ProcessActivities(RockContext rockContext, Object entity, List`1& errorMessages)
       at Rock.Model.WorkflowService.Process(Workflow workflow, Object entity, List`1& errorMessages)
       at RockWeb.Blocks.WorkFlow.WorkflowEntry.HydrateObjects()
       at RockWeb.Blocks.WorkFlow.WorkflowEntry.OnLoad(EventArgs e)
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Control.LoadRecursive()
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)### Steps to Reproduce
1. Create a new workflow
1. Add an Entity Property Set action with the following settings:
  * **Entity Type**: Group Member
  * **Entity Id or Guid**: 82 (Ted Decker in the Usher group)
  * **Property Name**: Note
  * **Property Value**: Testing
  * **Empty Value Handling**: Ignore
1. Attempt to execute the workflow

**Expected behavior:**

The property is updated to the provided value.

**Actual behavior:**

A `System.InvalidOperationException` is thrown, and the value is not updated.

### Versions
* **Rock Version:** 1.11.0.3
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
We recently uncovered this too and I was wondering if someone else was going to encounter it before we got the fix in.

**Comment by EthanW96** [comment]
I just came across this issue in v1.10.3.7 as well.
