### ISSUE TITLE
Rapid Attendance Entry - null reference exception when not taking attendance

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#4498]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The rapid attendance entry block has a setting to disable its attendance functions and use it solely as a contact item entry. However, it appears that the block is checking for attendance settings even if attendance is disabled. This is causing the block not to load correctly since user hasn't selected a group / schedule / date.

### Steps to Reproduce
1. Visit the rapid attendance page
2. Edit the block settings and disable attendance
3. Save and refresh

**Expected behavior:**

I should still be able to enter contact items when attendance is disabled.

**Actual behavior:**

Null reference exception:
```
at RockWeb.Blocks.CheckIn.RapidAttendanceEntry.IsAttendanceSettingValid() in C:\inetpub\wwwroot\Blocks\CheckIn\RapidAttendanceEntry.ascx.cs:line 1624
at RockWeb.Blocks.CheckIn.RapidAttendanceEntry.ShowDetails() in C:\inetpub\wwwroot\Blocks\CheckIn\RapidAttendanceEntry.ascx.cs:line 1604
at RockWeb.Blocks.CheckIn.RapidAttendanceEntry.Page_Load(Object sender, EventArgs e) in C:\inetpub\wwwroot\Blocks\CheckIn\RapidAttendanceEntry.ascx.cs:line 460
at System.Web.UI.Control.OnLoad(EventArgs e)
at Rock.Web.UI.RockBlock.OnLoad(EventArgs e) in C:\Source\Repos\Rock\Rock\Web\UI\RockBlock.cs:line 594
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

### Versions

* **Rock Version:** 1.11.2.1 and prealpha (1.12.0.9)
* **Client Culture Setting:** en-US

**Comment by MichaelAllen** [comment]
(I'm working on a fix for this, just wanted to document it here in case anyone else runs into the same issue in the meantime)

**Comment by matthewbronkema** [comment]
Fixed with https://github.com/SparkDevNetwork/Rock/commit/4fa3815e1c38574e3d46b12af895bbba5c698988
