### ISSUE TITLE
Registration Entry Block no longer fails gracefully if no Registration Instance is supplied or the one supplied is no longer active

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#4538]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The registration entry block does not fail gracefully when a registration instance is not passed or when the registration period has ended.

### Steps to Reproduce

1. Go to `https://prealpha.rocksolidchurchdemo.com/registration`
2. See the null reference exception.
3. Go to 'https://prealpha.rocksolidchurchdemo.com/registration?RegistrationInstanceId=2'
4. See the registration form
5. Change the registration end date to the past and visit 'https://prealpha.rocksolidchurchdemo.com/registration?RegistrationInstanceId=2'
6. See the null reference exception.

**Expected behavior:**

I expect to see the standard this registration was not found or the registration period has ended message.

**Actual behavior:**

A null reference exception is thrown
NullReferenceException in App_Web_rtdomcka
Message
Object reference not set to an instance of an object.

Stack Trace

   at RockWeb.Blocks.Event.RegistrationEntry.RegisterClientScript() in C:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 4504
   at RockWeb.Blocks.Event.RegistrationEntry.OnInit(EventArgs e) in C:\inetpub\wwwroot\Blocks\Event\RegistrationEntry.ascx.cs:line 707
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at Rock.Web.UI.RockBlockWrapper.CreateChildControls() in C:\Source\Repos\Rock\Rock\Web\UI\RockBlockWrapper.cs:line 71
   at System.Web.UI.Control.EnsureChildControls()
   at Rock.Web.UI.RockPage.OnInit(EventArgs e) in C:\Source\Repos\Rock\Rock\Web\UI\RockPage.cs:line 1310
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean 

<img width="539" alt="Screen Shot 2021-01-06 at 12 19 53 PM" src="https://user-images.githubusercontent.com/24379548/103800200-1795d800-501a-11eb-84cf-7bc0a8b3753e.png">

### Versions
Rock Version: 

* **Rock Version:** Rock McKinley 12.0 (1.12.0.10), Conifrmed on Prealpha v1.13
* **Client Culture Setting:** en-US

**Comment by randyjreed** [comment]
I am also on v12.0 and this is confirmed.

**Comment by JRichmond27** [comment]
This bug is not limited to v12. We're on v11.4 and experiencing the same issue.
