### ISSUE TITLE
An exception is thrown if an Event Registration Template Fee Name is >100 characters & <201 characters

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#4641]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The _Event Registration Template Fee_ functionality throws an exception if the fee's name is greater than 100 characters and less than 201 characters

### Steps to Reproduce

1. Create an Event Registration Template
2. Add a _Fee_ to the template
3. For the name of the fee, input 101 characters (or any value above 100)
4. Save the fee
5. Select the 'Save' button to save the template

#### Expected behavior:
I think that there are _two_ improvements to make. The first one shouldn't be difficult, but the second may be trickier (I don't know):
* Rock should allow saving fee names up to 200 characters, as the SQL Column is `nvchar(200)`
* If the fee name is greater than the allowed length, Rock should gracefully tell the user and guide them to make the appropriate adjustment to the field that isn't appropriate

##### Error Message Displayed:
Rock displays a message on the screen (above the template area, which usually the user doesn't see. The save button just seems to not work, unless the user has a very high resolution/high DPI display or scrolls to the top of the page
![image](https://user-images.githubusercontent.com/8688424/112896187-b3783280-90a3-11eb-89fc-39dd45224608.png)

##### An exception is logged in Rock
Summary
  Exception Date
  3/29/2021 2:10 PM
  Description
  Entity Validation Error:
  RegistrationTemplate_A171619831ECD291F09016133067771EB419CCBE5A333AE397ED12B5F5ED2406 (Name): The field Name must be a string or array type with a maximum length of '100'.;RegistrationTemplate_3497201647DFE9B4F54AFE757F9E8656224EBFC311258360107399B1FBC93CBA (Name):
  The field Name must be a string or array type with a maximum length of '100'.
  Site
  Rock RMS
  Page
  Event Registration
  Query String
  RegistrationTemplateId: 194
  User: Shawn Ross
![image](https://user-images.githubusercontent.com/8688424/112898098-07841680-90a6-11eb-9fe1-c8abb0b54648.png)

**System.SystemException Stack Trace:**
```
    at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Projects\Rock\Rock\Data\DbContext.cs:line 214at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Projects\Rock\Rock\Data\DbContext.cs:line 157
    at RockWeb.Blocks.Event.RegistrationTemplateDetail.btnSave_Click(Object sender, EventArgs e)
    at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
    at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

### Versions

* **Rock Version:** 11.3, 12.2
* **Client Culture Setting:** en-US

**Comment by smross** [comment]
To be clear, the SQL table _should_ allow up to 200 characters. But it appears the C# code does not (I got that tip from @cabal95 )
https://github.com/SparkDevNetwork/Rock/blob/702d063ba019948ece1037ac591d4ada7995e2b0/Rock/Model/RegistrationTemplate.cs#L52

**Comment by smross** [comment]
> To be clear, the SQL table _should_ allow up to 200 characters. But it appears the C# code does not (I got that tip from @cabal95 )
> https://github.com/SparkDevNetwork/Rock/blob/702d063ba019948ece1037ac591d4ada7995e2b0/Rock/Model/RegistrationTemplate.cs#L52

**My prior statements about the limit should be 200 are incorrect. I misread the SQL values (mistakenly read the octet length as the maximum length)**

**Comment by smross** [comment]
I'm not totally sure what to do with this issue at this point....

**I think that Rock should handle this exception better**
Potential approaches:

- Close this issue and open a new one, asking for Rock to handle this exception in a more friendly manner
- Edit this issue, cutting out the prior reference to the (misunderstood idea) of the maxlength being mismatched between C# and SQL. This would mean editing it to reflect only the 'handle the exception in a more friendly manner' portion of the issue
