### ISSUE TITLE
Exception: Error creating Analytics view

### ISSUE THREAD

**Issue by notGerryMiller** [SparkDevNetwork/Rock#4745]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When trying to create a metric with more than two partitions you are unable to create an analytics view. You will get the following exception.

Id | Exception Type | Source | Description |  
-- | -- | -- | -- | --
349225 | System.Exception |   | Error creating Analytics view for Active Leads | Hide Stack Trace
at Rock.Model.MetricService.EnsureMetricAnalyticsViews()    at RockWeb.Blocks.Reporting.MetricDetail.<>c__DisplayClass10_2.b__5()    at Rock.Data.DbContext.<>c__DisplayClass11_0.b__0()    at Rock.Data.DbContext.WrapTransactionIf(Func`1 action)    at RockWeb.Blocks.Reporting.MetricDetail.btnSave_Click(Object sender, EventArgs e)    at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)    at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)    at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)    at System.Web.UI.Page.ProcessRequest()    at System.Web.UI.Page.ProcessRequest(HttpContext context)    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)    at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)    at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb)    at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)    at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)    at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)    at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)    at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)    at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)    at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
349226 | System.Data.SqlClient.SqlException | .Net SqlClient Data Provider | The column '31' was specified multiple times for 'pvt'. The correlation name 'j31' is specified multiple times in a FROM clause. | Hide Stack Trace
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()    at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)    at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)    at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass59.b__57()    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)    at Rock.Model.MetricService.EnsureMetricAnalyticsViews() in C:\projects\Rock\Rock\Model\MetricService.Partial.cs:line 0

### Steps to Reproduce

1. Go to Metrics
2. Create A New Metric
3. Add at least three partitions 
4. Check the box to create an analytics view.
5. Click Save
6. No error will be generated for the user, however, an exception will be created and the view will not be made.

**Expected behavior:**

An analytics view should be creatted.

**Actual behavior:**

No analytics view is created an an exception is created. 

### Versions

* **Rock Version:** [12.4]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
@notGerryMiller it looks like there were two issues opened on this, so i'll close this one down while https://github.com/SparkDevNetwork/Rock/issues/4747 is worked on. Left reference link in 4747 to this in the comments if screenshots of your stack trace for this exception are needed.

**Comment by notGerryMiller** [comment]
@cwomack Awesome.  As long as the broken filter and the failure to create the BI database view are both fix I'm good with only one issue.
