### ISSUE TITLE
Elasticsearch Throwing Exception

### ISSUE THREAD

**Issue by notGerryMiller** [SparkDevNetwork/Rock#4753]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * X Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * X Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

Id | Exception Type | Source | Description |  
-- | -- | -- | -- | --
353038 | Elasticsearch.Net.UnexpectedElasticsearchClientException | Elasticsearch.Net | Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly. To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'hits.total.value', line 1, position 115. | Hide Stack Trace
at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)    at Nest.LowLevelDispatch.SearchDispatch[T](IRequest`1 p, PostData`1 body)    at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)    at Rock.UniversalSearch.IndexComponents.Elasticsearch.Search(String query, SearchType searchType, List`1 entities, SearchFieldCriteria fieldCriteria, Nullable`1 size, Nullable`1 from, Int64& totalResultsAvailable) in C:\projects\Rock\Rock\UniversalSearch\IndexComponents\Elasticsearch.cs:line 561    at RockWeb.Blocks.Cms.UniversalSearch.Search()    at RockWeb.Blocks.Cms.UniversalSearch.OnLoad(EventArgs e)    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Control.LoadRecursive()    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
353039 | Newtonsoft.Json.JsonSerializationException | Newtonsoft.Json | Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly. To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'hits.total.value', line 1, position 115. | Hide Stack Trace
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)    at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)    at Nest.JsonNetSerializer.Deserialize[T](Stream stream)    at Elasticsearch.Net.ResponseBuilder`1.SetBody(ElasticsearchResponse`1 response, Stream stream)    at Elasticsearch.Net.ResponseBuilder`1.ToResponse()    at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData)    at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)

### Description

We recently configured elasticsearch for universal search. It is indexing fine and we can query via curl/cli. This was most like caused by the version we are running. We are using a 7.x branch and the manual says to use a 2.x or 5.x branch of elastic search.

2.x was EOL on 2018-02-28
5.x was EOL on 2019-03-11

It looks like rock is using the following. Hopefully it just takes a library update. 
Elasticsearch.Net: https://www.nuget.org/packages/Elasticsearch.Net (2.5.8)
Newtonsoft.Json: https://www.nuget.org/packages/Newtonsoft.Json/ (11.0.1)

### Steps to Reproduce

This is hard to reproduce since this is a rare configuration.

1. Configure Elastic Search and Universal Search
2. Try to search at the following https://rock.yoururl.com/universalsearch
3. You'll get the above exceptions.

**Expected behavior:**

Rock to query elastic search and return valid search results.  I can query elastic search via the cli and get valid results.

**Actual behavior:**

See the above exceptions. 

### Versions

* **Rock Version:** 12.4
* **Client Culture Setting:** en-US
* **elasticsearch Version:** 7.14.0

**Comment by cwomack** [comment]
@notGerryMiller, thank you for your submission. After reviewing Rock's documentation, you've made us aware that the links/instructions to set up and install Elasticsearch take you to the most recent versions (v7+). This is a mistake as that's no longer the correct link.  Rock currently only works with Elasticsearch v2.x, and doesn't support the most recent versions at this time. 

We'll be updating the documentation to reflect that, but can you confirm everything works once you remove Elasticsearch v7 and then reinstall Elasticsearch v2.X?

**Comment by notGerryMiller** [comment]
It works fine now that I downgraded to v2.x.  However, using code that was EOL three and a half years ago doesn't feel great.

**Comment by cwomack** [comment]
@notGerryMiller we appreciate the feedback and will make updates to the documentation regarding Elasticsearch.  Since there's not quite a "bug" to fix at this point till Rock works with newer versions, I'll close the issue out.  Feel free to comment back however if there's additional issues regarding the use of Elasticsearch v2.X.
