### ISSUE TITLE
Benevolence Request Add Workflow Action fails with Foreign Key exception

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#5046]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

The Benevolence Request Add Workflow Action is throwing a Foreign Key exception in 13.4 This same workflow was working in 13.3, so it is a recent change. I was able to reproduce on the demo site (13.4.1) and prealpha (14.0.13)

It appears [this commit](https://github.com/SparkDevNetwork/Rock/commit/d9d5e8b9ad20af87496637b05d091faac97f8045) removed the default value for BenevolenceTypeId which is causing the workflow action to fail since it isn't setting any value for the type. While reverting that commit would fix this error, a better solution would be to add an option to the workflow action to select the type of request to create.

<details>
<summary>Here is the full text of the exception</summary>
<pre>The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.BenevolenceRequest_dbo.BenevolenceType_BenevolenceTypeId". The conflict occurred in database "bfc-rock-db", table "dbo.BenevolenceType", column 'Id'. The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 277
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 208
   at Rock.Workflow.Action.BenevolenceRequestAdd.Execute(RockContext rockContext, WorkflowAction action, Object entity, List`1& errorMessages) in C:\Github\Rock13\Rock\Workflow\Action\Finance\BenevolenceRequestAdd.cs:line 150
   at Rock.Model.WorkflowAction.Process(RockContext rockContext, Object entity, List`1& errorMessages) in C:\Github\Rock13\Rock\Model\Workflow\WorkflowAction\WorkflowAction.Logic.cs:line 485
   at Rock.Model.WorkflowActivity.Process(RockContext rockContext, Object entity, List`1& errorMessages) in C:\Github\Rock13\Rock\Model\Workflow\WorkflowActivity\WorkflowActivity.Logic.cs:line 152
   at Rock.Model.Workflow.ProcessActivity(RockContext rockContext, DateTime processStartTime, Object entity, List`1& errorMessages) in C:\Github\Rock13\Rock\Model\Workflow\Workflow\Workflow.Logic.cs:line 395
   at Rock.Model.Workflow.ProcessActivities(RockContext rockContext, Object entity, List`1& errorMessages) in C:\Github\Rock13\Rock\Model\Workflow\Workflow\Workflow.Logic.cs:line 205
   at Rock.Model.WorkflowService.Process(Workflow workflow, Object entity, List`1& errorMessages) in C:\Github\Rock13\Rock\Model\Workflow\Workflow\WorkflowService.cs:line 60
   at RockWeb.Blocks.WorkFlow.WorkflowEntry.CompleteCurrentWorkflowAction(Nullable`1 activateActivityTypeGuid, String responseText)
   at RockWeb.Blocks.WorkFlow.WorkflowEntry.CompleteFormAction(String formAction)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)</pre></details>

### Steps to Reproduce

1. Be on Rock 13.4+
1. Create a workflow using the "Benevolence Request Add" action
1. Run the workflow and see the error

**Expected behavior:**

A benevolence Request is created. Probably with the default request type since the action doesn't have an option to specify the type.

**Actual behavior:**

Rock throws an exception since there is no benevolence type set.

### Versions

* **Rock Version:** 13.4
* **Client Culture Setting:** en-US

**Comment by jorians** [comment]
@leahjennings and @MichaelAllen We have been testing this week for a move to v13.4 and also discovered this issue.  Would either of you be able to provide any insight on how quickly this issue might be addressed, or could suggest a possible work around if we do migrate to v13.4?

**Comment by jorians** [comment]
@MichaelAllen Thank you. We were due to upgrade on 6/27, but this Benevolence issue is pretty much a deal breaker for that upgrade. 

In your opinion, is there anything I could do, as a "work-around" that would allow us to upgrade, and still have the Benevolence Request added?

**Comment by MichaelAllen** [comment]
@jorians I don't think there is anything you could do to fix that action in 13.4, but you could temporarily modify your workflow to create the request another way. 

2 possibilities are the "Set Entity Properties" action from the "Workflow Stimpack" plugin or the "SQL Run" action. (If you need some help implementing either of those as a workaround, message me on Rocket Chat `@michaelallen` and I can talk you through it)

**Comment by nairdo** [comment]
@MichaelAllen  In case you need to know... FYI: We ended up shuffling things around in order to get a small-one-fix-change release to production this week as Rock version v13.5 (that was to fix a critical bug with the Checkr webhook).  Because of that, the previously named `hotfix-1.13.5` branch is now essentially `hotfix-1.13.6`.

**Comment by jrockman13** [comment]
Will there be a 13.7? I'm not seeing this in the 14.0 alpha notes. Our AGAPE fund team is really struggling with this regression.
