### ISSUE TITLE
Connection Request Entity Administration security cannot be edited

### ISSUE THREAD

**Issue by jliaoGFC** [SparkDevNetwork/Rock#5100]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
* Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description
We want to give a group of staff permission to add/edit connection requests. However, when we click on the lock icon for the Rock.Model.ConnectionRequest Entity under Entity Administration, we get the below error. We are on v12.7. We replicated it on 13.3, 13.6 (Rockdemo), and 14.0 (pre-alpha).
### Steps to Reproduce
1. Go to https://rock.rocksolidchurchdemo.com/admin/security/entity.
2. Click on the Lock button next to Rock.Model.ConnectionRequest.
**Expected behavior:**
Allow for editing.
**Actual behavior:**
Error popup with the following text:
NullReferenceException in Rock
Message
Object reference not set to an instance of an object.
Stack Trace
   at Rock.Model.ConnectionRequest.ToString() in C:\Source\Repos\Rock12\Rock\Model\ConnectionRequest.cs:line 464
   at RockWeb.Blocks.Administration.Security.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at Rock.Web.UI.RockBlockWrapper.CreateChildControls() in C:\Source\Repos\Rock12\Rock\Web\UI\RockBlockWrapper.cs:line 71
   at System.Web.UI.Control.EnsureChildControls()
   at Rock.Web.UI.RockPage.OnInit(EventArgs e) in C:\Source\Repos\Rock12\Rock\Web\UI\RockPage.cs:line 1322
   at ASP.themes_rock_layouts_dialog_aspx.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
### Versions
* **Rock Version:** v12.7
* **Client Culture Setting:** [Cloud hosted in Azure]

![image001](https://user-images.githubusercontent.com/110692421/183141527-092db583-745a-4ee2-bf63-f84089543fa1.png)

**Comment by nairdo** [comment]
Although this is a bug we're fixing, setting up various teams to be the 'connectors' for connection requests really should not typically involve trying to edit the Entity security for the `Rock.Model.ConnectionReqest`.  Some help might be seen here in this guide: https://community.rockrms.com/documentation/bookcontent/39#10000footviewofconnections
