### ISSUE TITLE
[Alpha v14.0] - 'Update Persisted Attribute Values' Job Failing

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5131]
### Description
In my v14.0 test instance, the _Update Persisted Attribute Values_ job is failing when it runs every night _and_ when I run in manually.

Stack Trace:
```
at Rock.Field.Types.EventCalendarFieldType.<>c.b__1_1(EventCalendarCache eventCalendar) in C:\Github\Rock\Rock\Field\Types\EventCalendarFieldType.cs:line 70
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Rock.Field.Types.EventCalendarFieldType.GetTextValue(String privateValue, Dictionary`2 privateConfigurationValues) in C:\Github\Rock\Rock\Field\Types\EventCalendarFieldType.cs:line 70
   at Rock.Field.FieldType.GetPersistedValues(String privateValue, Dictionary`2 privateConfigurationValues) in C:\Github\Rock\Rock\Field\FieldType.cs:line 1142
   at Rock.Jobs.UpdatePersistedAttributeValues.UpdateDirtyAttributeValues(Int32 commandTimeout, IJobExecutionContext context) in C:\Github\Rock\Rock\Jobs\UpdatePersistedAttributeValues.cs:line 486
   at Rock.Jobs.UpdatePersistedAttributeValues.UpdateDirtyAttributesAndValues(Int32 commandTimeout, IJobExecutionContext context) in C:\Github\Rock\Rock\Jobs\UpdatePersistedAttributeValues.cs:line 447
   at Rock.Jobs.UpdatePersistedAttributeValues.Execute(IJobExecutionContext context) in C:\Github\Rock\Rock\Jobs\UpdatePersistedAttributeValues.cs:line 111
   at Quartz.Core.JobRunShell.Run()
```

#### A Picture Is worth a Thousand Words

![Screen Shot 2022-08-22 at 13 51 05](https://user-images.githubusercontent.com/23226974/185986643-1dbd9226-2e48-4f4e-9ae8-6b462c7340d8.png)

![Screen Shot 2022-08-22 at 13 51 26](https://user-images.githubusercontent.com/23226974/185986738-dad040dc-32a7-4197-80a0-1b138d3c4ed6.png)

### Steps to Reproduce

Unsure, as it is not happening on the dev server.

**Expected behavior:**

Job run successfully.

**Actual behavior:**

Job does not run successfully.

### Versions

* **Rock Version:** [v14.0]
* **Client Culture Setting:** [en-US]

**Comment by ethan-sparkdevnetwork** [comment]
Fixed the EventCalendarFieldType and a few others that could get this error.
https://github.com/sparkdevnetwork/rock/commit/7651e85f715dc20df65682fb6fa874f32f6a79f6
https://github.com/sparkdevnetwork/rock/commit/21d40cf55f4db21c4579c693b0cd2b4134bb7da3
https://github.com/sparkdevnetwork/rock/commit/197b385a78cb6a64ada01f5ef71171985b8be227

**Comment by mikedotmundy** [comment]
This job is completing successfully now every night, however I have noticed that every few days it can take 30ish minutes to run. My DB is sitting at 100% for a chunk of the time it's running. Is this behavior normal?

Note: My dev DB is dialed back to an S1 (20 DTUs).

![Screenshot 2023-02-01 at 07 27 11](https://user-images.githubusercontent.com/23226974/216043204-b8193b04-9084-49e0-909c-7127a83468fb.png)

![Screenshot 2023-02-01 at 07 34 53](https://user-images.githubusercontent.com/23226974/216043991-2f6335a7-674c-4889-8d59-622361acb50e.png)

**Comment by cabal95** [comment]
@mikedotmundy TL;DR; The pattern you are seeing is normal.

Out of the box, the job is configured to update 25% of the attributes (and their values) each time it is run, whether it thinks it needs them or not. This was done to deal with cases where people are currently using SQL to update values but since it is old SQL it doesn't set the new IsDirty flag on the value. This is also meant to cover cases where if something "just went wonky" and the persisted value is wrong, it will eventually get set correctly after a couple days.

So the spike every 4 days is "expected". The way it determines 25% is by Attribute not Value (there are reasons for this). So every 4th night it's working on a specific 1/4 chunk of the attributes. And some of those attributes probably have lots and lots of related attribute values (Person Attributes for example).

You could try changing the block setting for that 25% value to a lower value - but that might not help. Meaning, if most of that 25 minutes is from a set of 20 attributes all in sequence, then they would probably still fall into the same "chunk".

**Comment by mikedotmundy** [comment]
Thanks @cabal95
