### ISSUE TITLE
[Alpha v1.14.1.1] Steps Automation Job Failing and Creating Exception

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5270]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The Steps Automation job is failing and creating an exception. This also fails in v15.0.

This job is working properly in my v13.7 instance. 

I am not sure, but this may be related to #5269.

#### A Picture Is worth a Thousand Words
<img width="1725" alt="Screenshot 2023-01-10 at 20 42 22" src="https://user-images.githubusercontent.com/23226974/211698732-415128f1-6ef1-4d2d-bcdc-6625123a1ad4.png">

<img width="1723" alt="Screenshot 2023-01-10 at 20 42 35" src="https://user-images.githubusercontent.com/23226974/211698737-41d821b2-05dc-4f69-8af4-3ba0a77e312a.png">

Full Stack Trace:
```
at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.InlineObjectQuery(ObjectQuery inlineQuery, Type expressionType)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.InlineValue(Expression expression, Boolean recompileOnChange)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.Visit(Expression exp)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitExpressionList(ReadOnlyCollection`1 original)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitMethodCall(MethodCallExpression m)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.Visit(Expression exp)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitLambda(LambdaExpression lambda)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.Visit(Expression exp)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitUnary(UnaryExpression u)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.Visit(Expression exp)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitExpressionList(ReadOnlyCollection`1 original)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitMethodCall(MethodCallExpression m)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.Visit(Expression exp)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitExpressionList(ReadOnlyCollection`1 original)
   at System.Linq.Expressions.EntityExpressionVisitor.VisitMethodCall(MethodCallExpression m)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.FuncletizingVisitor.Visit(Expression exp)
   at System.Data.Entity.Core.Objects.ELinq.Funcletizer.Funcletize(Expression expression, Func`1& recompileRequired)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter..ctor(Funcletizer funcletizer, Expression expression)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.CreateExpressionConverter()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.b__1()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1..GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.Jobs.StepsAutomation.ProcessStepType(IJobExecutionContext jobContext, StepTypeView stepTypeView, Int32 minDaysBetweenSteps, ConcurrentBag`1 addedResults, ConcurrentBag`1 updatedResults, List`1& errorMessages) in C:\Github\Rock14\Rock\Jobs\StepsAutomation.cs:line 229
   at Rock.Jobs.StepsAutomation.Execute(IJobExecutionContext context) in C:\Github\Rock14\Rock\Jobs\StepsAutomation.cs:line 128
   at Quartz.Core.JobRunShell.Run()
```

### Steps to Reproduce

1. Go to a Step Type and add a Data View to the `Auto-Complete Data View` section. Save the Step Type.
2. Run the Steps Automation Job. 
3. See error.

**Expected behavior:**

Steps Automation Job run successfully.

**Actual behavior:**

Steps Automation Job does not run successfully.

### Versions

* **Rock Version:** [v14.1, v15.0]
* **Client Culture Setting:** [en-US]

**Comment by shivambareria** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/43d5e62cbc0ad939fcd148a62ee0efa6ebf72c2e

**Comment by shivambareria** [comment]
https://github.com/SparkDevNetwork/Rock/commit/43d5e62cbc0ad939fcd148a62ee0efa6ebf72c2e
