### ISSUE TITLE
Saving Attribute Matrix Item times out the database

### ISSUE THREAD

**Issue by nlBayside** [SparkDevNetwork/Rock#5303]
### Please go through all the tasks below ###

* [x] Check this box only after you have successfully completed both the above tasks

## Overview ##

I'm noticing this problem on our database when saving an Attribute Matrix Item where it times out and I see an exception. This exception doesn't occur all the time; however, I can see from the Exception that it starts when I click "Save" from the ```AttributeMatrixEditor```control, and near the end goes to```BuildHistoryItems()```from AttributeMatrixItem.Logic.cs before reaching a```FirstOrDefault()```

When I was reading through the the ```BuildHistoryItem()```, I saw something that I thought might be causing such a long query. This line [here](https://github.com/SparkDevNetwork/Rock/blob/71cdbe6d8ac8bc7c340bee149355accbdb2e6a75/Rock/Model/Core/AttributeMatrixItem/AttributeMatrixItem.Logic.cs#L82) which reads:

```
var rootAttributeValue = attributeValueService.Queryable().AsNoTracking().FirstOrDefault( av =>
                av.Value.Equals( matrixGuidString, System.StringComparison.OrdinalIgnoreCase )
                && av.Attribute.EntityTypeId == personEntityTypeId );
```

The entity type that we're saving this to in our database is a Content Channel Item. I'm curious to know if AttributeMatrixItems are _not_ supposed to be used for anything other than the Person Entity Type. Regardless, this query is so slow for us that it's unusable sometimes. When it does work, I have a feeling its just due to SQL Server performing the correct query optimizations and caching.

## Query Plan ##

Below you will find the actual query plan that gets generated when the SQL query is run from that line.

![](https://user-images.githubusercontent.com/85907597/217685590-d50c00c2-8a7e-4db6-ab35-3df516521373.png)

This image is the SQL query that gets generated from Line 82 in ```AttributeMatrixItem.Logic.cs```

![](https://user-images.githubusercontent.com/85907597/217685631-388a4644-c0e9-42ba-8af2-09b9ab5b8e9a.png)

## History ##

When this query does work, the ```rootAttributeValue```is null. This means when this check(```rootAttributeValue?.EntityId == null```) is made, it will return true and the whole method is done. There is no history logged for a root attribute. I really think this is supposed to be used only for Person entity types because in areas where the History table is used for```BuildHistoryItems()```, it is referring to Person Demographic Changes. 

## Exception ##

    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
       at System.Data.SqlClient.SqlDataReader.get_MetaData()
       at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
       at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
       at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
       at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
       at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
       at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
       at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
       at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
       at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at Rock.Model.AttributeMatrixItem.BuildHistoryItems(DbContext dbContext, DbEntityEntry entry, EntityState state) in C:\Github\Rock13\Rock\Model\AttributeMatrixItem.cs:line 149
       at Rock.Data.Model`1.PreSaveChanges(DbContext dbContext, DbEntityEntry entry, EntityState state) in C:\Github\Rock13\Rock\Data\Model.cs:line 266
       at Rock.Data.DbContext.RockPreSave(DbContext dbContext, PersonAlias personAlias, Boolean enableAuditing) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 501
       at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 244
       at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 208
       at Rock.Data.DbContext.SaveChanges() in C:\Github\Rock13\Rock\Data\DbContext.cs:line 193
       at Rock.Web.UI.Controls.AttributeMatrixEditor.btnSaveMatrixItem_Click(Object sender, EventArgs e) in C:\Github\Rock13\Rock\Web\UI\Controls\AttributeMatrixEditor.cs:line 601
       at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
       at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
       at RockWeb.Global.Application_Error(Object sender, EventArgs e)
       at System.Web.HttpApplication.RaiseOnError()
       at System.Web.HttpApplication.RecordError(Exception error)
       at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)
       at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb)
       at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
       at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
       at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
       at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
       at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
       at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
       at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
       at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
       at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
       at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
       at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at Rock.Model.AttributeMatrixItem.BuildHistoryItems(DbContext dbContext, DbEntityEntry entry, EntityState state) in C:\Github\Rock13\Rock\Model\AttributeMatrixItem.cs:line 149
       at Rock.Data.Model`1.PreSaveChanges(DbContext dbContext, DbEntityEntry entry, EntityState state) in C:\Github\Rock13\Rock\Data\Model.cs:line 266
       at Rock.Data.DbContext.RockPreSave(DbContext dbContext, PersonAlias personAlias, Boolean enableAuditing) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 501
       at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 244
       at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Github\Rock13\Rock\Data\DbContext.cs:line 208
       at Rock.Data.DbContext.SaveChanges() in C:\Github\Rock13\Rock\Data\DbContext.cs:line 193
       at Rock.Web.UI.Controls.AttributeMatrixEditor.btnSaveMatrixItem_Click(Object sender, EventArgs e) in C:\Github\Rock13\Rock\Web\UI\Controls\AttributeMatrixEditor.cs:line 601
       at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
       at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
    
    Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
       at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
       at System.Data.SqlClient.SqlDataReader.get_MetaData()
       at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
       at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
       at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
       at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
       at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
    
    The wait operation timed out### Expected Behavior ###

The Attribute Matrix Item saves to the database.

### Actual Behavior ###

The database times out and we can't save the new Attribute Matrix Item.

### Steps to Reproduce ###

* Have plenty of attribute values in your database
* Save an attribute matrix item to a content channel item.

The Time out for the exception makes sense if the query is taking too long. Our database has over 4 million attribute value records for reference. A short amount of Attribute Values would likely run this quickly.

### Rock Version ###

13.7

### Client Culture Setting ###

us-en

**Comment by bobrufenacht** [comment]
We have seen this timeout issue and struggled with it as well with several churches when trying to use attribute matrices.

**Comment by zackdutra** [comment]
@sparkdevnetwork-service could you explain the Enhancement categorization? For us this appears to be a bug and is preventing the attribute matrix from working on any entity type including Person.

**Comment by zackdutra** [comment]
This has been tested on General Purpose service tier with 8 vCores and General Purpose service tier with 24 vCores. No change in behavior.

**Comment by JesseBeaird** [comment]
We are also seeing the same issue while saving a Person Attribute Matrix running 15.1.

**Comment by zackdutra** [comment]
@JesseBeaird could you share which service tier you're on if you're running Azure? For example, our is the General Purpose tier with 8 vCores, however it was also confirmed with 24 vCores.
