### ISSUE TITLE
Person History Block

### ISSUE THREAD

**Issue by davidbelk** [SparkDevNetwork/Rock#5313]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Person history under the person profile shows an exception when trying to view the history for most people but not all. I have verified with Tim Dear at Pinelake Church in Mississippi and they are seeing the same issue. 

### Steps to Reproduce

1. Go to Person Profile Page. Not every person is doing it. 
2. Click On Person History. 
3. See Exception:
NullReferenceException in App_Web_lzhwcf04
Message
Object reference not set to an instance of an object.

Stack Trace

   at RockWeb.Blocks.Checkin.AttendanceHistoryList.<>c__DisplayClass27_0.<BindGrid>b__9(<>f__AnonymousType1`12 a)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RockWeb.Blocks.Checkin.AttendanceHistoryList.BindGrid()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Expected behavior:** 

The expected behavior is being able to see the person history on the page. 

**Actual behavior:** 

The majority of people have the issue. A few do not. 

### Versions

* **Rock Version:** 14.1 
* **Client Culture Setting:** US

**Comment by dataCollegechurch** [comment]
I am unable to reproduce this on the demo site. Is there a specific person profile on the demo site you were able to reproduce this error on?

**Comment by MargaretMailhiot** [comment]
The demo site is only on 14.0. We just updated to 14.1 this week and are running into this same error on profiles

**Comment by RufenachtPW** [comment]
I ran into this issue as well. Upon troubleshooting, I found the issue has to do when an attendance occurrence record does not have a GroupId. The column, GroupId, on the attendanceOccurrence table allows nulls. On line 419 of the AttendanceHistoryList there is no check for GroupId. There needs to be a check for GroupId AND check for isAuthorized and an Or to get attendances where GroupId is null Suggest changing line 419 from Where( a => a.Group.IsAuthorized( Authorization.VIEW, this.CurrentPerson ) ) to .Where( a => ( a.Group != null && a.Group.IsAuthorized( Authorization.VIEW, this.CurrentPerson )) || a.Group == null )

**Comment by KCKurz** [comment]
We updated to 14.0 and this was not an issue, but once we went into v14.1, I can isolate the problem to only those who have Admin Security Permissions. Everyone else is fine. I hope this helps get us closer to a resolution.
![image](https://user-images.githubusercontent.com/103592812/224874866-086b8328-2b5b-4c50-88c0-d7207d53b935.png)

**Comment by KCKurz** [comment]
Please disregard my previous comment, I now have encountered this error on a nonstaff Rock profile. I see this task is "Confirmed", does that mean it is being worked on to bring resolution?

**Comment by ethan-sparkdevnetwork** [comment]
@KCKurz Confirmed just means that someone here was able to reproduce the issue.

**Comment by nlBayside** [comment]
We are also seeing this issue at our church. The records that are causing it are ones imported in from before we used Rock, so their GroupIds are null. Still an issue since we imported a lot of previous data.

**Comment by azturner** [comment]
Parkview Church encountered this error too on v14.1. Adding the `a.Group == null ||` on line 419 of the AttendanceHistoryList.ascx.cs file fixed it for them:
![image](https://user-images.githubusercontent.com/548180/228623483-11da85a3-0921-4ed7-bb37-1b424ce9ddd2.png)
