### ISSUE TITLE
Odd behavior when Saving Transaction

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5348]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When saving and adding a new Transaction to a Batch, after adding your amount, if you do not click outside of the Amount field before saving, you will be greeted with a message stating you have not added an amount. This behavior is the same for the _Save_, _Save Then Add_, and _Save Then View Batch_ buttons.

<img width="1728" alt="Screenshot 2023-03-17 at 16 17 11" src="https://user-images.githubusercontent.com/23226974/226030738-20889cae-5a9f-4410-97d9-8c3ea030353d.png">

This is a minor bug, however this is not normal behavior like in other areas of Rock.

The attached video will hopefully explain a little better what the issue is.

https://user-images.githubusercontent.com/23226974/226029626-6da43379-be51-41dc-a071-3a79a67afdbd.mov

In our instance, this is also generating an exception. However, I did not see an exception created when testing on the demo site.
<img width="1724" alt="Screenshot 2023-03-17 at 16 35 46" src="https://user-images.githubusercontent.com/23226974/226037407-0cdf4fc5-6ebf-42f9-9acd-7190267e8604.png">

```
  at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Rock.Web.UI.RockHiddenFieldPageStatePersister.Load() in C:\Github\Rock14\Rock\Web\UI\RockHiddenFieldPageStatePersister.cs:line 112
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

### Expected Behavior

I would expect that I do not have to click out of the Amount field before saving the Transaction.

### Actual Behavior

You must click outside the Amount field before saving the Transaction.

### Steps to Reproduce

- Add a new Batch.
- Add a Transaction to the new Batch. **For this first transaction, you will not see the issue.** However, input all the required info and then click `Save Then Add`. 
- Now, on the 2nd transaction, select a Person. 
- Enter a dollar amount in the `Amount` field, and DO NOT click on the page. Click `Save Then Add` (or any of the "Save" buttons). 
- See the modal pop up stating that the amount you entered is still registering $0. 
- You can repeat the above steps, only instead make sure to click anywhere after entering an amount, and then click `Save`. You will notice it worked properly.

### Rock Version

v14.1, v14.2, v15.0

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
This is still an issue for us in v15.1

Here is a screenshot of the exception:

<img width="1723" alt="Screenshot 2023-07-17 at 20 45 44" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/85c8236f-d6d3-46e4-b690-2a6d7ebb626b">

Stack trace:
```
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Rock.Web.UI.RockHiddenFieldPageStatePersister.Load() in \Rock\Web\UI\RockHiddenFieldPageStatePersister.cs:line 112
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```
