### ISSUE TITLE
Connection Badges

### ISSUE THREAD

**Issue by davidbelk** [SparkDevNetwork/Rock#5352]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Tell us what you see!

When I deleted a badge from [Home](https://rock.rocksolidchurchdemo.com/Admin)[General Settings](https://rock.rocksolidchurchdemo.com/admin/general) that was set on the [/people/connections/board](https://rock.rocksolidchurchdemo.com/people/connections/board) 

I was able to fix this by going to the block settings on the connections board page and saving. It began to work again. 

NullReferenceException in Rock
Message
Object reference not set to an instance of an object.

Stack Trace

   at Rock.Web.UI.Controls.BadgeListControl.<>c.<CreateChildControls>b__11_0(BadgeCache b) in C:\GitHub\Rock14\Rock\Web\UI\Controls\Badges\BadgeListControl.cs:line 108
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Rock.Web.UI.Controls.BadgeListControl.CreateChildControls() in C:\GitHub\Rock14\Rock\Web\UI\Controls\Badges\BadgeListControl.cs:line 108
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.WebControls.CompositeControl.get_Controls()
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.SetValidationGroup(Control[] controls, String validationGroup) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 1149
   at Rock.Web.UI.RockBlock.OnLoad(EventArgs e) in C:\GitHub\Rock14\Rock\Web\UI\RockBlock.cs:line 555
   at RockWeb.Blocks.Connection.ConnectionRequestBoard.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Expected Behavior

Expected Behavior

The badge should automatically be removed so the block is not looking for it? 

### Actual Behavior

Actual Behavior

Once the badge is deleted, it causes the exception on the connection board page. 

### Steps to Reproduce

Delete a badge that is set to show up in connections. 

Go to the connection board.

See the error. 

Go to the block settings on the connection board page and edit the block, hit save and it fixes the error. 

### Rock Version

14.2 

### Client Culture Setting

en-US

**Comment by BrentPirolli** [comment]
I've ran into similar issues in the past where deleting a check-in tag that was assigned to a check-in event would cause errors until you went in and removed it. I'm not sure Rock handles deletions in a way that they check if things are in use all the time or not. I'll mark this as an enhancement to look into.
