### ISSUE TITLE
[v15.0 Alpha] Giving Configuration Block - The name 'lTTGDefaultAccount' does not exist in the current context

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#5384]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When loading a business profile there is an error where the `Giving Configuration` block is.  I was not able to recreate this on the demo server.

The name 'lTTGDefaultAccount' does not exist in the current context

<img width="856" alt="Screenshot 2023-04-11 at 2 19 36 PM" src="https://user-images.githubusercontent.com/22873346/231290665-ef0cdc34-41df-41a9-a837-4cb43b15cf7f.png">

### Expected Behavior

Expected to not see an error

### Actual Behavior

Error is shown when loading the page.

### Steps to Reproduce

Search for a business in V15.0 alpha
The error will be displayed on the page.

### Rock Version

15.0

### Client Culture Setting

en-US

**Comment by randyjreed** [comment]
Here is the exception stack trace and a screenshot of the error on the page properties.

`at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at Rock.Web.Cache.BlockTypeCache.GetCompiledType() in C:\GitHub\Rock\Rock\Web\Cache\Entities\BlockTypeCache.cs:line 311`

<img width="1372" alt="Screenshot 2023-04-12 at 8 15 44 AM" src="https://user-images.githubusercontent.com/22873346/231503430-676a8bee-94d1-469d-9e80-4385449e79ef.png">

**Comment by ethan-sparkdevnetwork** [comment]
@randyjreed This error would occur if the GivingConfiguration.ascx file was not replaced but the GivingConfiguration.ascx.cs was. Can you check GivingConfiguration.ascx for "<asp:Literal ID="lTTGDefaultAccount" runat="server" />"?

Also do you have any pre/post html for the block or other custom work?

**Comment by randyjreed** [comment]
UPDATE: Ran the Alpha update again on a fresh dev server and the issue was not present this time.
