### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#5418]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Intermittent exceptions (as in the title) thrown from workflow processing. The exception suggests that a .Net collection was modified while code was iterating over the collection (not allowed). There is not a mechanism whereby a workflow itself could violate this rule.

The stack track indicates this happens when the workflow engine finishes processing a random workflow and attempts a SaveChanges to persist the changes to the workflow. It appears to be iterating over items in the attribute cache (a .Net collection) when the exception is thrown.

This started about a week ago when we installed a snapshot of hotfix-1.14.3 to address extremely slow IIS startup problems we've seen since deploying V14. The patches dramatically reduced system startup (~15 minutes to ~1 minute), but we've been seeing this problem intermittently ever since.

```

1740 | System.InvalidOperationException | mscorlib | Collection was modified; enumeration operation may not execute. | Hide Stack Trace
-- | -- | -- | -- | --
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at Rock.Web.Cache.EntityCache`2.All(RockContext rockContext) in C:\Rock14\Rock\Web\Cache\EntityCache.cs:line 468    at Rock.Web.Cache.AttributeCache.GetAttributePropertyDependencies() in C:\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 858    at Rock.Web.Cache.RockCache.GetOrAddExisting(RockCacheGetOrAddExistingArgs args) in C:\Rock14\Rock\Web\Cache\RockCache.cs:line 363    at Rock.Web.Cache.RockCache.GetOrAddExisting(String key, String region, Func`1 itemFactory, TimeSpan expiration) in C:\Rock14\Rock\Web\Cache\RockCache.cs:line 337    at Rock.Web.Cache.AttributeCache.GetDirtyAttributeIdsForPropertyChange(Int32 entityTypeId, Func`1 modifiedPropertyNamesFactory) in C:\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 901    at Rock.Data.DbContext.RockPostSave(List`1 updatedItems, PersonAlias personAlias, Boolean enableAuditing) in C:\Rock14\Rock\Data\DbContext.cs:line 635    at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Rock14\Rock\Data\DbContext.cs:line 338    at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Rock14\Rock\Data\DbContext.cs:line 261    at Rock.Model.WorkflowService.Process(Workflow workflow, Object entity, List`1& errorMessages) in C:\Rock14\Rock\Model\Workflow\Workflow\WorkflowService.cs:line 60    at Rock.Jobs.ProcessWorkflows.Execute(IJobExecutionContext context) in C:\Rock14\Rock\Jobs\ProcessWorkflows.cs:line 93
```

### Expected Behavior

These exceptions should not occur.

### Actual Behavior

These exceptions do occur. They occur randomly on workflows of different types. They do not repeat on a given workflow.

### Steps to Reproduce

Build an inventory of workflows queued for processing by the workflow engine. Let the engine run. Observe the exceptions.

We only see a handful (<5) of these exceptions a day and have a relatively large database with several thousand active workflows. This behaves as a narrow timing crack, most likely indicating a multi-threaded concurrency problem. It first showed up when we pulled in hotfix-1.14.3 changes that changed how attribute cache works. (Our snapshot would have been taken on Friday 4/14/2023.)

### Rock Version

1.14.3 (4/14/2023)

### Client Culture Setting

en-US

**Comment by SteveSwaringen** [comment]
We've also seen this exception on the Group Sync job.
```
4573	System.InvalidOperationException	mscorlib	Collection was modified; enumeration operation may not execute.	
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.Web.Cache.EntityCache`2.All(RockContext rockContext) in C:\Git\Rock14\Rock\Web\Cache\EntityCache.cs:line 468
   at Rock.Web.Cache.AttributeCache.GetAttributePropertyDependencies() in C:\Git\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 858
   at Rock.Web.Cache.RockCache.GetOrAddExisting(RockCacheGetOrAddExistingArgs args) in C:\Git\Rock14\Rock\Web\Cache\RockCache.cs:line 308
   at Rock.Web.Cache.RockCache.GetOrAddExisting(String key, String region, Func`1 itemFactory, TimeSpan expiration) in C:\Git\Rock14\Rock\Web\Cache\RockCache.cs:line 282
   at Rock.Web.Cache.AttributeCache.GetDirtyAttributeIdsForPropertyChange(Int32 entityTypeId, Func`1 modifiedPropertyNamesFactory) in C:\Git\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 901
   at Rock.Data.DbContext.RockPostSave(List`1 updatedItems, PersonAlias personAlias, Boolean enableAuditing) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 635
   at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 338
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 261
   at Rock.ExtensionMethods.UpdateLastStatusMessage(IJobExecutionContext context, String message) in C:\Git\Rock14\Rock\Utility\ExtensionMethods\QuartzExtensions.cs:line 46
   at Rock.Jobs.GroupSync.Execute(IJobExecutionContext context) in C:\Git\Rock14\Rock\Jobs\GroupSync.cs:line 122
```

**Comment by SteveSwaringen** [comment]
And Communication Transport
```
4238	System.InvalidOperationException	mscorlib	Collection was modified; enumeration operation may not execute.	
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.Web.Cache.EntityCache`2.All(RockContext rockContext) in C:\Git\Rock14\Rock\Web\Cache\EntityCache.cs:line 468
   at Rock.Web.Cache.AttributeCache.GetAttributePropertyDependencies() in C:\Git\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 858
   at Rock.Web.Cache.RockCache.GetOrAddExisting(RockCacheGetOrAddExistingArgs args) in C:\Git\Rock14\Rock\Web\Cache\RockCache.cs:line 308
   at Rock.Web.Cache.RockCache.GetOrAddExisting(String key, String region, Func`1 itemFactory, TimeSpan expiration) in C:\Git\Rock14\Rock\Web\Cache\RockCache.cs:line 282
   at Rock.Web.Cache.AttributeCache.GetDirtyAttributeIdsForPropertyChange(Int32 entityTypeId, Func`1 modifiedPropertyNamesFactory) in C:\Git\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 901
   at Rock.Data.DbContext.RockPostSave(List`1 updatedItems, PersonAlias personAlias, Boolean enableAuditing) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 635
   at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 338
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 261
   at Rock.Communication.EmailTransportComponent.d__20.MoveNext() in C:\Git\Rock14\Rock\Communication\EmailTransportComponent.cs:line 1055
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Rock.Communication.Transport.ThrottleHelper.d__0.MoveNext() in C:\Git\Rock14\Rock\Communication\Transport\ThrottleHelper.cs:line 35
```

**Comment by SteveSwaringen** [comment]
And a login attempt.
```
3687	System.InvalidOperationException	mscorlib	Collection was modified; enumeration operation may not execute.	
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.Web.Cache.EntityCache`2.All(RockContext rockContext) in C:\Git\Rock14\Rock\Web\Cache\EntityCache.cs:line 468
   at Rock.Web.Cache.AttributeCache.GetAttributePropertyDependencies() in C:\Git\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 858
   at Rock.Web.Cache.RockCache.GetOrAddExisting(RockCacheGetOrAddExistingArgs args) in C:\Git\Rock14\Rock\Web\Cache\RockCache.cs:line 308
   at Rock.Web.Cache.RockCache.GetOrAddExisting(String key, String region, Func`1 itemFactory, TimeSpan expiration) in C:\Git\Rock14\Rock\Web\Cache\RockCache.cs:line 282
   at Rock.Web.Cache.AttributeCache.GetDirtyAttributeIdsForPropertyChange(Int32 entityTypeId, Func`1 modifiedPropertyNamesFactory) in C:\Git\Rock14\Rock\Web\Cache\Entities\AttributeCache.cs:line 901
   at Rock.Data.DbContext.RockPostSave(List`1 updatedItems, PersonAlias personAlias, Boolean enableAuditing) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 635
   at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 338
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in C:\Git\Rock14\Rock\Data\DbContext.cs:line 261
   at Rock.Model.UserLoginService.UpdateLastLogin(String userName) in C:\Git\Rock14\Rock\Model\CRM\UserLogin\UserLoginService.WebForms.cs:line 121
   at RockWeb.Blocks.Security.Login.LoginUser(String userName, String returnUrl, Boolean rememberMe) in E:\Web\RockRMS\Blocks\Security\Login.ascx.cs:line 645
   at RockWeb.Blocks.Security.Login.CheckUser(UserLogin userLogin, String returnUrl, Boolean rememberMe) in E:\Web\RockRMS\Blocks\Security\Login.ascx.cs:line 474
   at RockWeb.Blocks.Security.Login.btnLogin_Click(Object sender, EventArgs e) in E:\Web\RockRMS\Blocks\Security\Login.ascx.cs:line 426
   at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**Comment by SteveSwaringen** [comment]
What is consistent about the pattern in all cases is that a DbContext.SaveChanges() is causing an AttributeCache.GetDirtyAttributeIdsForPropertyChange() call that precipitates the "Collection was modified; enumeration operation may not execute" exception.

**Comment by SteveSwaringen** [comment]
Update on this. We backed out all of the 1.14.3 changes we had pulled into our custom build of 14.2. Since doing that, we haven't seen any of these anomalous exceptions (though we do now have to endure 5+ minute Rock restarts). (We had been seeing several of these exceptions per day.) Nor have we seen any of the dropped registrant group member assignments that had plagued us. (About 25% of registrants that should have been added to registration groups (Obsidian registrations) were not added to the groups. No exceptions were logged, they were just silently dropped.)

Something in the 1.14.3 code we pulled in is bad and I don't see anything in any of the 1.15.0 deltas that would likely correct the problem.

**Comment by ethan-sparkdevnetwork** [comment]
@SteveSwaringen Does your code have anything custom code in the Rock project?

**Comment by ethan-sparkdevnetwork** [comment]
@SteveSwaringen Can we get the compiled rock.dll that had the 14.3 changes in it? You can just zip it and email it to me.

**Comment by ethan-sparkdevnetwork** [comment]
@SteveSwaringen One more thing, which commit did you merge when you pulled in the 14.3 code?

**Comment by SteveSwaringen** [comment]
@ethan-sparkdevnetwork We do have some custom code in the Rock project. It is unlikely that we have anything that would interact at this low level but we don't run stock Rock. I'll send you a zip of the last version we had that was showing this set of problems.

The "which commit" question is harder to answer. We started by merging your hotfix-1.14.3 branch at a point in time (Friday 4/14/2023). That's when the problems started. We later pulled in one additional commit (https://github.com/SparkDevNetwork/Rock/commit/b1a76a868228af70f58a5b7db74963588ced1c01) that was added to this branch later that looked like it might have been a solution. It didn't seem to have any impact on the problem. The DLL I'll send you included this commit as well.

I note that the "additional commit" was also dated 4/14 but I'm pretty sure it wasn't included in what we originally pulled from hotfix-1.14.3.

**Comment by ethan-sparkdevnetwork** [comment]
The dll in the google drive doesn't include b1a76a8. Are you able to pull the current hotfix-14.3 branch to a non-production system and see if the error occurs?

**Comment by SteveSwaringen** [comment]
The issue is  plausibly corrected by https://github.com/SparkDevNetwork/Rock/commit/b1a76a868228af70f58a5b7db74963588ced1c01. It looks like a build error caused this to be missing from our solution. Closing ticket as noted above.
