### ISSUE TITLE
Send Group Attendance Reminder job fails to run correctly

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5488]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When using the new (v15) Send Group Attendance Reminder job, it fails to run correctly. Some times the job will run correctly but other times it fails. I think it has to do with what groups its trying to send out reminders for. I have been unable to troubleshoot this more indepth. 

### Expected Behavior

Each time this runs (in our case every 15 minutes) it should complete and send relevant reminders. 

### Actual Behavior

The job does not complete correctly. This is the error we are getting: 

Cannot insert duplicate key row in object 'dbo.AttendanceOccurrence' with unique index 'IX_GroupId_LocationID_ScheduleID_Date'. The duplicate key value is (21900, <NULL>, 457, 2023-06-18). The statement has been terminated.

### Steps to Reproduce

I am not sure how to reproduce this on test data but it is reproducible on our test server but might have something to do with specific individual group settings. 

### Rock Version

15.0

### Client Culture Setting

en-us

**Comment by austinspooner** [comment]
Here is the full stack trace if that is helpful:

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()

**Comment by austinspooner** [comment]
This issue continues to happen on a number of our groups. Its not related to just one group. Is there anything you need from me to help troubleshoot this?

**Comment by zackdutra** [comment]
@austinspooner can you confirm if this was resolved for you in 15.2?
