### ISSUE TITLE
The Remote Host Closed the Connection Exception

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5521]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

This is possibly related to #4652, but the exception/stack trace is different, so I am opening a new bug. This seems to be some issue with the GetAvatar feature introduced in v15.0.

Since updating to v15.1, (possibly in v15.0 also) we have been regularly seeing the following exception:
![Screenshot 2023-07-18 at 11 08 51](https://github.com/SparkDevNetwork/Rock/assets/23226974/6c832350-9812-4efc-a87a-be3d6ef08913)

Stack Trace:
```
at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at RockWeb.GetAvatar.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

### Expected Behavior

No exception.

### Actual Behavior

Exception is logged.

### Steps to Reproduce

See above.

I have been unable to figure out exactly what page(s) or action(s) are causing these exceptions to happen, however, it is happening for people who do not have access to our internal Rock pages, which means most likely, it is happening when users are logged into their external account and/or associated pages.

### Rock Version

v15.1

### Client Culture Setting

en-US

**Comment by dataCollegechurch** [comment]
1. 
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/16a32f3b-3b75-4947-83d0-cd89019dd91b)
2.
I don't see a Cache Folder for that path:
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/cd9af3e0-4491-48df-bc27-44d710cba4a8)

**Comment by jonedmiston** [comment]
Other recommendations from Google:

1. It might seem silly, but there are many issues that can be caused by your system's date and time not syncing up properly with the real world, and error code 0x80070057 is one of them.
2. Run Chkdsk. If the underlying storage hardware you're running has some corrupted data, a damaged partition, or defective hardware, the [Windows error-checking tool](https://www.lifewire.com/how-to-scan-a-hard-drive-using-error-checking-2624497) or the [Chkdsk command](https://www.lifewire.com/chkdsk-command-2625838) can help find and fix them.

From: https://www.lifewire.com/fix-error-code-0x80070057-4691502

**Comment by dataCollegechurch** [comment]
The time on my Azure VM currently looks correct.
I ran chkdsk and will report back tomorrow if the issues continues.

**Comment by mikedotmundy** [comment]
1. 52 out of 126 GB Free space
2. I also do not have a `~\App_Data\Avatar\Cache` directory, however my `~\App_Data\Cache` directory is 91 MB.
3. My Azure VM is displaying the correct time.
4. Windows error-checking tool did not return any issues on my HD.

**Comment by dataCollegechurch** [comment]
Quick update: Exceptions continue to occur after chkdsk was run

**Comment by zackdutra** [comment]
We're experiencing the same issue with GetAvatar.ashx, exactly as shown above

**Comment by robotman3000** [comment]
@dataCollegechurch @mikedotmundy What version of IIS are you using? Is it the same for both of you? I noticed that both your stack traces have `IIS7WorkerRequest`. "IIS7" seems to suggest a very old version of IIS

**Comment by zackdutra** [comment]
Our stack trace also shows the IIS7 message, but we're running version 10

**Comment by mikedotmundy** [comment]
1. We are running IIS10.
2. Our AppPool Identity is running as LocalSystem (and is configured the same as the rest of the settings in the documentation).
3. I'm not sure how to check the permissions for LocalSystem.

**Comment by dataCollegechurch** [comment]
@mikedotmundy - I think you can look at the Security Permissions for the folder in question.

We are also running IIS10 and our App Pool is running as LocalSystem.

I believe LocalSystem shows up as SYSTEM most places. It does have access to create new folders in our case.
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/b449f478-3e0a-4e5b-8340-6c44728bbb8f)

**Comment by mikedotmundy** [comment]
Ok thank you @dataCollegechurch - I wondered if that was it - my permissions look the same.

**Comment by dataCollegechurch** [comment]
This is interesting. I manually added the ~\App_Data\Avatar\Cache folder and the system did start adding files into it. Now I am getting this flavor of exception messages:
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/a0a2142a-e9a6-4647-adb0-a71af6c29486)

**Comment by JimMichael** [comment]
Coming here just to report that I'm seeing this on v16.0 alpha (1.16.0.10). The exceptions happen when I visit a person profile (and sometimes the internal homepage) and the URLs in the exceptions point at valid profile images or images with the initials of the person, but not every time, or for every person. 

I'll note that our Person Image file type is stored on Cloudinary, not on local storage or the db... in case that could be part of the issue. Like others here, we have no /App_Data/Avatar/Cache directory. Only Fonts and Masks are directories there.

Running on Win 2022/IIS10 here.

**Comment by mikedotmundy** [comment]
We are also continuing to see this on Alpha v1.16.0.10.

**Comment by dataCollegechurch** [comment]
We are also using cloudinary, @mikedotmundy @zackdutra , where are you storing your people images?

**Comment by zackdutra** [comment]
We switched to Azure blob storage, but some are still in database

**Comment by nairdo** [comment]
Greetings everyone.  We've done some extensive research on this one and the advisement is:

- A) That exception is normal if/when a client browser drops a connection to the server.  That can happen for a number of reasons.
- B) It's not _generally_ advised to always ignore that exception _unless_ you've considered the specific instance/case.
- C) Therefore, we're going to surgically handle (ignore) this particular exception (for the GetAvatar) call.

That means it's still possible there could be other places in Rock where a "The Remote Host Closed the Connection" exception occurs in the future.  So, if it does happen, please feel free to report it with the stack trace and we'll consider handling/ignoring that case.  Ultimately we could decide to ignore those exceptions system wide, but we'll get there if we get there.

**Comment by mikedotmundy** [comment]
Thanks @nairdo. Will this be included in v16.0? 

Also, what about #4652?

**Comment by dataCollegechurch** [comment]
Anecdotally it appears that this issue is occurring for some churches but not others. If this exception is driven by the client browser dropping the connection, I would expect for this error to be occurring for every church. Personally I would not be comfortable ignoring this error until we could determine either that it is occurring for all churches or why it is only occurring for some.
