### ISSUE TITLE
Cannot Complete Registration when Registrar Option is Use First Registrant

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5624]
### Description

On an Event Registration Template, if you set the `Registrar Options` field to `Use First Registrant`, you are unable to complete the registration and are greeted with an error.

![Screenshot 2023-10-04 at 12 40 56](https://github.com/SparkDevNetwork/Rock/assets/23226974/74f21e72-d51f-4fe7-a56c-dfd1cab61b8f)

<br><br>
![Screenshot 2023-10-04 at 12 39 02](https://github.com/SparkDevNetwork/Rock/assets/23226974/b80f4158-371a-4f98-8893-0a7e32c585dc)

<br><br>
Exception is also created:
![Screenshot 2023-10-04 at 12 42 15](https://github.com/SparkDevNetwork/Rock/assets/23226974/90b8c311-33ff-42bd-9ae1-fe212e492306)

Full Stack Trace:
```
at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ValidateContextsAreCompatible(RelatedEnd targetRelatedEnd)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IEntityWrapper wrappedOwner, RelatedEnd relatedEnd, IEntityWrapper entityToAdd, Boolean isForeignKeyChange)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.InternalContext.GetStateEntries(Func`2 predicate)
   at System.Data.Entity.Infrastructure.DbChangeTracker.Entries()
   at Rock.Data.DbContext.RockPreSave(DbContext dbContext, PersonAlias personAlias, Boolean enableAuditing) in \Rock\Data\DbContext.cs:line 614
   at Rock.Data.DbContext.SaveChanges(SaveChangesArgs args) in \Rock\Data\DbContext.cs:line 326
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing) in \Rock\Data\DbContext.cs:line 290
   at Rock.Blocks.Event.RegistrationEntry.UpsertRegistrant(RockContext rockContext, RegistrationContext context, Person registrar, Guid registrarFamilyGuid, RegistrantInfo registrantInfo, Int32 index, Dictionary`2 multipleFamilyGroupIds, Nullable`1& singleFamilyId, Boolean isWaitlist, Boolean isCreatedAsRegistrant, Boolean isNewRegistration, List`1 postSaveActions) in \Rock.Blocks\Event\RegistrationEntry.cs:line 2429
   at Rock.Blocks.Event.RegistrationEntry.SubmitRegistration(RockContext rockContext, RegistrationContext context, RegistrationEntryBlockArgs args, String& errorMessage) in \Rock.Blocks\Event\RegistrationEntry.cs:line 1148
   at Rock.Blocks.Event.RegistrationEntry.SubmitRegistration(RegistrationEntryBlockArgs args) in \Rock.Blocks\Event\RegistrationEntry.cs:line 481
```

Also, the "This Registration Was Completed By" screen should not appear at all when choosing `Use First Registrant`.

### Actual Behavior

When selecting `Use First Registrant`, 1), you see the "This Registration Was Completed By" box and 2), there is an error message and you are unable to complete the registration.

### Expected Behavior

When selecting `Use First Registrant`, 1), we should not see the "This Registration Was Completed By" box and 2), there should be no error message and registration should complete successfully.

### Steps to Reproduce

Create a simple Registration Template with the following settings:
- Allow Multiple Registrants = no
- Registrar Options = Use First Registrant

See that you cannot complete the registration without seeing an error message.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
@mikedotmundy The exception has been fixed. The `This Registration Was Completed By` is showing up because no Email address was available from the first registrant. If you add an "Email" field and make it required then the `This Registration Was Completed By` message does not show up.
