### ISSUE TITLE
Cannot Create Merge Document from Connection Request Board Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5633]
### Description

When clicking the `Merge Records` button on the Connection Request Board Block while in List view, you are greeted with an error message. An exception is also created.

![Screenshot 2023-10-12 at 13 29 37](https://github.com/SparkDevNetwork/Rock/assets/23226974/7eb286e9-4795-4c01-a713-966cc22205aa)

![Screenshot 2023-10-12 at 14 30 09](https://github.com/SparkDevNetwork/Rock/assets/23226974/6f2a1863-528a-471f-997a-93766624a711)

Stack Trace:
```
at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Rock.Web.UI.Controls.Grid.GetEntitySetFromGridSourceList() in \Rock\Web\UI\Controls\Grid\Grid.cs:line 3908
   at Rock.Web.UI.Controls.Grid.GetEntitySetFromGrid(EventArgs e) in \Rock\Web\UI\Controls\Grid\Grid.cs:line 3566
   at Rock.Web.UI.Controls.Grid.Actions_MergeTemplateClick(Object sender, EventArgs e) in \Rock\Web\UI\Controls\Grid\Grid.cs:line 2141
   at Rock.Web.UI.Controls.GridActions._lbMergeTemplate_Click(Object sender, EventArgs e) in \Rock\Web\UI\Controls\Grid\GridActions.cs:line 709
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

### Actual Behavior

Cannot create a Merge Document.

### Expected Behavior

Should be able to create a Merge Document.

### Steps to Reproduce

- Go to `https://rockrmslatest.com/page/642?ConnectionOpportunityId=1`.
- Make sure you are in List view, not Board view.
- Click the Merge Records button.
- See error.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy Hi Mike - I am unable to recreate this issue on both my local of v16.0 and on rockrmslatest.com.  If you still experience the issue, please provide additional steps or a video.  If I don't hear back from you within the next week, I will close the issue.

**Comment by mikedotmundy** [comment]
https://github.com/SparkDevNetwork/Rock/assets/23226974/d19078bc-d27c-40b2-9050-85077bd35338

**Comment by chead4** [comment]
@mikedotmundy Thanks for the video Mike.  I realized I was selecting the wrong Merge option. I was selecting Merge Person Records and not Merge Records into Merge Template.  I was able to recreate on prealpha and on v16.0.

**Comment by chead4** [comment]
@mijobryco Thanks for letting us know about this issue.  I have recreated the issue and it will be fixed as part of this ticket.
