### ISSUE TITLE
Ampersand ("&") in Content Channel Title Generates Error when Editing Security

### ISSUE THREAD

**Issue by david-axelson** [SparkDevNetwork/Rock#5725]
### Description

Including an ampersand ("&") in the title of a content channel creates an exception when clicking the lock icon to edit permissions.

### Actual Behavior

![Screenshot 2024-01-24 at 1 36 48 PM](https://github.com/SparkDevNetwork/Rock/assets/74628512/18901a90-85d4-4058-8c03-291be00cea5a)

vs

![Screenshot 2024-01-24 at 1 37 11 PM](https://github.com/SparkDevNetwork/Rock/assets/74628512/22dd284a-ff71-4b3f-8ee3-87a2761b9b8c)

(screenshots from rockrmsdemo.com)

Stack Trace:

```

15345 | System.ArgumentNullException | mscorlib | Value cannot be null. Parameter name: key
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) 
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
at Rock.Web.PageReference.GetBreadCrumbPageReferences(RockPage rockPage, PageCache initialPage, PageReference initialPageReference, String keySuffix) in \Rock\Web\PageReference.cs:line 871
at Rock.Web.UI.RockPage.OnInit(EventArgs e) in \Rock\Web\UI\RockPage.cs:line 1489
at ASP.themes_rock_layouts_dialog_aspx.OnInit(EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

### Expected Behavior

Either no error when using ampersand or validation on the Content Channel title to prevent error.

### Steps to Reproduce

- Go to https://rockrmsdemo.com/admin/cms/content-channels.
- Create New Content Channel with Ampersand ("&") in Title.
- Click Lock icon to edit Security for the Content Channel - error will show.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.2

### Client Culture Setting

en-US

**Comment by TheArkChurch** [comment]
I can confirm this on 16.2
