### ISSUE TITLE
[1.16.7.2 Alpha] Nextgen Checkin errors and doesn't allow seemingly random people to check-in

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#6056]
### Description

I was testing Nextgen Check-in on the new alpha cycle. When I try to check myself in to any check-in configuration using nextgen check-in, I get the following error: `An error has occurred` (see GIF below).
![main_large-3](https://github.com/user-attachments/assets/533d07c4-cfa4-4b2b-adbb-b2d035a89eb1)

Here's the exception screenshots and stack trace:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/232fa853-8e7e-4c54-985c-c674641c7ca0">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e167391d-f4d5-4e61-9f8a-5baea16d5e74">

```
The cast to value type 'System.Int32' failed because the materialized value is null. Either the result type's generic parameter or the query must use a nullable type.
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.ErrorHandlingValueReader`1.GetValue(DbDataReader reader, Int32 ordinal)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.CheckIn.v2.CheckInDirector.GetRecentAttendance(DateTime cutoffDateTime, IReadOnlyList`1 personIds, RockContext rockContext) in \Rock\CheckIn\v2\CheckInDirector.cs:line 365
   at Rock.CheckIn.v2.CheckInSession.LoadAttendees(IReadOnlyCollection`1 members, OpportunityCollection baseOpportunities) in \Rock\CheckIn\v2\CheckInSession.cs:line 328
   at Rock.CheckIn.v2.CheckInSession.LoadAndPrepareAttendeesForFamily(String familyId, IReadOnlyCollection`1 possibleAreas, DeviceCache kiosk, IReadOnlyCollection`1 locations) in \Rock\CheckIn\v2\CheckInSession.cs:line 200
   at Rock.Rest.v2.CheckInController.PostFamilyMembers(FamilyMembersOptionsBag options) in \Rock.Rest\v2\CheckInController.cs:line 259
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()
```

Now, I've tried several different profiles and check-in configurations and cannot find any commonality among them. It's not every profile, just random ones. Some have security roles, some don't. The profiles I've tried with have person Ids varying from a single digit to 5 digits, and family Ids in the 5-6 digit range. There's also a varying number of people in the specific families I've tested - anywhere from 1 individual to 7 individuals. We also thought it may be profiles who don't have previous attendance records for the configuration, but we were able to rule that out as well.

It happens regardless if I search by name or phone, and if it affects one individual in the family then no one in the family can check in (leads me to believe the issue is at the family level, but I can't seem to figure out what).

Here's the configuration of three check-in areas I've tested with:
<img width="1666" alt="image" src="https://github.com/user-attachments/assets/d945cd6e-a893-4768-bbb8-6c5e7f2a768e">

<img width="1688" alt="image" src="https://github.com/user-attachments/assets/56329a55-0e84-4355-9570-a59ac64687a5">

<img width="1673" alt="image" src="https://github.com/user-attachments/assets/7cecbc75-9ac7-40df-b9f2-73ed0d45ab94">

Let me know what else I can provide that would help track this down!

### Actual Behavior

When trying to checkin using Nextgen check-in, certain profiles / families error out and are unable to check-in at all. 

### Expected Behavior

I would expect that all profiles would be able to check-in and not get an error.

### Steps to Reproduce

I don't really have reproduction steps, but in our instance using pre-configured check-in areas (and the new nextgen checkin pages), here are the steps I follow to get the error.

- Adjust a check-in configuration with locations and a schedule you can test with that is currently active (see ours below)
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/7fdacc37-c3b8-4f8b-97c2-b4068d5be137">

- In a browser, navigate to https://yourrockserver.com/nextgen-checkin
- Setup check-in with the kiosk / areas you are testing
- Type in the phone number of an individual who the issue affects 
   - I have a list of people this affects, just can't find any commonality among them
- Tap on the family
- Notice the error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by leahjennings** [comment]
Here's a screenshot of the console:
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/7913ff90-0f3e-4633-886f-09edfdcb5c25">
