### ISSUE TITLE
[Pre-Alpha 1.17.0.32] RockQueue.Drain() Exception on Insert to Interaction Table

### ISSUE THREAD

**Issue by jr-peck** [SparkDevNetwork/Rock#6113]
### Description

Rock is recording regular exceptions on attempts to make inserts to the Interaction table that fail due to a duplicate Guid.

This screenshot is from rockrmslatest.com and shows the issue. On a server under heavier load we are seeing exceptions generated roughly every 2 minutes. ( 870 - 880 a day ).

![image](https://github.com/user-attachments/assets/08be685e-9143-4860-8efc-37ca3a7e70a1)

The exceptions started following deployment of 1.17.0.31

### Actual Behavior

Actual Behavior

The details for the exception have two traces. The first is:
```
System.Exception		Exception in RockQueue.Drain(): InteractionTransaction	
   
at RockWeb.Global.LogError(Exception ex, HttpContext context)
   at RockWeb.Global.<>c.b__30_0(Exception ex)
   at Rock.Transactions.RockQueue.Drain(Action`1 errorHandler)
   at RockWeb.Global.DrainTransactionQueue()
   at RockWeb.Global.<>c.b__32_0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
The second is:
```
System.Data.SqlClient.SqlException	.Net SqlClient Data Provider	Cannot insert duplicate key row in object 'dbo.Interaction' with unique index 'IX_Guid'. The duplicate key value is (c941f27d-be22-4771-8561-6554f7478bd4). The statement has been terminated.	
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DbDataReader reader)
   at EntityFramework.Utilities.SqlQueryProvider.InsertItems[T](IEnumerable`1 items, String schema, String tableName, IList`1 properties, DbConnection storeConnection, Nullable`1 batchSize)
   at EntityFramework.Utilities.EFBatchOperation`2.InsertAll[TEntity](IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)
   at Rock.Data.DbContext.BulkInsertWithConditionalCacheUse[T](IEnumerable`1 records, Boolean canUseCache) in \\Rock\Data\DbContext.cs:line 1092
   at Rock.Transactions.InteractionTransaction.LogInteractions(List`1 interactionTransactionInfos, RockContext rockContext) in \\Rock\Transactions\InteractionTransaction.cs:line 253
   at Rock.Transactions.InteractionTransaction.Execute() in \\Rock\Transactions\InteractionTransaction.cs:line 227
   at Rock.Transactions.RockQueue.Drain(Action`1 errorHandler) in \\Rock\Transactions\RockQueue.cs:line 237
   ```

### Expected Behavior

Expected Behavior

That the insert succeed without an exception.

### Steps to Reproduce

- Go to Settings/System/Exception List
- Search for 'RockQueue.Drain()'
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.17.0.31, 1.17.0.32

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
I'm not sure if this is of value, but I received a similar issue 2 days ago in our production v16.6 instance. 

First Trace:
```
at RockWeb.Global.LogError(Exception ex, HttpContext context)
   at Rock.Transactions.RockQueue.Drain(Action`1 errorHandler)
   at RockWeb.Global.DrainTransactionQueue()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Second Trace:
```
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DbDataReader reader)
   at EntityFramework.Utilities.SqlQueryProvider.InsertItems[T](IEnumerable`1 items, String schema, String tableName, IList`1 properties, DbConnection storeConnection, Nullable`1 batchSize)
   at EntityFramework.Utilities.EFBatchOperation`2.InsertAll[TEntity](IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)
   at Rock.Data.DbContext.BulkInsertWithConditionalCacheUse[T](IEnumerable`1 records, Boolean canUseCache) in \Rock\Data\DbContext.cs:line 1061
   at Rock.Transactions.InteractionTransaction.LogInteractions(List`1 interactionTransactionInfos, RockContext rockContext) in \Rock\Transactions\InteractionTransaction.cs:line 313
   at Rock.Transactions.InteractionTransaction.Execute() in \Rock\Transactions\InteractionTransaction.cs:line 255
   at Rock.Transactions.RockQueue.Drain(Action`1 errorHandler) in \Rock\Transactions\RockQueue.cs:line 233
```

**Comment by chead4** [comment]
@mikedotmundy Thanks for letting us know, please include a screenshot with Stack Trace of the exception.  I'm reopening this issue and will let the team know the exception is occurring again.

**Comment by mikedotmundy** [comment]
<img width="2051" alt="Image" src="https://github.com/user-attachments/assets/e97dd6eb-b7bd-49fc-99ce-5dbf7a936dba" />

**Comment by azturner** [comment]
Not positive this is related, but seems to be since exception message and stack trace is very similar. We are seeing (in v16.8) occasionally when an attribute is updated twice in quick succession. An duplicate key exception will occur when Rock is attempting to update history table:

![Image](https://github.com/user-attachments/assets/72b773f9-dbf8-4965-8015-3f96d4b8c7d4)

**Comment by chead4** [comment]
@azturner Thanks for the additional details David.  I will add to our internal ticket.

**Comment by chead4** [comment]
@azturner Hi David - I spoke with the dev team, and since this involves a different table (History) compared to the original ticket, could you please create a new GitHub issue for your comment above? Thanks!

**Comment by mikedotmundy** [comment]
@chead4 Not sure if this is helpful or if it is you guys doing it on purpose for testing, but the exception has been created on the prealpha site over the past few days. [https://rockrmslatest.com/admin/system/exceptions/1440](https://rockrmslatest.com/admin/system/exceptions/1440)

**Comment by chead4** [comment]
@mikedotmundy Thanks for reaching out.  We have an internal issue for this exception and I'll add a comment on this ticket to keep everyone updated as to when it is resolved.

**Comment by chead4** [comment]
Just a quick update — I'm going to go ahead and close this issue for now, since we haven’t seen any timeout or duplicate key exceptions since starting the beta testing with v17. If you do run into this issue again, please feel free to submit a new GitHub issue and include the exception details along with the full stack trace. Thanks so much!

**Comment by markewampler** [comment]
@chead4 I am going to try something.  It happens daily for us once a day, and I just investigated it, and I want to try and see if something on my end will resolve it.  If so that will be helpful information to put in there.
