### ISSUE TITLE
Adding Job to Jobs List Throws Exception Error

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#807]
When I click on the Add button to add a job I get an error page. Not sure if it is just my instance of Rock or a general bug in Rock.

HttpUnhandledException in System.Web

Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.themes_rock_layouts_fullwidth_aspx.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

- TargetInvocationException in mscorlib

Message
Exception has been thrown by the target of an invocation.
Stack Trace
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Rock.Web.UI.Controls.ComponentPicker.set_ContainerType(String value)
   at Rock.Field.Types.ComponentFieldType.EditControl(Dictionary`2 configurationValues, String id)
   at Rock.Web.Cache.AttributeCache.AddControl(ControlCollection controls, String value, String validationGroup, Boolean setValue, Boolean setId, Nullable`1 required, String labelText)
   at Rock.Attribute.Helper.AddEditControls(String category, List`1 attributeKeys, IHasAttributes item, Control parentControl, String validationGroup, Boolean setValue, List`1 exclude)
   at Rock.Attribute.Helper.AddEditControls(IHasAttributes item, Control parentControl, Boolean setValue, String validationGroup, List`1 exclude, Boolean supressOrdering)
   at RockWeb.Blocks.Administration.ScheduledJobDetail.ShowDetail(Int32 serviceJobId)
   at RockWeb.Blocks.Administration.ScheduledJobDetail.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

-- MissingMethodException in mscorlib

Message
Method not found: 'Void Rock.Attribute.TextFieldAttribute..ctor(System.String, System.String, Boolean, System.String, System.String, Int32, System.String)'.
Stack Trace
   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at Microsoft.Internal.AttributeServices.GetAttributes[T](ICustomAttributeProvider attributeProvider)
   at System.ComponentModel.Composition.Hosting.CompositionServices.TryExportMetadataForMember(MemberInfo member, IDictionary`2& dictionary)
   at System.ComponentModel.Composition.AttributedModel.AttributedExportDefinition.get_Metadata()
   at System.ComponentModel.Composition.ReflectionModel.ReflectionMemberExportDefinition.get_Metadata()
   at System.ComponentModel.Composition.Primitives.ContractBasedImportDefinition.MatchRequiredMetadata(ExportDefinition definition)
   at System.ComponentModel.Composition.Primitives.ContractBasedImportDefinition.IsConstraintSatisfiedBy(ExportDefinition exportDefinition)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.TryGetNonGenericExports(ImportDefinition definition, Tuple`2& singleMatch, IEnumerable`1& multipleMatches)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.TryGetExports(ImportDefinition definition, Tuple`2& singleMatch, IEnumerable`1& multipleMatches)
   at System.ComponentModel.Composition.Primitives.ComposablePartCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.<>c__DisplayClass2.b__0()
   at System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)
   at Rock.Extension.Container`2.Refresh()
   at Rock.Financial.GatewayContainer.<.cctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Rock.Financial.GatewayContainer.get_Instance()

**Comment by azturner** [comment]
@BEGamache  This looks like it may be caused by a payment gateway provider that is not in sync with the Rock core files.  Can you check the date, file size, and version of your Rock.dll and the Rock.PayFlowPro.dll and post those details here?

**Comment by edmistj** [comment]
@BEGamache Any update?

**Comment by BEGamache** [comment]
Sorry guys. I haven’t had a chance to look at it yet. I’ll try and get to it before in the next hour or two. Sorry for the delay.

Sincerely,
Brandon Gamache
Crossroads Christian Church
6450 South State Highway 360
Grand Prairie, Texas 75052
(817) 557-2277
CrossroadsChristian.org

**Comment by BEGamache** [comment]
Turns out it was an extra gateway that was causing the issue. The same issue prevented me from accessing the Financial Gateways page so I removed the .dll and restarted Rock. I can now access both the Job addition page and Financial Gateway page. Looks like the Job addition issue was thrown because GetScheduledPayments is the default or first Job Type in the list. 

Sorry for the trouble.
