### ISSUE TITLE
Check-in Exceptions - NullReferenceException in DDay.iCal

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#866]
I was getting these exceptions every so often during testing, but we have had over 400 last night and this morning during our first weekend of live Rock check-in:

`An error occurred on the Rock Check-in site on page: 
https://checkin.newpointe.org:443/checkin/welcome
HttpUnhandledException in System.Web
Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.themes_checkinnewpointeorange_layouts_checkin_aspx.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-NullReferenceException in DDay.iCal
Message
Object reference not set to an instance of an object.
Stack Trace
at DDay.iCal.Serialization.iCalendar.EncodableDataTypeSerializer.DecodeData(IEncodableDataType dt, String value)
at DDay.iCal.Serialization.iCalendar.EncodableDataTypeSerializer.Decode(IEncodableDataType dt, String value)
at DDay.iCal.Serialization.iCalendar.StringSerializer.Deserialize(TextReader tr)
at DDay.iCal.Serialization.iCalendar.DataMapSerializer.Deserialize(TextReader tr)
at DDay.iCal.iCalParser.property(ISerializationContext ctx, ICalendarPropertyListContainer c)
at DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
at DDay.iCal.iCalParser.icalbody(ISerializationContext ctx, IICalendar iCal)
at DDay.iCal.iCalParser.icalendar(ISerializationContext ctx)
at DDay.iCal.Serialization.iCalendar.iCalendarSerializer.Deserialize(TextReader tr)
at DDay.iCal.Serialization.iCalendar.SerializerBase.Deserialize(Stream stream, Encoding encoding)
at DDay.iCal.iCalendar.LoadFromStream(Stream s, Encoding e, ISerializer serializer)
at DDay.iCal.iCalendar.LoadFromStream(TextReader tr, ISerializer serializer)
at DDay.iCal.iCalendar.LoadFromStream(TextReader tr)
at Rock.Model.Schedule.GetCalenderEvent()
at Rock.CheckIn.KioskSchedule..ctor(Schedule schedule)
at Rock.CheckIn.KioskDevice.LoadKioskLocations(KioskDevice kioskDevice, Location location, Nullable`1 campusId, RockContext rockContext)
at Rock.CheckIn.KioskDevice.LoadKioskLocations(KioskDevice kioskDevice, Location location, Dictionary`2 campusLocations, RockContext rockContext)
at Rock.CheckIn.KioskDevice.Read(Int32 id, List`1 configuredGroupTypes)
at Rock.CheckIn.CheckInState.get_Kiosk()
at RockWeb.Blocks.CheckIn.Welcome.RefreshView()
at RockWeb.Blocks.CheckIn.Welcome.lbRefresh_Click(Object sender, EventArgs e)
at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Most times, it just slows down the check-in pages, but every so often the iPad actually shows the exception screen.

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/a79a101fd90a7e6d648af44cdf46d135b02b5ebd
