### ISSUE TITLE
InvalidOperationException in mscorlib on External Scheduled Transaction Page

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#889]
I've been seeing the below error a lot, but I can't reproduce it.  I'll see if I can get anymore info:

>An error occurred on the My NewPointe site on page: 
https://my.newpointe.org:443/page/325?ScheduledTransactionId=32
HttpUnhandledException in System.Web
Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.themes_newpointe_layouts_leftsidebar_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\e22c2559\92c7e946\App_Web_yvgmnjo3.2.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-InvalidOperationException in mscorlib
Message
Nullable object must have a value.
Stack Trace
at System.Nullable`1.get_Value()
at RockWeb.Blocks.Finance.ScheduledTransactionEdit.ProcessPaymentInfo(String& errorMessage) in c:\inetpub\wwwroot\Blocks\Finance\ScheduledTransactionEdit.ascx.cs:line 848
at RockWeb.Blocks.Finance.ScheduledTransactionEdit.btnNext_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\Finance\ScheduledTransactionEdit.ascx.cs:line 411
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by bwitting** [comment]
@edmistj  Ok, I figured out what is causing this - if you leave a fund at 0 on the scheduled transaction page (internal or external), you get the exception and can't save your updated giving.  This seems to be a pretty serious problem - you basically can't update a scheduled transaction unless you are giving to every fund on the screen.

**Comment by azturner** [comment]
@bwitting , I've tried to reproduce this and am not able to. The exception actually looks like it has something to do with the payment frequency selected not being a valid frequency ( in the list of frequency defined values ). When you view the block do you have a blank frequency option displayed by any chance, or have you changed frequencies at all?

**Comment by bwitting** [comment]
@azturner - I'm not even seeing where you can change a frequency. I didn't even edit anything this time. Check out the following video: 

https://vimeo.com/121813634  (Password is **Rock!**)

The first part is the internal page - I opened the schedule and clicked Save, and got the exception.  The second part is External page - same thing.

We're using PayFlowPro and haven't altered anything with scheduling.

**Comment by azturner** [comment]
@bwitting, That would be a problem :). The Frequency is determined by the selected gateway. Can you verify that the block settings for those blocks have the PayFlowPro gateway set for both Credit Card and ACH.

**Comment by bwitting** [comment]
Oh geez. You're right, the block settings were on TestGateway for both.  That took care of the issue.  Thanks!
