### ISSUE TITLE
3.0 Person Merge times out. 

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#921]
In McKinley 3.0, I can't merge people - I get a timeout every time. 

>An error occurred on the Rock RMS site on page: 
https://rock.newpointe.org:443/PersonMerge/207

HttpUnhandledException in System.Web

Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.

Stack Trace
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.themes_rock_layouts_fullwidth_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\e22c2559\92c7e946\App_Web_zw0nyxkq.2.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

-SqlException in .Net SqlClient Data Provider

Message
Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

Stack Trace
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at Rock.Data.DbService.ExecuteCommand(String query, CommandType commandType, Dictionary`2 parameters, Nullable`1 commandTimeout)
at RockWeb.Blocks.Crm.PersonMerge.lbMerge_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\Crm\PersonMerge.ascx.cs:line 460
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

--Win32Exception in

Message
The wait operation timed out

Stack Trace

**Comment by azturner** [comment]
@bwitting , do you by any chance have any workflow triggers defined? If so, would you be able to temporarily inactivate those triggers ( uncheck the active checkbox ) in your beta install, and try the mege again, and let me know if that makes a difference.

**Comment by bwitting** [comment]
@azturner Sorry David, I don't have any workflow triggers defined. Is there anything else I can check?

**Comment by bwitting** [comment]
Seems fixed in 3.1
