### ISSUE TITLE
Unable to Access History

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#999]
When accessing a student's history, the following error comes up:

An exception has occurred. Details of this error can be found below: 
An error occurred on the Rock RMS site on page: 
https://rock.belairpres.org:443/Person/4602/History
HttpUnhandledException in System.Web
Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-NullReferenceException in System.Web
Message
Object reference not set to an instance of an object.
Stack Trace
at System.Web.UI.WebControls.ListControl.PerformDataBinding(IEnumerable dataSource)
at System.Web.UI.WebControls.ListControl.PerformSelect()
at RockWeb.Blocks.Checkin.AttendanceHistoryList.BindFilter()
at RockWeb.Blocks.Checkin.AttendanceHistoryList.OnLoad(EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by BelAirIT** [comment]
It seems to happen after adding kids' records manually into group attendance.
![image](https://cloud.githubusercontent.com/assets/7409839/7382040/1116df4c-edbf-11e4-8429-189e2eef2e44.png)
